Add TokenPricesReader implementation
smartcontractkit/ccip pull request #1013
Opened 2024-06-13 16:02 UTC by asoliman92

Add TokenPricesReader implementation for use in ocr3

2024-06-13 16:11 UTC, dimkouv requested changes

2024-06-13 16:11 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +		contractName = "PriceRegistry"
we call the `PriceAggregator` contract not price registry

2024-06-13 16:11 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	var prices []*cciptypes.BigInt
use `make([]cciptypes.BigInt, 0, len(tokens)`
check what `slice capacity` is

2024-06-13 16:11 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +				return nil, err
wrap the errors using `fmt.Errorf("some msg %w", err)`

2024-06-13 16:11 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +		if staticPrice, exists := pr.TokenPriceConfig.StaticPrices[token]; exists {
use goroutines to fetch prices in parallel, mentioned in the ticket

2024-06-13 16:11 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	StaticPrices map[ocrtypes.Account]*cciptypes.BigInt `json:"staticPrice"`
json tag has typo

2024-06-18 09:27 UTC, dimkouv reviewed
resolve linter errors

2024-06-18 09:27 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/factory.go
> +	onChainTokenPricesReader := reader.OnchainTokenPricesReader{
use a factory to initialize things otherwise after adding a new field you have to go and update all the initializations. i.e. `NewOnchainTokenPricesReader`

2024-06-18 09:27 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/factory.go
> +	onChainTokenPricesReader := reader.OnchainTokenPricesReader{
constructor can return a pointer

2024-06-18 09:27 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	ctx, cancel := context.WithCancel(ctx)
use `https://pkg.go.dev/golang.org/x/sync/errgroup` instead of `errChan,ctx,wg,..`

2024-06-18 09:27 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	return prices, nil
the goroutines logic can be simplified a lot with the errgroup

2024-06-18 12:34 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	ctx, cancel := context.WithCancel(ctx)
neat :+1:

2024-06-18 12:38 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +			}
nit (since it wont be used with errgroup): Even though what you have is technically correct, I would have just made the assignment instead of checking the context.

2024-06-19 10:54 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	ctx, cancel := context.WithCancel(ctx)
A newbie thing :D. errorgroup looks much better I agree.

2024-06-19 20:06 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +				println("staticPrice: ", staticPrice.String(), "\n")
All prints are for local debugging. Will remove before merging.

2024-06-20 12:40 UTC, dimkouv requested changes

2024-06-20 12:40 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/mocks/contract_reader.go
> +func (hr *ContractReaderMock) GetLatestValue(ctx context.Context, contractName, method string, params, returnVal any) error {
What does `hr` stand for?

2024-06-20 12:40 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	if len(prices) != len(tokens) {
This condition is always `false` because of the way you initialize the prices slice.

2024-06-20 12:40 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	if len(prices) != len(tokens) {
safe to remove

2024-06-20 12:40 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	if len(prices) != len(tokens) {
or iterate over prices and return error if one of them is nil

2024-06-20 12:41 UTC, dimkouv approved these changes
approving, since logic looks good.
just fix this non-required check before merging

2024-06-20 13:15 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/mocks/contract_reader.go
> +func (hr *ContractReaderMock) GetLatestValue(ctx context.Context, contractName, method string, params, returnVal any) error {
copy paste typo :D, it was for homereader

2024-06-20 13:29 UTC, 0xnogo commented on core/services/ocr3/plugins/ccip/internal/mocks/contract_reader.go
> +func (hr *ContractReaderMock) GetLatestValue(ctx context.Context, contractName, method string, params, returnVal any) error {
Could we use `Mockery` for mocks generation? This would help us standardize better code. Consider this comment as nit.

2024-06-20 13:30 UTC, 0xnogo approved these changes

2024-06-20 13:30 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/mocks/contract_reader.go
> +func (hr *ContractReaderMock) GetLatestValue(ctx context.Context, contractName, method string, params, returnVal any) error {
We should standardize on using mockery to generate mocks: take a look at `//go:generate mockery` for examples.

2024-06-20 13:34 UTC, merged

2024-06-20 13:38 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	}
What do you think about including the nil tokens in this error message? i.e.
```suggestion
	var nilTokens []ocr2types.Account
	for i, price := range prices {
		if price == nil {
			nilTokens = append(nilTokens, tokens[i])
		}
	}
	if len(nilTokens) != 0 {
		return nil, fmt.Errorf("failed to get all token prices successfully, some prices are nil: %s", strings.Join(nilTokens, ","))
	}
```

2024-06-20 13:41 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader.go
> +	}
oops, just merged 😅. I like the idea. I'll make another simple PR for it once I finish the home chain config comments. 👍

2024-06-20 13:42 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/onchain_prices_reader_test.go
> +func TestOnchainTokenPricesReader_GetTokenPricesUSD(t *testing.T) {
You could add another test for the mock reader returning an error for Could you add another test for `GetLatestValue` returning an error.