[TT-1218] new incarnation of compatibility pipeline
smartcontractkit/ccip pull request #1022
Opened 2024-06-14 09:22 UTC by Tofel

2024-06-24 14:09 UTC, kalverra requested changes

2024-06-24 14:09 UTC, kalverra commented on .github/workflows/ccip-client-compatibility-tests.yml
> +    - cron: "30 5 * * TUE,FRI" # Run every Tuesday and Friday at midnight + 30min EST
Why not every weeknight?

2024-06-24 14:09 UTC, kalverra commented on .github/workflows/ccip-client-compatibility-tests.yml
> +          slack_channel_id: ${{ secrets.QA_SLACK_CHANNEL }}
Do we want to change this?

2024-06-24 14:53 UTC, Tofel commented on .github/workflows/ccip-client-compatibility-tests.yml
> +    - cron: "30 5 * * TUE,FRI" # Run every Tuesday and Friday at midnight + 30min EST
no need to. We run on Tue an Fri and check whether during last 4 days there was a new stable release. This way I think it runs often enough to give us fast feedback and doesn't create much noise. Due to that schedule we won't miss any release.

2024-06-25 15:46 UTC, kalverra approved these changes

2024-06-25 17:14 UTC, kalverra approved these changes

2024-06-26 16:36 UTC, AnieeG approved these changes

2024-06-26 17:27 UTC, merged