Handle TokenDeployer client creation when there is more than 1 router per chain
smartcontractkit/ccip pull request #1027
Opened 2024-06-14 16:48 UTC by AnieeG

## Motivation

## Solution

2024-06-14 16:52 UTC, kalverra requested changes

2024-06-14 16:52 UTC, kalverra commented on integration-tests/ccip-tests/testconfig/tomls/ccip-default.toml
> +CCIPOwnerTokens = false # if true, the test will use deploy the tokens by the CCIPOwner, otherwise the tokens will be deployed by a non-owner account, only applicable for 1.5 pools and onwards
Thanks for adding this, though I think we should make it `true` by default. If you run with an older contract, the test should just fail.

2024-06-14 16:54 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/tomls/ccip-default.toml
> +CCIPOwnerTokens = false # if true, the test will use deploy the tokens by the CCIPOwner, otherwise the tokens will be deployed by a non-owner account, only applicable for 1.5 pools and onwards
The default runs the test with latest contract, should it not be false in this case?
I can add one more comment mentioning that you need to change it to true , if you are running with pre-1.5 pools

2024-06-14 16:54 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/tomls/scalability.toml
> +CCIPOwnerTokens = true
Here I have made it as true , as the contract version is 1.4

2024-06-17 17:59 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/tomls/contract-version1.4.toml
> +[CCIP]
Added this to ensure CI tests are running with previous versioned contracts as well

2024-06-17 20:06 UTC, kalverra approved these changes

2024-06-17 20:12 UTC, jasonmci approved these changes
approved

2024-06-17 21:08 UTC, merged