[CCIP-2563] [CCIP-2422] TransferConfig Tests
smartcontractkit/ccip pull request #1030
Opened 2024-06-14 20:08 UTC by kalverra

## Motivation

Smoke test coverage is light on different transfer configs.

## Solution

Adds a transfer config smoke test to check different combinations of configs and tokens and ensure they pass properly.

2024-06-24 15:53 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	DefaultRequestGasLimit       = 600_000
```suggestion
	DefaultDestinationGasLimit       = 600_000
```

2024-06-24 15:55 UTC, AnieeG requested changes
Build error

2024-06-24 16:05 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
>  type TestConfigOverrideOption func(*CCIPTestConfig) string
A comment would be useful here stating what should be the return value

2024-06-24 17:52 UTC, b-gopalswami commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +		if amount == nil { // make nil transfer amount 0 to avoid panics
```suggestion
		if amount == nil { // make nil transfer amount as 0 to avoid panics
```

2024-06-24 17:52 UTC, b-gopalswami commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	DefaultRequestGasLimit       = 600_000
If we don't have different Gas limits, then I'd suggest to go for `DefaultGasLimit`. If that's not the case, then it make sense to call it appropriately.

2024-06-24 17:52 UTC, b-gopalswami commented on integration-tests/ccip-tests/contracts/contract_models.go
> +// SetTokenTransferFeeConfig sets the token transfer fee configuration for the OnRamp
🌟

2024-06-24 17:52 UTC, b-gopalswami commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	}
Should we add test for bidirectional as it is supported in every lane?

2024-06-24 18:05 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	DefaultRequestGasLimit       = 600_000
Yes there are other gaslimits. This is specifically used in ExtraAgrs of ccip-msg struct to notify destination gas limit

2024-06-25 13:07 UTC, kalverra commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	}
@AnieeG ? I'm not sure it matters much for this test as we're not explicitly checking anything with bidirectional lanes here. Might be redundant?

2024-06-25 18:48 UTC, AnieeG approved these changes

2024-06-25 18:48 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +			if sourceCCIP.TransferAmount[i] == nil { // nil transfer amount means no transfer for this token
want to keep it nil?

2024-06-25 18:52 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +			if sourceCCIP.TransferAmount[i] == nil { // nil transfer amount means no transfer for this token
We should definitely keep the check. But I did remove the times when we set it to nil in the test.

2024-06-25 18:54 UTC, AnieeG commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	}
Right, it is just to check the config functionality. no need for bi-directional

2024-06-27 15:50 UTC, b-gopalswami approved these changes

2024-06-27 17:32 UTC, merged