Leader lane orm
smartcontractkit/ccip pull request #1032
Opened 2024-06-15 04:39 UTC by matYang

## Motivation

## Solution

2024-06-17 13:04 UTC, mateusz-sekara requested changes

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +			jobId:                 jb.ID,
This information is already encapsulated in `priceCleanup` and `priceWrite` structs which makes interactions a bit complex ![image](https://github.com/smartcontractkit/ccip/assets/18304098/4be9d7b0-5fe7-4fae-81ec-e8df77bb7c5c)

It would be simpler not to expose orm, jobId etc in the CommitPlugin and simplify interactions between components. Also it seems that from the client perspective (CommitPlugin) it would be easier to register a single Service and interact with it. I suggest encapsulating all the details about gas/token prices logic into `PriceService` and make the responsibility and boundaries between components more obvious
![image](https://github.com/smartcontractkit/ccip/assets/18304098/8b51f86c-3ef8-41f1-91c3-eeb825c9b323)

Plugin configuration is simpler because you don't need to pass orm and jobId there. Mocking is easier because you only need to mock `PriceService` instead of form and price service. The plugin always calls db through this "service" layer. You register only `X` services instead of `2X` per lane

Something like this should work

```go
type PriceService interface {
	job.ServiceCtx
	UpdateDynamicConfig(ctx context.Context, prices.GasPriceEstimatorCommit, ccipdata.PriceRegistryReader) error
	GetGasTokenPrices(ctx context.Context, destChainSelector uint64) ([]GasPrice, []TokenPrice, error)
}

type priceService struct {
	lggr logger.Logger

	services.StateMachine
	wg               *sync.WaitGroup
	backgroundCtx    context.Context //nolint:containedctx
	backgroundCancel context.CancelFunc
}

func (p *priceService) Start(context.Context) error {
	return p.StateMachine.StartOnce("PriceService", func() error {
		p.lggr.Info("Starting PriceService")
		p.wg.Add(1)
		p.run()
		return nil
	})
}

func (p *priceService) Close() error {
	return p.StateMachine.StopOnce("PriceService", func() error {
		p.lggr.Info("Closing PriceService")
		p.backgroundCancel()
		p.wg.Wait()
		return nil
	})
}

func (p *priceService) run() {
	cleanupTicker := time.NewTicker(withJitter(p.cleanupInterval))
	updateTicker := time.NewTicker(withJitter(p.updateInterval))

	go func() {
		for {
			select {
			case <-p.backgroundCtx.Done():
				return
			case <-cleanupTicker.C:
				p.runCleanup()
			case <-updateTicker.C:
				p.runUpdate()
			}
		}
	}()
}

func (p *priceService) GetGasTokenPrices(ctx context.Context, destChainSelector uint64) ([]GasPrice, []TokenPrice, error) {
	gas := p.orm.GetGasPricesByDestChain(ctx, destChainSelector)
	tokenPrices := p.orm.GetTokenPricesByDestChain(ctx, destChainSelector)
	return gas, tokenPrices, nil
}
```

You have one single `PriceService` that encapsulates all the logic related to the token prices, gas prices. CommitPlugin doesn't call ORM directly but it always uses PriceService as a proxy. There is a single `Service` to be registered which is more lightweight if you consider that service will be registered per lane.

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup.go
> +	eg.Go(func() error {
If we don't care about the results then why two separate queries for deleting instead of running single one that deletes both gas prices and token prices?

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup.go
> +	cleanupInterval = priceExpireSec * time.Second
Are you sure about linking `cleanupInterval` with `priceExpireSec`? I understand that `priceExpiration` is based on the product requirements, but why do you want to clean the database every 8 hours? What's the expected number of prices that would be generated during that window? Is it related to the number of lanes/chains? 
I would say that you should perform cleanup more often to reduce the risk of deleting an extreme number of rows at once (and generating an IOPS spike on the db end). Especially if you consider that delete queries don't have any paging in place

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	err := c.updatePrices(c.backgroundCtx)
This is wrong in my opinion, `c.backgroundCtx` is reserved for the underlying background worker's lifecycle. Whereas here you need to pass context from CommitPlugin/Factory, because you run this in "foreground" thread and you want to respect timeouts/cancellations passed from the calling function.

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +func (c *priceWrite) executeUpdate(ctx context.Context) error {
Probably this function is redundant because it only lock mutex and call `updatePrices`, could be inlined in my opinion

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	for _, gasPrice := range gasPricesInDB {
Why do fetch all gas prices if we need only a single one? Shouldn't we apply that on the query level as well? I mean filtering by sourceChainSelector

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		nil, // This is related to DynamicConfig, it is later set in NewReportingPlugin
Does it make sense to expose these fields in the constructor if they cannot be assigned during struct init and we always pass `nil` there? (if you need that for tests then I suggest creating separate constructor that is not public)

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	ticker := time.NewTicker(c.updateInterval)
I suggest wrapping that with `withJitter` (see LogPoller for instance), it will reduce the risk of calling db exactly the same moment from all the registered services

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	if c.gasPriceEstimator == nil {
This should be probably the first line of the function. You've already performed a couple of operations that are heavy (e.g. called priceGetter) just to discover that you shouldn't have done that at all because struct is not yet initialized

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	if c.gasPriceEstimator == nil {
Also, I think that this `gasPriceEstimator == nil` is already checked in the parent function, right?

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	c.dynamicConfigMu.Lock()
Do you need a write lock at this stage? I think that RLock/RUnlock should be sufficient because you don't change any state during `updatePrices` right?

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup_test.go
> +func Test_priceCleanupInBackground(t *testing.T) {
What does this test verify? Entire database is mocked so you only check if mocks are called, right? Test like this is very fragile because it relies on knowing how the deleting is implemented, any change to the underlying logic (e.g. how records are deleted) is gonna break it.

I would suggest using a real database here and rely on the fact that records are actually inserted/removed from the database 

for instance sth like this

```go

func Test_PriceCleanupInBackground(t *testing.T) {
    
     priceService.updatePrices()
     assertLen(priceService.GetTokenGasPrices()), X)

     AssertEventually(t, func() bool {
         len(priceService.GetTokenGasPrices()) == 0
     })

}```

2024-06-17 13:04 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +		tokenPricesUSD[cciptypes.Address(tokenPrice.TokenAddr)] = tokenPrice.TokenPrice.ToInt()
```go
	TokenPrice *assets.Wei
```
TokenPrice could be nil, seems like this `ToInt()` call might end up throwing segfault. Shouldn't we check nullability at this stage? It would make code more defensive

2024-06-17 13:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	for _, gasPrice := range gasPricesInDB {
I've checked implementation of `GetGasPricesByDestChain` and probably it's not that bad. IIUC with 100 source chains pointing to the dest chain you would fetch at most 100 records, but still if we always need a single record then why don't we fetch only a single record? :)

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +			jobId:                 jb.ID,
good call, refactored

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup.go
> +	cleanupInterval = priceExpireSec * time.Second
`priceExpiration` isn't impacted by product requirements, we really just need 1 latest row per gas/token price. It was set to 8hrs with me thinking it might help tracking price history while debugging, I'm realizing that logs are perfectly sufficient for that purpose, we can clean up more frequently.

Proposing to do every 10 minutes. On average every lane will insert 1 gas price and 2 fee token prices every minute, 10min -> 30 rows per lane.

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	err := c.updatePrices(c.backgroundCtx)
fixed

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +func (c *priceWrite) executeUpdate(ctx context.Context) error {
cleaned up

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	for _, gasPrice := range gasPricesInDB {
Good find, there's a followup PR that will make use of all source gas prices, it requires adding quite some logic for backwards-compatible observations so I want to make it a standalone PR

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		nil, // This is related to DynamicConfig, it is later set in NewReportingPlugin
simplified

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	ticker := time.NewTicker(c.updateInterval)
nice

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	if c.gasPriceEstimator == nil {
yup already checked, cleaned up

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_write.go
> +	c.dynamicConfigMu.Lock()
changed to rwmutex and RLock

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +		tokenPricesUSD[cciptypes.Address(tokenPrice.TokenAddr)] = tokenPrice.TokenPrice.ToInt()
They are currently not allowed to be nil, but good call, added nil price filter.

2024-06-18 04:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup_test.go
> +func Test_priceCleanupInBackground(t *testing.T) {
refactored the tests into `TestPriceService_priceWriteAndCleanupInBackground` and using real DB. It's difficult to decouple calls to other components, like PriceGetter, OffRampReader, PriceRegistry reader; overall I find the test really valuable as it demonstrates the service actually working E2E.

2024-06-18 04:31 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup.go
> +	eg.Go(func() error {
it's to stick with separation of token and prices; after the upcoming static price removal, mostly only fee token prices will remain, they require far less update/cleanup frequency; afterwards, token prices will be removed offchain, they will be read onchain via Keystone; since it doesn't hurt much to use 2 queries, it's cleaner to stick with the separation

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	gasPricesInDB, tokenPricesInDB, err := r.priceService.GetGasAndTokenPrices(ctx, r.destChainSelector)
you can remove `InDB` suffic, plugin shouldn't care where they come from.

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +type PriceService interface {
cciporm.GasPrice contains `assets.Wei` that's evm specific. We don't want the plugin to have chain specific info.

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +	GetGasAndTokenPrices(ctx context.Context, destChainSelector uint64) ([]cciporm.GasPrice, []cciporm.TokenPrice, error)
Method looks a bit odd.
```
getGasAndTokenPrices(destChain)
```

And returns `cciporm.GasPrice` that has a field `SourceChain`.

Maybe some comment explaining how this works.

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +func NewPriceService(
It would be nice if the constructor accepts `priceCleanupInterval` and `priceUpdateInterval` instead of having it hardcoded.

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +		if gasPrice.SourceChainSelector == r.sourceChainSelector && gasPrice.GasPrice != nil {
We fetch a lot of items and then we filter in-code. Can we make this part of the query?

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +			sourceGasPriceUSD = gasPrice.GasPrice.ToInt()
Would it be possible that the query returns multiple gas prices for the same chain and here we select an old one? Should we get the one where gasPrice.timestamp is the max?

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +			sourceGasPriceUSD = gasPrice.GasPrice.ToInt()
or if the service guarantees that it returns one gas price per chain add some validation and error

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +		return nil, nil, fmt.Errorf("missing gas price for sourceChainSelector %d", r.sourceChainSelector)
would it be possible that we get `missing gas price for sourceChainSelector` errors on plugin boot? i.e. the bg service didn't have time to write the price update in db

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +			tokenPricesUSD[cciptypes.Address(tokenPrice.TokenAddr)] = tokenPrice.TokenPrice.ToInt()
`ToInt()` might overflow since wei is `ubig.Big`. If that's not possible at least let's add a defensive check.

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		cleanupInterval: utils.WithJitter(priceCleanupInterval), // use WithJitter to avoid multiple services impacting DB at same time
Shouldn't we use proper db locks instead?

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		cleanupInterval: utils.WithJitter(priceCleanupInterval), // use WithJitter to avoid multiple services impacting DB at same time
not sure i understand what's the purpose of `WithJitter`. One node will use a value of `10s` another will have `9s` etc..  Is it important?

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		tokenPrices, err := p.orm.GetTokenPricesByDestChain(ctx, destChainSelector)
Should we bound this unbounded queries? i.e. add pagination or sth

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	gasPricesInDB, tokenPricesInDB, err := r.priceService.GetGasAndTokenPrices(ctx, r.destChainSelector)
non necessary newline at 188

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +			tokenPricesUSD[cciptypes.Address(tokenPrice.TokenAddr)] = tokenPrice.TokenPrice.ToInt()
Also it's a bit confusing. the value is the token price in usd, but the data type is wei.

2024-06-18 09:18 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	gasPricesInDB, tokenPricesInDB, err := r.priceService.GetGasAndTokenPrices(ctx, r.destChainSelector)
something else i noticed, not part of the pr:
```
for token, tokenPriceObservations := range tokenPriceObservations
```

let's use a different name :D

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	jobId int32
This is no longer needed I think

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	jobId int32
`priceGetter` was also moved to `priceService` and it's no longer needed to be a field in `CommitReportingPlugin`

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		gasPriceEstimator:       nil,
`nil` is default so you don't need to initialize that explicitly

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +	if p.gasPriceEstimator == nil || p.destPriceRegistryReader == nil {
This is already verified in `runUpdate`. You are already holding a lock, so this state won't change between previous check and this one

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +	sortedLaneTokens, filteredLaneTokens, err := ccipcommon.GetFilteredSortedLaneTokens(ctx, p.offRampReader, p.destPriceRegistryReader, p.priceGetter)
Minor, but it seems that `GetFilteredSortedLaneTokens` is used only by `price_service` so maybe we should move that from `ccipcommon` to the same package as `price_service`

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		return nil
@dimkouv should we close `priceGetter` when `Close()` is called on `priceService`? AFAIK `priceGetter` will be used only in `priceService` so when `priceService` is being closed then it should propagate that information down to `priceGetter` as well, right?

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +type priceService struct {
👏

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		cleanupInterval: utils.WithJitter(priceCleanupInterval), // use WithJitter to avoid multiple services impacting DB at same time
nit, but I would move `withJitter` call to the `run()` fun when ticker is initialized. Just for the sake of consistency, this is how it's done in other places

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup.go
> +	cleanupInterval = priceExpireSec * time.Second
> priceExpiration isn't impacted by product requirements, we really just need 1 latest row per gas/token price. It was set to 8hrs with me thinking it might help to track price history while debugging

I'm not against setting priceExpiration to 8 hours - if you need that for debugging then why not, doesn't sound like a huge impact. I'm trying to say that even if you set that to 8 hours cleanup should tick more frequently.

For instance, let's assume we produce 1 db row with prices every 1 second, priceExpiration is set to 8 hours

1. priceCleanupInterval is set to 8 hours - you need to remove 28k rows at once
2. priceCleanupInterval is set to 10 minutes - you need to remove 600 rows at once (but more frequently)

Does it make sense?

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_cleanup.go
> +	cleanupInterval = priceExpireSec * time.Second
That being said, if you set it like this

```go
	priceExpireSec       = 600
	priceCleanupInterval = priceExpireSec * time.Second
```

You will remove prices that are older than 10 minutes every 10 minutes, but I think these two should be decoupled, for instance something like this

```go
	priceExpireSec       = 8 * time.Hours
	priceCleanupInterval = 10 * time.Minutes
```

Then you will keep the prices for at least 8 hours, but cleanup will be run more frequently, therefore deleting rows in smaller chunks

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		// Do the first cleanup immediately upon starting the service, cleanup early to limit DB impact
Actually, it might create a higher pressure. When the node reboots all services will start immediately trying to remove data from the db. IMO you can drop that line and run the cleanup whenever the `cleanupTicker` ticks for the first time. WDYT?

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		p.lggr.Errorw("Error when updating prices after dynamic config update", "err", err)
You don't return `err` from here, is it intentional or accidental? I think you can inline err checking like this

```go
	if err := p.runUpdate(ctx); err != nil {
		p.lggr.Errorw("Error when updating prices after dynamic config update", "err", err)
		return err // ????
	}
	return nil
```

2024-06-18 09:20 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service_test.go
> +func TestPriceService_priceWriteAndCleanupInBackground(t *testing.T) {
:heart:

2024-06-18 09:22 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +func NewPriceService(
Yeah, I guess you can have to constructors, one accepting these values and another one (using previous one) with defaults

2024-06-18 09:23 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +			sourceGasPriceUSD = gasPrice.GasPrice.ToInt()
> Would it be possible that the query returns multiple gas prices for the same chain and here we select an old one? Should we get the one where gasPrice.timestamp is the max?

I think it should not happen, because of how the query is written. However, maybe a good test scenario to actually verify that on plugin/priceService component leve

2024-06-18 09:27 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		cleanupInterval: utils.WithJitter(priceCleanupInterval), // use WithJitter to avoid multiple services impacting DB at same time
Not node, but plugin. Imagine 400 lanes, it's 800 commit job specs (therefore 800 commit instances), all trying to remove data from a single table exactly in the same moment. `withJitter` is a nice tool to avoid these spikes and make those calls more distributed in time. Of course, the database will handle locking, but that's not a problem here, we don't care about that, we only want to smoothen the load and avoid spikes every 8 hours, when 800 routines want to write sth into database exactly in the same moment.

2024-06-18 09:28 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		tokenPrices, err := p.orm.GetTokenPricesByDestChain(ctx, destChainSelector)
I do believe that every query should be paginated, but I guess it could be addressed in a separate PR

2024-06-18 20:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	gasPricesInDB, tokenPricesInDB, err := r.priceService.GetGasAndTokenPrices(ctx, r.destChainSelector)
cleaned the above up

2024-06-18 20:29 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +type PriceService interface {
changed function interface to `GetGasAndTokenPrices(ctx context.Context, destChainSelector uint64) (map[uint64]*big.Int, map[cciptypes.Address]*big.Int, error)` to hide orm details

2024-06-18 20:36 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +	GetGasAndTokenPrices(ctx context.Context, destChainSelector uint64) ([]cciporm.GasPrice, []cciporm.TokenPrice, error)
added comments

2024-06-18 20:41 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +func NewPriceService(
played with the idea, currently there isn't a need for setting custom intervals other than in a single test, and it's nice to encapsulate knowledge of intervals in PriceService itself. Given there isn't a foreseeable need to make this configurable, let's keep this simple.

2024-06-18 22:14 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +		if gasPrice.SourceChainSelector == r.sourceChainSelector && gasPrice.GasPrice != nil {
added comments; leader lane will make use of all gas prices in a follow up PR, that'd require observability compatibility work, a bit too big in 1 PR

2024-06-18 22:19 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +			sourceGasPriceUSD = gasPrice.GasPrice.ToInt()
It's implemented at the ORM level, the call to get gas/token price for a chain always returns the latest price for that chain, it's tested there with real db, as far as application needs to be concerned, there is only 1 current price

2024-06-18 22:21 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +		return nil, nil, fmt.Errorf("missing gas price for sourceChainSelector %d", r.sourceChainSelector)
shouldn't be possible, `NewReportingPlugin` calls `UpdateDynamicConfig` which sets up the initial price

2024-06-18 22:26 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +			tokenPricesUSD[cciptypes.Address(tokenPrice.TokenAddr)] = tokenPrice.TokenPrice.ToInt()
moved this logic into `PriceService`; overflow should be possible right since Wei wraps `big.Int`, ToInt() just returns the underlying bigInt

afaik Wei is commonly used to wrap big.Int in Core for DB r/w since it readily implements scanner/value type

2024-06-18 22:31 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		tokenPrices, err := p.orm.GetTokenPricesByDestChain(ctx, destChainSelector)
this was actually briefly discussed, we will be removing most of token prices in the upcoming 2 weeks, going forward, token prices are gonna be limited to fee tokens + L/UL bps tokens, fee tokens are mostly just 2 per chain, and currently L/UL is only Eth; judging by speed to liquidity manager expansion, I doubt it'll ever be more than a few tokens before V2 rolls out and we ditch leader lane logic, so it's better to keep things simple and no pagination for now.

Same applies to gas prices, it is essentially capped by chain expansion speed, hard to imaging it going over 50 before v2

2024-06-18 22:35 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	jobId int32
cleane up

2024-06-18 22:38 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		gasPriceEstimator:       nil,
sol habits on always explicit assignment.. clean up

2024-06-18 22:41 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +	if p.gasPriceEstimator == nil || p.destPriceRegistryReader == nil {
yes but it feels better to add extra defence here in case `observePriceUpdates` is refactored in the future, like it was in this PR, this check results in an error as it should not happen, the check in `runUpdate` is info log as it can happen in happy path

2024-06-18 22:44 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +	sortedLaneTokens, filteredLaneTokens, err := ccipcommon.GetFilteredSortedLaneTokens(ctx, p.offRampReader, p.destPriceRegistryReader, p.priceGetter)
let's keep it in ccipcommon along with GetDestinationTokens =)

2024-06-18 22:52 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		return nil
hmm priceGetter isn't being closed before this PR; looking at code it shouldn't right, close on it calls the underlying pipeline runner, which is a singleton constructed during newApplication and shared across services

2024-06-18 22:54 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		cleanupInterval: utils.WithJitter(priceCleanupInterval), // use WithJitter to avoid multiple services impacting DB at same time
I had that initially, but it makes deterministic timing in tests more difficult, having it in constructor allows overriding of it later to make things deterministic if needed

2024-06-18 22:58 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		p.lggr.Errorw("Error when updating prices after dynamic config update", "err", err)
inlined; not returning error here is intentional, I don't think we want errors to bubble up to `NewReportingPlugin` when it can be transient, with the current setup, Commit services can still boot but cannot report prices if the error persists, this would be in-line with existing behavior

2024-06-18 23:21 UTC, matYang commented on core/services/ocr2/plugins/ccip/internal/ccipdb/price_service.go
> +		// Do the first cleanup immediately upon starting the service, cleanup early to limit DB impact
removed

2024-06-19 07:27 UTC, dimkouv approved these changes

2024-06-19 09:55 UTC, mateusz-sekara approved these changes

2024-06-19 11:57 UTC, merged