multi ramps
smartcontractkit/ccip pull request #1034
Opened 2024-06-17 14:51 UTC by dimkouv

(draft)

tl;dr
1) Msg ID is computed on source and only used for logging purposes
2) Msg Hash is computed on destination chain
3) Merkle tree uses msg hash for leaves

2024-06-19 07:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/mocks/messagehasher.go
> +	return b32, nil
Not sure if we can assume that the message hash will always be Bytes32. Some chains may have shorter / longer hashes. `[]byte` is probably safest?

2024-06-19 07:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +			lggr.Errorw("critical error hash counts should never be empty", "seqNum", seqNum)
```suggestion
			lggr.Criticalw("hash counts should never be empty", "seqNum", seqNum)
```

2024-06-19 07:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/mocks/messagehasher.go
> +	return b32, nil
Maybe can do in an upcoming PR

2024-06-19 07:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +		if msg.MsgHash.String() == emptyHash {
I think equality should be a method on the `Bytes32` object (or if we make msg ids plain `[]byte`, and create a `MsgID` type, a method on that object, or a free function `MsgIDEquals` though this is less common)

2024-06-19 07:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +		if msg.MsgHash.String() == emptyHash {
This avoids stringification issues of bytes i.e hex vs base64 etc.

2024-06-19 07:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +		sort.Slice(hashesSlice, func(i, j int) bool { return hashesSlice[i] < hashesSlice[j] })
I wonder if we really want this or if we just want consensus failure in this case? If the committee is split, we want the "honest" nodes to be able to stall long enough for the dishonest nodes to be kicked out?

2024-06-19 12:35 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/mocks/messagehasher.go
> +	return b32, nil
yeah, let's sync with research and do as a followup

2024-06-19 12:41 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +		if msg.MsgHash.String() == emptyHash {
yes

2024-06-19 12:51 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +		sort.Slice(hashesSlice, func(i, j int) bool { return hashesSlice[i] < hashesSlice[j] })
Doesn't really matter because if they are 50/50 then
Msg will be dropped a few lines below (assuming that 50% is less than 2fchain+1 ofcourse):

But determinism is nice to have, at least for testing and debugging. Sorting is not a big performance or complexity issue IMO.

```
if count >= 2*fChain+1 {
   msgSeqNumsQuorum.Add(seqNum)
}
```

2024-06-25 08:51 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +	// For each sequence number consider correct the Hash with the most votes.
Is that what you meant here?
```suggestion
	// For each sequence number consider the Hash with the most votes.
```

2024-06-25 09:33 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +	// For each sequence number consider correct the Hash with the most votes.
I guess it's the same thing. Updating to what you recommend.

2024-06-25 09:46 UTC, asoliman92 requested changes
I think it's a good time to simplify tests with some helpers as it's bloating and hard to read. @winder has similar concerns as well.

2024-06-25 09:55 UTC, asoliman92 approved these changes

2024-06-25 09:55 UTC, asoliman92 approved these changes

2024-06-25 10:26 UTC, makramkd commented on core/services/ocr3/plugins/ccip/spec/commit_plugin.py
> +    message_hash: bytes
A clarifying comment here on the difference b/w message_id and message_hash maybe

2024-06-25 10:26 UTC, makramkd commented on core/services/ocr3/plugins/ccip/spec/commit_plugin.py
> +        msg_ids = msg_hashes = set()
To be absolutely clear you don't want `msg_ids` and `msg_hashes` to refer to the same `set()` right? Cuz this is what this line is saying.

I'd separate this to two separate lines

```python
msg_ids = set()
msg_hashes = set()
```

2024-06-25 10:26 UTC, makramkd commented on core/services/ocr3/plugins/ccip/spec/commit_plugin.py
> +                msg_ids.add(msg.message_hash)
```suggestion
                msg_hashes.add(msg.message_hash)
```

2024-06-25 10:48 UTC, makramkd approved these changes

2024-06-25 11:47 UTC, merged