Uses Better Simulated Funding Approach
smartcontractkit/ccip pull request #1064
Opened 2024-06-20 16:15 UTC by kalverra

2024-06-20 16:17 UTC, AnieeG commented on integration-tests/load/go.mod
> +	github.com/smartcontractkit/chainlink-testing-framework v1.31.3
how about the go.sum for this

2024-06-20 16:25 UTC, kalverra commented on integration-tests/load/go.mod
> +	github.com/smartcontractkit/chainlink-testing-framework v1.31.3
go mod tidy was weird and missed this, fixed

2024-06-20 17:44 UTC, AnieeG approved these changes

2024-06-20 18:34 UTC, AnieeG requested changes

2024-06-20 18:34 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/test_env.go
> +		for _, networkCfg := range networks.MustGetSelectedNetworkConfig(testInputs.EnvInput.Network) {
This looks like it will add all keys from the slice of available networks to a single network from `testInputs.EnvInput.PrivateEthereumNetworks `slice

2024-06-21 07:13 UTC, Tofel commented on integration-tests/ccip-tests/testsetups/test_env.go
> +		for _, networkCfg := range networks.MustGetSelectedNetworkConfig(testInputs.EnvInput.Network) {
and that's what we want, no? we could just check if network is simulated, but even if it's not, I don't think there's any harm done

2024-07-01 17:36 UTC, closed without merging