ccip-2583 readme for ccip test config
smartcontractkit/ccip pull request #1070
Opened 2024-06-22 02:52 UTC by AnieeG

## Motivation

## Solution

2024-06-24 15:44 UTC, b-gopalswami reviewed
I have highlighted some of the broken links in my first pass. Will review further.

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/README.md
> +3. Secrets - You also need to set some secrets. This is a mandatory step needed to run the tests. Please refer to [sample-secrets.toml](testconfig/examples/sample-secrets.toml) for the list of secret
The filename is wrong here.
```suggestion
3. Secrets - You also need to set some secrets. This is a mandatory step needed to run the tests. Please refer to [sample-secrets.toml](testconfig/examples/secrets.toml.example) for the list of secrets that are mandatory to run the tests.
```

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/README.md
> +We recommend against changing the content of [sample-secrets.toml](testconfig/examples/sample-secrets.toml). Please create a new file and set it as the secrets file.
Same suggesstion as above. Please fix the filename.

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +- The test reads the default configuration from [ccip-default.toml](/integration-tests/ccip-tests/testconfig/tomls/ccip-default.toml).
```suggestion
- The test reads the default configuration from [ccip-default.toml](./tomls/ccip-default.toml). 
```

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +  - Example override file - [override.toml.example](/integration-tests/ccip-tests/testconfig/examples/override.toml.example)
```suggestion
  - Example override file - [override.toml.example](./examples/override.toml.example)
```

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +  - Example secret file - [secrets.toml.example](/integration-tests/ccip-tests/testconfig/examples/secrets.toml.example)
```suggestion
  - Example secret file - [secrets.toml.example](./examples/secrets.toml.example)
```

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +   * refer to the example - [network_config.toml.example](/integration-tests/ccip-tests/testconfig/examples/network_config.toml.example)
```suggestion
   * refer to the example - [network_config.toml.example](./examples/network_config.toml.example)
```

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +Refer to [secrets.toml.example](/integration-tests/ccip-tests/testconfig/examples/secrets.toml.example) for details.
```suggestion
Refer to [secrets.toml.example](./examples/secrets.toml.example) for details.
```

2024-06-24 15:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/examples/secrets.toml.example
> +dashboard_url="/d/6vjVx-1V8/ccip-long-running-tests"
Is this ok to refer here?

2024-06-24 16:05 UTC, kalverra requested changes

2024-06-24 16:05 UTC, kalverra commented on integration-tests/ccip-tests/testconfig/examples/network_config.toml.example
> +AVALANCHE_MAINNET = [
This might be a bit overkill. You can probably cut this down to 
```toml
[RpcHttpUrls]
ETHEREUM_MAINNET = [
    'https:....',
    'https:......',
]
OTHER_MAINNET = [
    'https:....',
    'https:......',
]

2024-06-24 16:05 UTC, kalverra commented on integration-tests/ccip-tests/testconfig/examples/override.toml.example
> +{
Is it hard to change this to TOML format while we're at it?

2024-06-24 16:05 UTC, kalverra commented on integration-tests/ccip-tests/testconfig/README.md
> +The configuration is specified in a TOML file. The configuration is used to specify the test environment, test type, test parameters, and other necessary details for running the tests.
```suggestion
The configuration is a TOML file that specifies the test environment, test type, test parameters, and other necessary details for running the tests.
```

2024-06-24 16:05 UTC, kalverra commented on integration-tests/ccip-tests/testconfig/README.md
> +- If there are sensitive details like private keys, credentials in test config, they can be specified in a separate secret file.
Why do we separate the secrets and overrides file? In the core testconfig there is only the defaults and the overrides. Is there a reason CCIP specifically wants the third option?

2024-06-24 20:49 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +### CCIP.Groups.<testtype>.KeepEnvAlive
The `<testtype>` is not rendering properly. This change needs to be applied to all instances.
https://github.com/smartcontractkit/ccip/blob/1349876b58d5ca62c0654932fd3e424f069b0289/integration-tests/ccip-tests/testconfig/README.md#ccipgroupskeepenvalive
```suggestion
### CCIP.Groups.<test_type>.KeepEnvAlive
```

2024-06-24 20:49 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +If a request is triggered within this duration, the test will skip sending another request during load run. For Example, if `SkipRequestIfAnotherRequestTriggeredWithin` is set to `40m`, and a request
Just to be clear.
```suggestion
If a request is triggered within this duration, the test will skip sending another request during load run. For Example, if `SkipRequestIfAnotherRequestTriggeredWithin` is set to `40m`, and a request is triggered at 0th second, the test will skip sending another request for another 40m.
```

2024-06-24 20:49 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/README.md
> +dashboard_url = "/d/6vjVx-1V8/ccip-long-running-tests"
Is this ok to refer here?

2024-06-25 21:21 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/README.md
> +- If there are sensitive details like private keys, credentials in test config, they can be specified in a separate secret file.
Yes. we want to set the live network details in a separate network config. so that it can be loaded as a static value from github/1 pass secrets. The rest of the configs get generated dynamically with [action](https://github.com/smartcontractkit/ccip/blob/ccip-develop/.github/actions/setup-create-base64-config-ccip/action.yml ). This is a core feature imported from [CTF](https://github.com/smartcontractkit/chainlink-testing-framework/blob/main/config/network.go#L17)

2024-06-25 21:24 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/examples/override.toml.example
> +{
Probably a diff PR. But one reason could be - it's easier to read nested struct with json. But can be changed

2024-06-25 21:24 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/examples/secrets.toml.example
> +dashboard_url="/d/6vjVx-1V8/ccip-long-running-tests"
yes

2024-06-25 21:43 UTC, AnieeG commented
New PR created https://github.com/smartcontractkit/ccip/pull/1092

2024-06-25 21:43 UTC, closed without merging