Fix/ccip 2466 homechain config sync
smartcontractkit/ccip pull request #1077
Opened 2024-06-24 17:16 UTC by asoliman92

Fix some of previous PR commit as it was merged with auto-merge before addressing all of them.

2024-06-24 18:15 UTC, 0xnogo approved these changes

2024-06-24 18:15 UTC, 0xnogo approved these changes

2024-06-24 22:35 UTC, winder requested changes
I think the polling test is still wrong

2024-06-24 22:35 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +	time.Sleep(2 * time.Second)
Sorry, but if I'm reading the code correctly this still doesn't test the polling logic. You need to assert that `homeChainReader` is called twice. Once when `Start` is called, and once when `poll` is called.

When you call `Close()` the stop channel prevents poll from fetching a result so you never hit that block of code.

I haven't used StopChan before so I wrote this test to verify the expected behavior:
```
func TestStopChan(t *testing.T) {
	ch := make(StopChan)
	ctx, _ := ch.NewCtx()
	go func() {
		time.Sleep(1 * time.Second) // 1 second timeout
		close(ch)
	}()

	ticker := time.NewTicker(400 * time.Millisecond) // 2 ticks before the stop chan is triggered
	for {
		select {
		case <-ctx.Done():
			fmt.Println("We're done here.")
			return
		case <-ticker.C:
			fmt.Println("Ticking here.")
		}
	}
}
```

2024-06-24 22:35 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +	time.Sleep(2 * time.Second)
StopChan also seems totally unnecessary:
```
func TestStopChan(t *testing.T) {
	stopCh := make(chan struct{})
	go func() {
		time.Sleep(1 * time.Second)
		close(stopCh)
	}()

	ticker := time.NewTicker(500 * time.Millisecond)
	for {
		select {
		case <-stopCh:
			fmt.Println("We're done here.")
			return
		case <-ticker.C:
			fmt.Println("Ticking here.")
		}
	}
}
```

2024-06-25 07:45 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +	time.Sleep(2 * time.Second)
Got you, I used the stop channel as it's used in some other polling services we have in our repos. I fixed the test to check for the number of calls now and it's working correctly. Thanks!

2024-06-25 09:53 UTC, dimkouv approved these changes

2024-06-25 11:41 UTC, winder approved these changes

2024-06-25 14:23 UTC, merged