Feature/ccip 1250 commitstore
smartcontractkit/ccip pull request #1080
Opened 2024-06-24 21:03 UTC by patrickhuie19

## Motivation
Continues the work done in feature/ccip-1250 and adds a provider based implementation of a CommitStore

## Solution

2024-07-02 15:59 UTC, makramkd requested changes, later dismissed
Think there's some issues, lmk if these don't make sense

2024-07-02 15:59 UTC, makramkd commented on core/services/chainlink/relayer_factory.go
> +	"github.com/naoina/toml"
Why a new toml dep?

2024-07-02 15:59 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_2_0/commit_store.go
> +	}
Don't think this code will run if `c.estimator == nil` since the same condition is checked above. Also, why the explicit unlock, since that's already deferred?

2024-07-02 15:59 UTC, makramkd commented on core/services/ocr2/plugins/ccip/exportinternal.go
> +type JSONCommitOffchainConfig = v1_2_0.JSONCommitOffchainConfig
Exporting a specific version like this seems not right, do we want to maybe suffix this with the version to make it clear that this is for 1.2?

2024-07-02 15:59 UTC, makramkd commented on core/services/ocr2/plugins/ccip/proxycommitstore.go
> +	dstCommitStoreReader cciptypes.CommitStoreReader
To make it crystal clear what each reader should implement, can we use narrower interfaces here instead of the full CommitStoreReader interface?

Implementations of CommitStoreReader would be implementing a superset of these narrower interfaces. But the narrower interface makes it very clear what you can do on each chain.

2024-07-02 15:59 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +func (i IncompleteSourceCommitStoreReader) ChangeConfig(ctx context.Context, onchainConfig []byte, offchainConfig []byte) (cciptypes.Address, error) {
Shouldn't this be a pointer receiver for the `i.gasPriceEstimator` updates to work?

2024-07-02 16:08 UTC, patrickhuie19 commented on core/services/chainlink/relayer_factory.go
> +	"github.com/naoina/toml"
weird goland behavior. fixed in next revision

2024-07-02 16:08 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_2_0/commit_store.go
> +	}
these shouldn't be here - borked from a merge. This chunk is removed in the next revision

2024-07-03 06:04 UTC, makramkd commented on core/services/ocr2/plugins/ccip/proxycommitstore.go
> +	}
Use `multierr` to aggregate errors from multiple calls

2024-07-03 06:04 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +}
Can delete these

2024-07-03 06:04 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +}
Delete

2024-07-03 06:04 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +}
Delete

2024-07-03 06:04 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +}
🪓

2024-07-03 06:04 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +}
🪓

2024-07-03 06:04 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +}
✂️

2024-07-03 06:04 UTC, makramkd commented on core/services/relay/evm/ccip.go
> +}
⚔️

2024-07-03 14:56 UTC, patrickhuie19 commented on core/services/relay/evm/ccip.go
> +}
Since it goes over the wire, it needs to satisfy the full `CommitStoreReader` iface, so these error only methods will have to remain :(

2024-07-03 17:14 UTC, krehermann approved these changes

2024-07-08 14:37 UTC, dimkouv approved these changes

2024-07-08 14:37 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	srcCommitStore, err := srcProvider.NewCommitStoreReader(ctx, ccipcalc.EvmAddrToGeneric(commitStoreAddress))
that will cause confusion, worths at least adding a comment explaining
> there's no commit store contract on source but...

2024-07-08 14:37 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	commitStoreReader = ccip.NewProviderProxyCommitStoreReader(srcCommitStore, dstCommitStore)
why not initialize directly? (remove line 66)

2024-07-08 14:37 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/proxycommitstore.go
> +type IncompleteSourceCommitStoreReader interface {
I feel `Incomplete` prefix is not required.
Just `Source/DestCommitStoreReader` each one having a complete set of supported methods

2024-07-08 14:56 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	commitStoreReader = ccip.NewProviderProxyCommitStoreReader(srcCommitStore, dstCommitStore)
NewProviderProxyCommitStoreReader returns a `*ProviderProxyCommitStoreReader`, which if not cast into a CommitStoreReader would not play nicely with our consistent approach to wrap our readers with the observability wrapped structs. 

```
Cannot use 'observability.NewObservedCommitStoreReader(commitStoreReader, destChainID, ccip.CommitPluginLabel)' (type *ObservedCommitStoreReader) as the type *ProviderProxyCommitStoreReader
```

2024-07-08 14:58 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	srcCommitStore, err := srcProvider.NewCommitStoreReader(ctx, ccipcalc.EvmAddrToGeneric(commitStoreAddress))
I'll add here: https://github.com/smartcontractkit/ccip/pull/1150

2024-07-08 15:44 UTC, merged