CCIP-2645: Introducing leader lane and setting PriceReportingDisabled
smartcontractkit/ccip pull request #1120
Opened 2024-06-28 21:49 UTC by b-gopalswami

## Motivation

## Solution

2024-07-08 19:12 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/global.go
> +	Lane                    *Lane                                       `toml:",omitempty"`
If this is a new common going forward , it's better to derive it from contract version. Something like we do for Token Admin Registry

2024-07-08 19:12 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	}
Please put it under it's own function

2024-07-08 19:12 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/tomls/leader-lane.toml
> +NoOfNetworks = 3
Please change this to 4. It will be easier to capture edge scenarios

2024-07-08 19:12 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +		// by this we will make sure all required leader lanes will be defined.
I think this is better to do it w.r.t destination chain id. network name will be different for same chain ids in case there are multiple routers. for example if you deploy 2 routers in one chain, the network name will be like A-1 and A-2.
It's better to keep a map with destination chain id tracking, and check whether it's covered

2024-07-08 19:12 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	GasUpdateEvents           []gasUpdateEvent
why another element? can we not increase the scope of gasUpdateWatcher?

2024-07-08 19:43 UTC, b-gopalswami commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	GasUpdateEvents           []gasUpdateEvent
Having another element is better in this case to avoid struct filtering inside the `WaitForPriceUpdates`. As these new elements are only needed post `WaitforPriceUpdates` check.

2024-07-09 14:39 UTC, b-gopalswami commented on integration-tests/ccip-tests/testsetups/ccip.go
> +		// by this we will make sure all required leader lanes will be defined.
I created the map of destination network name with value as list of source network name and defined the leader lane from that. I still went with network name as the chain ID remains same if there are more than one router. Each router has its own price registry.

2024-07-09 19:32 UTC, kalverra requested changes

2024-07-09 19:32 UTC, kalverra commented on integration-tests/ccip-tests/testsetups/ccip.go
> +		lanes := lanes
Necessary?

2024-07-09 19:32 UTC, kalverra commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	// Once map is available, picking every first source network name from the list to form the leader lanes
Why bother building a list if you only ever use the first element?

2024-07-09 19:32 UTC, kalverra commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	log.Debug().Interface("Gas update transactions", transactions).Msg("List of transaction hash:")
```suggestion
	log.Debug().Interface("Tx Hashes", transactions).Msg("Checked Gas Update Transactions")
```

2024-07-09 19:32 UTC, kalverra commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	LeaderLanes         []LeaderLane
I think this is more consistently placed in the `TestGroupInput`?

2024-07-09 19:32 UTC, kalverra commented on integration-tests/ccip-tests/testsetups/ccip.go
> +		lggr.Info().
```suggestion
		lggr.Debug().
```

2024-07-09 20:35 UTC, b-gopalswami commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	LeaderLanes         []LeaderLane
I think it is better to place it under TestSetups as it will common feature irrespective of TestGroup.

2024-07-09 20:43 UTC, b-gopalswami commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	// Once map is available, picking every first source network name from the list to form the leader lanes
Ah, you are right!

2024-07-10 15:10 UTC, kalverra approved these changes

2024-07-31 18:57 UTC, anirudhwarrier approved these changes

2024-07-31 19:02 UTC, anirudhwarrier requested changes
```
❌PANIC❌ TestSmokeCCIPForBidirectionalLane (0.00s) 
  ---❌ Error Found ❌---
  panic: test timed out after 30m0s 
```
Seems leader lane smoke test is failing  [here](https://github.com/smartcontractkit/ccip/actions/runs/10184185275/job/28171238699?pr=1120#step:12:787)

2024-08-01 14:29 UTC, anirudhwarrier approved these changes

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +type GasUpdateEvent struct {
nit: better to move it under contracts/contract_models.go

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/tomls/leader-lane.toml
> +NoOfRoutersPerPair = 2
nice!!

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	LeaderLanes         []LeaderLane
Not for this PR, for future  - There are actually a lot of common set up in `TestGroupInput` which we can extract to common.

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	// Once map is available, picking every first source network name from the list to form the leader lanes
please update the comment based on the change you made

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +			Msg("Non-leader lane")
This will increase unnecessary logs. How about changing it to debug?

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +			ccipLaneB2A.PriceReportingDisabled = true
```suggestion
			ccipLaneB2A.PriceReportingDisabled = len(o.Cfg.LeaderLanes) > 0 &&
			!o.Cfg.isLeaderLane(ccipLaneB2A.SourceNetworkName, ccipLaneB2A.DestNetworkName)
```

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +			ccipLaneB2A.PriceReportingDisabled = true
Or you can just update `isLeaderLane` to `isPriceReportingDisabled`

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +		Int("Tx hashes", len(transactionsBySource)).
please change the key accordingly. For successful cases, this logging might be unnecessary

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +				transactions[g.Tx] = v
is it needed? are you not writing the same value you just read?

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +			return err
Please merge the lane with error message, ow it's going to be difficult to debug

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +				transactions[g.Tx] = map[uint64]actions.GasUpdateEvent{
nit - This operation is not thread safe.

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	lggr.Info().Interface("Tx hashes by source", transactionsBySource).Msg("Checked Gas Update Transactions by Source")
would prefer debug log here

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	for key, transactionDetails := range transactions {
Is `transactions` used anywhere else ? can we not save `transactionsBySource` directly in `filterGasUpdateByTx`?

2024-08-02 22:56 UTC, AnieeG commented on integration-tests/ccip-tests/testsetups/ccip.go
> +		}); err == nil && !pointer.GetBool(setUpArgs.Cfg.TestGroupInput.ExistingDeployment) {
This logic is duplicated in a lot of places, might be better to put it into a function something like `IsLeaderLaneFeatureEnabled`

2024-08-05 18:33 UTC, b-gopalswami commented on integration-tests/ccip-tests/testsetups/ccip.go
> +				transactions[g.Tx] = v
Removed it as I'm not storing event details anymore.

2024-08-05 18:33 UTC, b-gopalswami commented on integration-tests/ccip-tests/testsetups/ccip.go
> +	for key, transactionDetails := range transactions {
Fixed

2024-08-05 18:57 UTC, AnieeG approved these changes

2024-08-05 19:30 UTC, merged