Ccip-2578 - Enable slow and fast chain
smartcontractkit/ccip pull request #1122
Opened 2024-06-30 22:11 UTC by AnieeG

## Motivation
Memory consumption issues when log finalization takes long
Enabling slow and fast chain to execute in single chain

## Solution

1. Stop storing successful Tx and CCIPSendReq Phase data in request status if the phases are successful. This will not create unnecessary phase status in memory when SendRequested Log finalization takes time to complete.

2. To enable fast and slow chain, provide the network details for fast and slow chain in test config. If you want to run all but 3 chains as fast network, you need to provide fast network details in 1st index of test config's `selected_network` and rest of the network as slow config, so that when you provide `NoOfNetworks` to be greater than provided network number in `selected_network`, the test can then replicate 1st network config( except chain id) to create rest of the networks ( `NoOfNetworks- len(selected_network)`. 
For example -
If you want to run with 3 slow chains and 5 fast chains, provide network details in this order -
```
selected_network - [fast chain, slow chain, slow chain, slow chain]
NoOfNetworks - 8

```
In this way the test will find config for 4 networks and the rest 4 network will be created by replicating 1st network.

2024-07-03 19:50 UTC, kalverra requested changes

2024-07-03 19:50 UTC, kalverra commented on integration-tests/ccip-tests/testreporters/ccip.go
> +	sendTransactionStats *TransactionStats,
Nit: I find naming the argument as optional can help clarify things in cases like this.
```suggestion
	optionalSendTransactionStats *TransactionStats,
```

2024-07-03 19:50 UTC, kalverra commented on integration-tests/ccip-tests/load/ccip_multicall_loadgen.go
> +			stat.UpdateState(&lggr, 0, testreporters.TX, startTime.Sub(txConfirmationTime), testreporters.Success, nil)
Why remove the stats here? Are they no longer important in this context?

2024-07-03 19:50 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +						reqStat[i].UpdateState(lggr, seqNum, testreporters.CCIPSendRe, 0, testreporters.Success, nil)
Is the stat no longer useful here? Or never was?

2024-07-03 20:40 UTC, AnieeG commented on integration-tests/ccip-tests/load/ccip_multicall_loadgen.go
> +			stat.UpdateState(&lggr, 0, testreporters.TX, startTime.Sub(txConfirmationTime), testreporters.Success, nil)
I am storing this stats in  [SourceLogFinalized step](https://github.com/smartcontractkit/ccip/pull/1122/files#diff-1a4a2100a0ce78a434159b73c483a46fa61c0e705a299173b570af603dac8de7R355-R362)
This is to avoid unnecessary streaming to loki and hoarding data in memory. Otherwise if there is significant load and the msg takes 30-40 min in getting finalized, the memory usage increases due to storing this stats in TX, and CCIPSendReq step. If request fails in  TX, and CCIPSendReq step we store the stats, but if it passes these two steps, we just store the relevant data in SourceLogFinalized step to avoid duplication

2024-07-03 21:05 UTC, AnieeG commented on integration-tests/ccip-tests/load/ccip_loadgen.go
> -	ctx, cancel := context.WithTimeout(context.Background(), sourceCCIP.Common.ChainClient.GetNetworkConfig().Timeout.Duration)
Removed all of this as we are not capturing how long does it take to confirm a tx. This is a generic chain behavior and can be omitted from validating CCIP specific outcomes.

2024-07-03 22:03 UTC, kalverra approved these changes

2024-07-04 01:08 UTC, b-gopalswami approved these changes
LGTM!

2024-07-04 01:11 UTC, merged