SHIP-2006 Consolidate All FinalityDepth Settings to default TOML files
smartcontractkit/ccip pull request #1151
Opened 2024-07-08 01:13 UTC by adityavadhavkar1215

## Motivation
[Ticket](https://smartcontract-it.atlassian.net/browse/SHIP-2006)

## Solution
Removed FinalityDepth setting from chains where FinalityTag is enabled and updated the values of FinalityDepth setting to make it the same as the values set in infra-k8s repo.

2024-07-08 13:29 UTC, dhaidashenko commented on core/chains/evm/config/toml/defaults/Kroma_Mainnet.toml
> -FinalityDepth = 400
Multiple components still (TXM or HeadTracker with `FinalityTagBypass=true`) use `FinalityDepth` even if `FinalityTagEnabled=true`. We should not remove it.

2024-07-09 11:52 UTC, simsonraj commented on docs/CONFIG.md
> +FinalityDepth = 50
Kroma changed from 400 to 50? I think its about 700, no?

2024-07-09 11:54 UTC, simsonraj commented on docs/CONFIG.md
> +FinalityDepth = 50
Metis finality should be an Average of 2.6 hours, as per our last research, can we please translate that depth & use that value?

2024-07-09 11:58 UTC, simsonraj requested changes

2024-07-09 11:58 UTC, simsonraj commented on docs/CONFIG.md
> +FinalityDepth = 2400
I think it should be 200 for the testnet to correspond to 20 minutes finality, @stackman27 please weigh in
if  increasing the finality anywhere in the config we should also increase the HistoryDepth I believe

2024-07-09 11:58 UTC, simsonraj commented on docs/CONFIG.md
> +FinalityDepth = 200
where did we get this value from?

2024-07-09 12:03 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Kroma_Mainnet.toml
> -FinalityDepth = 400
@dhaidashenko : Applicable for CCIP too? not sure if all the chains have the right depth & I dont think we had any issues so far due to that

2024-07-09 13:12 UTC, adityavadhavkar1215 commented on docs/CONFIG.md
> +FinalityDepth = 50
@simsonraj the CONFIG.md was updated by running the command 'make config-docs'. What I'm assuming happened here is that since I removed the FinalityDepth value from the specific config file the code running behind 'make config-docs' used the FinalityDepth value from some default config file. However, I'm not sure which default file is it reading from.

2024-07-09 17:33 UTC, dhaidashenko commented on core/chains/evm/config/toml/defaults/Kroma_Mainnet.toml
> -FinalityDepth = 400
Yes, `FinalityTagBypass=true` is set by default in CL Node (so applied to CCIP too), which means that HeadTracker fallback to the finality depth.

2024-07-10 13:52 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Celo_Mainnet.toml
> -FinalityDepth = 10
Lets keep it back on

2024-07-10 13:53 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Kroma_Mainnet.toml
> -FinalityDepth = 400
Lets keep it back & change it to 700

2024-07-10 15:05 UTC, adityavadhavkar1215 commented on core/chains/evm/config/toml/defaults/Celo_Mainnet.toml
> -FinalityDepth = 10
Done

2024-07-10 15:05 UTC, adityavadhavkar1215 commented on core/chains/evm/config/toml/defaults/Kroma_Mainnet.toml
> -FinalityDepth = 400
Done

2024-07-10 15:19 UTC, adityavadhavkar1215 commented on docs/CONFIG.md
> +FinalityDepth = 2400
Done

2024-07-10 15:24 UTC, adityavadhavkar1215 commented on docs/CONFIG.md
> +FinalityDepth = 200
This was in infra-k8s repo.

2024-07-10 20:15 UTC, adityavadhavkar1215 commented on core/chains/evm/config/toml/defaults/Metis_Mainnet.toml
> +FinalityDepth = 312
2.6 hours is the time to finality and block rate varies between 30 sec - 2 min. So, FinalityDepth = 2.6 * 60 * 60 / 30. Considering 30 sec as block rate to estimate the max value for Finality Depth.

2024-07-10 20:16 UTC, adityavadhavkar1215 commented on core/chains/evm/config/toml/defaults/Mantle_Sepolia.toml
> +FinalityTagEnabled = true
@stackman27 mentioned that Mantle is finalitytag enabled. Did not find Mantle's exact FinalityDepth but infra-k8s had 200 so keeping 200 and adding FinalityTagEnabled = true.

2024-07-10 20:17 UTC, adityavadhavkar1215 commented on docs/CONFIG.md
> +FinalityDepth = 50
Done

2024-07-11 13:28 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Metis_Mainnet.toml
> +FinalityDepth = 312
Lets increase this to 500 for some buffer, But for testnet we have seen upto 3000 blocks

2024-07-11 13:29 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Mantle_Sepolia.toml
> +FinalityTagEnabled = true
For mantle it was discussed that the avg finality time is 75 minutes that is ~ 500 blocks in testnet & ~9000 blocks in mainnet.

2024-07-11 13:30 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
sorry, this can go upto 300 blocks for testnet

2024-07-11 13:39 UTC, adityavadhavkar1215 commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
Updated.

2024-07-11 13:39 UTC, adityavadhavkar1215 commented on core/chains/evm/config/toml/defaults/Mantle_Sepolia.toml
> +FinalityTagEnabled = true
Updated.

2024-07-11 13:39 UTC, adityavadhavkar1215 commented on core/chains/evm/config/toml/defaults/Metis_Mainnet.toml
> +FinalityDepth = 312
Updated.

2024-07-17 13:58 UTC, simsonraj approved these changes
Approved with request to @stackman27 to verify some values

2024-09-25 19:46 UTC, Madalosso commented
I am reopening this to carry on with the work.

2024-09-25 19:47 UTC, Madalosso commented
@stackman27 Can you please review the updated values here?

2024-09-27 19:37 UTC, Madalosso commented
NOTE: Check if these values should be copied to the [chainlink core ccip-specific config dir](https://github.com/smartcontractkit/chainlink/tree/develop/ccip/config).
ping @simsonraj

2024-09-30 12:44 UTC, Madalosso commented
NOTE: we should apply these values to the new CL core repo, which now has some [overrides for ccip](https://github.com/smartcontractkit/chainlink/tree/develop/ccip/config) (part of the effort to bring CCIP back to core repo)

2024-09-30 13:59 UTC, Madalosso commented
@simsonraj @stackman27 
While chatting with @friedemannf about these new configs, he noticed that the[ document](https://docs.google.com/document/d/1yUyuSb-nuN6lc-yP1rXsqmga6_r_MTZMJltAbUKo1LY/edit) created by Aditya used some alpha and beta infra-k8s cluster configs as the source of truth... And raised concerns about this.

What do you guys think? @friedemannf suggested that we should only rely on custom settings from:
> For CCIP, the sources should be:
testnet: prod-testnet cluster
mainnet: NOP setup guide

2024-09-30 16:09 UTC, Madalosso commented
Closing this to prevent reviews.
I'll review CCIP values based on the correct source of truth, make necessary changes and re-open it

2024-09-30 16:55 UTC, Madalosso commented
Opening with update values for testnet, relying only on prod-testnet infra-k8s overrides

2024-09-30 17:03 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/Mantle_Sepolia.toml
> +FinalityTagEnabled = true
@simsonraj , we have 1200 finalityDepth override on infra-k8s for this testnet. Will use this value here. let me know if you're rather keep 500

2024-09-30 17:04 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
[200 on infra-k8s](https://github.com/smartcontractkit/infra-k8s/blob/a7e46c641e13a3ae32b62f598f7c49dc913bd0ad/projects/chainlink/files/chainlink-clusters/cl-ccip-testnets-prod/config.yaml#L666). 200 or 300 @simsonraj

2024-09-30 18:49 UTC, Madalosso commented
The latest commit added the main net values set by [CCIP Node Setup Guide](https://smartcontract-it.atlassian.net/wiki/spaces/CCIP/pages/609257802/CCIP+Node+Setup+Guide+Internally+Shared)

2024-10-01 10:24 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Linea_Sepolia.toml
> +FinalityDepth = 200
why 200 on Sepolia but 600 on Mainnet?

2024-10-01 10:25 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Mantle_Sepolia.toml
> +FinalityDepth = 1200
Can we please verify if this is still the case?
also cc @ma33r

2024-10-01 10:26 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Metis_Rinkeby.toml
> +FinalityDepth = 3000
Also Rinkeby may not be operational, can we delete this one?

2024-10-01 10:26 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Metis_Mainnet.toml
> +FinalityDepth = 500
Also difference between mainnet & sepolia

2024-10-01 10:27 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/zkSync_Goerli.toml
> +FinalityDepth = 300
I think we should also delete the goerli here?

2024-10-01 10:27 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
isnt it 1200?

2024-10-01 10:34 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
Unless the block timing is different between mainnet & testnet, can you please also give a pass on all the mainnet configs ?

2024-10-01 12:38 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/Linea_Sepolia.toml
> +FinalityDepth = 200
200 is the [testnet prod value
](https://github.com/smartcontractkit/infra-k8s/blob/a7e46c641e13a3ae32b62f598f7c49dc913bd0ad/projects/chainlink/files/chainlink-clusters/cl-ccip-testnets-prod/config.yaml#L705-L706)

`200` introduced by @stackman27  at https://github.com/smartcontractkit/infra-k8s/pull/20027

I have no idea why Mainnet is set to 600, I'm following what is oriented on [CCIP Node Setup Guide](https://smartcontract-it.atlassian.net/wiki/spaces/CCIP/pages/609257802/CCIP+Node+Setup+Guide+Internally+Shared#TOML-Config)

Maybe the block time is different between testnet and mainnet and that's why?

2024-10-01 12:44 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
I am getting these values from infra-k8s prod-testnet overrides.
Do you think there's a chance that those values are also wrong?
https://github.com/smartcontractkit/infra-k8s/blob/a7e46c641e13a3ae32b62f598f7c49dc913bd0ad/projects/chainlink/files/chainlink-clusters/cl-ccip-testnets-prod/config.yaml#L662
```
[[EVM]]
      ChainID = '300'
      ChainType = 'zksync'
      FinalityTagEnabled = false
      # 200block ~ 20min concurrent with the l1_committed tag
      FinalityDepth = 200
      # block rate is ~2-5sec, so this ensures blocks are polled correctly
      LogPollInterval = '5s'
      # sufficient time for RPC to be labelled out of sync, since blockRate is pretty fast
      NoNewHeadsThreshold = '1m'

      [EVM.GasEstimator]
      # no EIP1559 to ensure our estimator does not estimate gas with MaxPriorityFee which will break minFunding requirement
      EIP1559DynamicFees = false
      # high LimitDefault for worst case pubdata bytes with BatchGasLimit reduced to 4M in OCR2Config
      LimitDefault = 2_500_000_000
      FeeCapDefault = '500 mwei'
      PriceDefault = '25 mwei'
      # p999 value for gasPrice based on historical data
      PriceMax = '500 mwei'
      # avg gasPrices are at 0.025 gwei
      PriceMin = '25 mwei'

      [EVM.GasEstimator.BlockHistory]
      # increasing this to smooth out gas estimation
      BlockHistorySize = 200

      [EVM.HeadTracker]
      # tracks top N blocks to keep in heads database table. Should store atleast the same # of blocks as finalityDepth
      HistoryDepth = 250
```

2024-10-01 12:52 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/Metis_Mainnet.toml
> +FinalityDepth = 500
Wow... nice find. I think Aditya introduced this and slipped my revision.
There is no FinalityDepth value set for Metis (testnet or mainnet)... Do you think I should remove these, then?

2024-10-01 14:38 UTC, friedemannf commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
The finality committee only really signed off on mainnets, but IMO we should set the same values for testnets as well

2024-10-28 12:56 UTC, stackman27 commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
@friedemannf we can request Finality committee (FC) to sign off on testnet values too or deduct a value with similar security assumptions. This was the case for zkSync where FC decided a 20min block time which was different on mainnet and testnet

2024-10-28 13:04 UTC, stackman27 commented on core/chains/evm/config/toml/defaults/Linea_Sepolia.toml
> +FinalityDepth = 200
yea exactly it was the block time difference. Linea  Mainnet and testnet produces block at different rates and we wanted to get to around 20min finalityTime on both networks

2024-10-28 15:56 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/Linea_Sepolia.toml
> +FinalityDepth = 200
@stackman27 you confirm that this rate is correct then?

2024-10-28 16:00 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
So... solved? Seems like this value is correct, can you please confirm @stackman27 ?

2024-10-28 17:40 UTC, stackman27 commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
@friedemannf do you have any concerns? these values are live so i don't have any concerns

2024-10-28 17:48 UTC, stackman27 commented on core/chains/evm/config/toml/defaults/Linea_Sepolia.toml
> +FinalityDepth = 200
yup it is correct and live. Ref: https://github.com/smartcontractkit/rmn-testnet-prod/blob/main/shared.toml#L457

2024-10-28 17:53 UTC, stackman27 approved these changes
LGTM! 

please add additional comments as discussed before merging

2024-10-29 12:50 UTC, Madalosso commented on core/chains/evm/config/toml/defaults/Metis_Mainnet.toml
> +FinalityDepth = 500
reason: 
https://github.com/smartcontractkit/ccip/pull/1151/commits/566f982cd7cec787f6c80be9be264039de6c37e5#r1672903236

2024-10-29 13:07 UTC, friedemannf commented on core/chains/evm/config/toml/defaults/zkSync_Sepolia.toml
> +FinalityDepth = 200
After reading up on the discussion I agree with @stackman27, 200 blocks / ~20 min on testnet 👍

2024-10-29 13:09 UTC, friedemannf approved these changes

2024-10-29 16:52 UTC, Madalosso approved these changes

2024-10-29 17:20 UTC, dhaidashenko approved these changes

2024-10-29 20:56 UTC, matYang approved these changes

2024-10-30 12:43 UTC, Madalosso commented
Blocked by #1514  (CI failure)

2024-11-06 16:38 UTC, merged