Log NewReportingPlugin errors for Commit and Exec plugins
smartcontractkit/ccip pull request #1187
Opened 2024-07-11 18:00 UTC by rstout

Also output metrics

## Motivation

## Solution

2024-07-11 20:43 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipcommit/factory.go
> +			rf.config.lggr.Errorw("NewReportingPlugin failed", "err", err)
Consider wrapping the errors returned by `newReportingPluginFn` with additional context similar to how the exec plugin does it.

2024-07-12 15:13 UTC, rstout commented on core/services/ocr2/plugins/ccip/ccipcommit/factory.go
> +			rf.config.lggr.Errorw("NewReportingPlugin failed", "err", err)
> Also, should this change be made there as well?
This change is in the exec plugin as well, or did you mean something else?

2024-07-12 16:00 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipcommit/factory.go
> +			rf.config.lggr.Errorw("NewReportingPlugin failed", "err", err)
Oops, missed that.

2024-07-12 16:01 UTC, winder approved these changes

2024-07-15 15:51 UTC, connorwstein approved these changes

2024-07-15 22:12 UTC, connorwstein requested changes, later dismissed

2024-07-15 22:12 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/ccipexec/initializers.go
> +	MaxRetries:   6 * 24, // Retry for approximately 24hrs (MaxDelay of 10m = 6 times per hour, times 24 hours)
@rstout on second thought lets make this a bit shorter. I think 4 hours would be good - that should be enough time for a nop to notice that their RPC etc is broken and address

2024-08-05 15:03 UTC, makramkd approved these changes

2024-08-07 22:19 UTC, merged