Use Finality Tag for Astar
smartcontractkit/ccip pull request #1329
Opened 2024-08-20 12:36 UTC by flodesi

## Motivation
following the [cherry pick for astar custom finaility from chainlink repo](https://github.com/smartcontractkit/ccip/pull/1324), need to enable it for astar

## Solution

2024-08-20 17:23 UTC, friedemannf approved these changes

2024-08-20 17:25 UTC, friedemannf commented
You'll need to run `make config-docs` to re-generate the documentation

2024-08-20 23:51 UTC, finleydecker requested changes

2024-08-20 23:51 UTC, finleydecker commented on core/chains/evm/config/toml/defaults/Astar_Mainnet.toml
>  # FinalityTag will be enabled once the custom tag is implemented
```suggestion
```

2024-08-20 23:51 UTC, finleydecker commented on core/chains/evm/config/toml/defaults/Astar_Mainnet.toml
>  # FinalityTag will be enabled once the custom tag is implemented
We can remove this comment now :)

2024-08-20 23:51 UTC, finleydecker commented on core/chains/evm/config/toml/defaults/Astar_Shibuya.toml
>  # FinalityTag will be enabled once the custom tag is implemented
```suggestion
```

2024-08-21 06:32 UTC, finleydecker approved these changes

2024-08-22 16:59 UTC, matYang approved these changes

2024-08-23 19:33 UTC, merged