CCIP-2824: Adding reorg test
smartcontractkit/ccip pull request #1379
Opened 2024-08-27 20:03 UTC by b-gopalswami

## Motivation
Test around reorg is not available in CCIP which let the bug (caching the block timestamp which got reorged) in mainnet. 

## Solution
Add unit level test which can identify the caching problem.
Add E2E test to assess CCIP behaviour when above and below finality reorg happens.

2024-08-29 09:03 UTC, mateusz-sekara approved these changes

2024-09-04 15:24 UTC, makramkd approved these changes

2024-09-05 06:10 UTC, Tofel commented on core/services/ocr2/plugins/ccip/integration_test.go
> +// TestReorg is to ensure CCIP works even when there is below finality depth reorg happens.
maybe... `// TestReorg ensures that CCIP works even when a below finality depth reorg happens`?

2024-09-05 06:11 UTC, Tofel commented on core/services/ocr2/plugins/ccip/integration_test.go
> +		require.NoError(t, err)
I am a big proponent of assertion messages, what do you think about adding them?

2024-09-05 06:12 UTC, Tofel commented on core/services/ocr2/plugins/ccip/integration_test.go
> +		// We need higher finality depth on the destination to perform reorg deep enough to revert commit and execution reports
I like that you have added comments explaining the what and the why!

2024-09-05 06:15 UTC, Tofel commented on core/services/ocr2/plugins/ccip/testhelpers/integration/chainlink.go
> +	sourceFD, destFD uint32,
nit: why not `sourceFinalityDepth` and `destinationFinalityDepth`?

2024-09-05 06:15 UTC, Tofel commented on core/services/ocr2/plugins/ccip/testhelpers/integration/chainlink.go
> +func createConfigV2Chain(chainId *big.Int, fd uint32) *v2.EVMConfig {
nit: `fd` -> `finalityDepth`

2024-09-05 06:17 UTC, Tofel commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +		logmsg.Msg("As expected, it got failed in one of the phases")
nit: `As expected, one of the phases failed`?

2024-09-05 06:19 UTC, Tofel commented on integration-tests/ccip-tests/actions/reorg_helpers.go
> +		assert.NoError(r.t, err)
curious, any reason for using `assert` instead of `require`? + assertion message?

2024-09-05 06:20 UTC, Tofel commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	require.NotNil(t, TestCfg.TestGroupInput.MsgDetails.DestGasLimit)
shouldn't that validation be part of test config validation? or is `nil` a correct value for message details in some cases?

2024-09-05 06:22 UTC, Tofel commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +		return
`return`? shouldn't we fail the test if there are no lanes?

2024-09-05 06:24 UTC, Tofel commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +		return violationDetectedByNodeCount == len(clNodes)
nit: any chance that this might happen:
* 5 nodes
* 4 detect violation, but 1 has 2x entries

Check passes, even though it shouldn't.

Maybe it would be more robust to store log count per node? and make sure each had at least 1 such log?

2024-09-05 06:24 UTC, Tofel commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	if setupOutput.Cfg.SelectedNetworks[1].FinalityTag {
nit: do we validate at some point that we have at least 2 networks?

2024-09-05 06:25 UTC, Tofel commented on integration-tests/ccip-tests/testconfig/tomls/ccip-reorg.toml
> +evm_http_urls = ['http://127.0.0.1:9544']
any reason for hardcoding the urls? how are these tests supposed to be run?

2024-09-05 06:25 UTC, Tofel requested changes
nice job, but I would love to see at least assertion messages added

2024-09-05 18:30 UTC, kalverra requested changes

2024-09-05 18:30 UTC, kalverra commented on core/services/ocr2/plugins/ccip/integration_test.go
> +		require.NoError(t, err)
Agreed, they help a lot if you're less familiar with the test

2024-09-05 18:30 UTC, kalverra commented on core/services/ocr2/plugins/ccip/integration_test.go
> +	t.Run("Reorg test to simulate caching problem", func(t *testing.T) {
I'm curious why there is a plain `t.Run` here instead of using the raw test?

2024-09-05 18:30 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +		logmsg.Msg("As expected, it got failed in one of the phases")
```suggestion
		logmsg.Msg("Phase failed, as expected")
```

2024-09-05 18:30 UTC, kalverra commented on integration-tests/ccip-tests/actions/reorg_helpers.go
> +		assert.NoError(r.t, err)
You're not supposed to call `require` from inside goroutines, as it just wraps [t.FailNow()](https://pkg.go.dev/testing#T.FailNow)

2024-09-06 17:06 UTC, b-gopalswami commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	require.NotNil(t, TestCfg.TestGroupInput.MsgDetails.DestGasLimit)
Ok that is copy-pasta! I do see we have config validation for [this](https://github.com/smartcontractkit/ccip/blob/12c9ba90309aa3b1984e0684ccfd3a44956be36c/integration-tests/ccip-tests/testconfig/ccip.go#L73-L75). You won't find a trace of it!

2024-09-06 17:55 UTC, b-gopalswami commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	if setupOutput.Cfg.SelectedNetworks[1].FinalityTag {
If we have only one network, then no lanes will be found and test returns way up front and moreover this test runs with custom config which has two networks.

2024-09-06 18:01 UTC, b-gopalswami commented on core/services/ocr2/plugins/ccip/integration_test.go
> +	t.Run("Reorg test to simulate caching problem", func(t *testing.T) {
Right. We don't need it.

2024-09-06 19:13 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/tomls/ccip-reorg.toml
> +evm_http_urls = ['http://127.0.0.1:9544']
I adopted this from previous work on this. I don't think it is needed. Removed it.

2024-09-06 19:15 UTC, b-gopalswami commented
@kalverra @Tofel Review comments are addressed. Please review.

2024-09-06 19:21 UTC, kalverra approved these changes
Please include a PR to the core Chainlink repo with these changes as well.

2024-09-09 16:57 UTC, Tofel approved these changes

2024-09-09 20:50 UTC, merged