Remove problematic liquidity functions and add incoming supply lock
smartcontractkit/ccip pull request #1396
Opened 2024-08-29 22:27 UTC by jhweintraub

## Motivation

Minor Changes to the HybridLockReleaseTokenPool to better meet Circle's bridge requirements

1. Add additional supply lock on incoming messages when a proposal has been created. I.E When a proposal for a chain selector is active, new tokens cannot be released or locked to ensure better security control on the destination-chain's token supply.
2. `withdrawLiquidity()` and `transferLiqudity()` have been removed to avoid issues with the supply lock. Allowing for withdrawing liquidity that has been provided would allow for the supply on the destination chain to be greater than the locked amount on the source chain, preventing a successful migration from occuring.

3. Comment fixes for invariants

2024-08-30 15:46 UTC, RensR commented on contracts/src/v0.8/ccip/pools/USDC/USDCBridgeMigrator.sol
> +/// functionality is based on hard requirements defined by Circle to allow for future CCTP compatibility
Maybe link these requirements

2024-08-30 15:48 UTC, RensR approved these changes

2024-08-30 16:00 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> -  function transferLiquidity(address from, uint64 remoteChainSelector, uint256 amount) external onlyOwner {
this is gonna make it impossible to migrate USDC liquidity to a new pool, don't we wanna have at least this as a backup?

2024-08-30 16:03 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> -  function transferLiquidity(address from, uint64 remoteChainSelector, uint256 amount) external onlyOwner {
It does but also it makes Circle uneasy about the potential for supply-imbalance that abuse of this function could cause

2024-08-30 16:16 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> -  function transferLiquidity(address from, uint64 remoteChainSelector, uint256 amount) external onlyOwner {
I don't think it changes the security assumption, technically CCIP Owner has the ability to cause imbalance via other means, having this function doesn't increase that risk

2024-09-06 04:26 UTC, matYang requested changes

2024-09-06 04:26 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +    // TODO: SourcePoolData vs. OffChainTokenData
nit

2024-09-06 04:26 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +      !shouldUseLockRelease(releaseOrMintIn.remoteChainSelector)
on the inbound direction, i.e remote -> home, do we still need `s_shouldUseLockRelease`? the flag in `sourcePoolData` can be used as source of truth

2024-09-06 04:26 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +  bytes public constant LOCK_RELEASE_FLAG = "NO_CTTP_USE_LOCK_RELEASE";
precompute this into a hash and save a kecceck on hot path

2024-09-06 04:26 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +    s_tokensExcludedFromBurn[remoteChainSelector] += amount;
with this 2nd var tracking liquidity, it won't work with withdrawLiquidity right;

can we still use `s_lockedTokensByChainSelector` as the SoT for accounting, and `s_tokensExcludedFromBurn` can be used to calc correct burn amount during the burn? With that, you also don't need `s_migratedChains`

2024-09-06 14:44 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +    s_tokensExcludedFromBurn[remoteChainSelector] += amount;
That's correct but I also am somewhat hard pressed to think of the incredibly unlikely situation whereby there's a sudden migration requiring a withdrawal and also a migration at the same time that would cause stuck liquidity issues.

2024-09-06 16:27 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +    s_tokensExcludedFromBurn[remoteChainSelector] += amount;
If i understand correctly what you're asking, then we'll make `s_lockedTokensByChainSelector` an increasing only value when liquidity is transferred in or deposited, and then the burn amount would be `s_lockedTokensByChainSelector - s_tokensExcludedFromBurn`.

In the event of a migration using `transferLiquidity` we would then just make the exclusions again manual. It's not like that information isn't known since there's a getter already available. And Honestly we can slightly rework the transfer function anyways to just pull all the liquidity since its not like there would ever be a partial migration

```
 function transferLiquidity(address from, uint64 remoteChainSelector) external onlyOwner {
    OwnerIsCreator(from).acceptOwnership();

    uint256 withdrawAmount = HybridLockReleaseUSDCTokenPool(from).getLockedTokensForChain(remoteChainSelector);

    HybridLockReleaseUSDCTokenPool(from).withdrawLiquidity(remoteChainSelector, withdrawAmount);

    s_lockedTokensByChainSelector[remoteChainSelector] += withdrawAmount;

    s_tokensExcludedFromBurn[remoteChainSelector] += HybridLockReleaseUSDCTokenPool(from).getTokensExcludedFromBurn(remoteChainSelector);

    emit LiquidityTransferred(from, remoteChainSelector, amount);
  }
```
Would mean removing the `amount` parameter from the selector but I'm fine with that since we're already not following the Lock-Release pool implementation exactly anyways.

2024-09-08 14:58 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +    s_tokensExcludedFromBurn[remoteChainSelector] += amount;
`s_tokensExcludedFromBurn` is only accurate when there can be no more USDC messages entering inflight or being executed, ie. when pool is paused both at OnRamp and OffRamp, hence it must be set and then consumed during a burn.

I think we can make the policy to simplify our state management here: if we are amidst a burn event, there should NOT be transferLiquidity going on in parallel. With that, we don't need to worry about the edge cases, such as migrating `s_tokensExcludedFromBurn`

2024-09-09 14:29 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +    s_tokensExcludedFromBurn[remoteChainSelector] += amount;
it sounds like from that then all we need is a revert in the event that the function is called in the midst of a pending migration. Given that it's owner locked that can be considered redundant anyways but still not hard to add it in.

2024-09-09 19:14 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +  bytes32 public constant LOCK_RELEASE_FLAG = 0xd43c789702079778276cca9a680e6d7bfaa2e27220f672833579b5715732145d;
nit: typically for flags we do a `bytes4(keccak256(`, check existing examples

2024-09-09 19:16 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/HybridLockReleaseUSDCTokenPool.sol
> +    s_tokensExcludedFromBurn[remoteChainSelector] += amount;
yeah wouldn't hurt to add it

2024-09-09 19:22 UTC, matYang commented on contracts/src/v0.8/ccip/pools/USDC/USDCBridgeMigrator.sol
> +    s_tokensExcludedFromBurn[remoteChainSelector] += amount;
there is a chance we want to reduce this number, e.g. in a misconfig, or cancellation of burn, this should be a set function that also supports 0

2024-09-12 14:18 UTC, matYang approved these changes

2024-09-12 14:48 UTC, merged