2.15 merge
smartcontractkit/ccip pull request #1401
Opened 2024-09-02 07:51 UTC by mateusz-sekara

## Motivation

## Solution

2024-09-02 15:21 UTC, makramkd commented on contracts/src/v0.8/keystone/KeystoneFeedsConsumer.sol
> +  error UnauthorizedWorkflowName(bytes10 workflowName);
@0xsuryansh can you check that this is not a regression?

2024-09-03 02:17 UTC, asoliman92 commented on core/services/chainlink/application.go
> +	var capabilityRegistrySyncer registrysyncer.Syncer
Code here is a bit outdated. even if 2.15 is 2 weeks ago I think it was different as most of the part related to the capabilities was last edited first week of August. Can you double check nothing was auto resolved wrongly here?

2024-09-03 02:19 UTC, asoliman92 commented on .mockery.yaml
> +  github.com/smartcontractkit/chainlink/v2/core/services/promreporter:
I'm not familiar with prom or headreporter. What's the reason for removing headreporter completely like this?

2024-09-03 07:25 UTC, mateusz-sekara commented on .mockery.yaml
> +  github.com/smartcontractkit/chainlink/v2/core/services/promreporter:
That's the state of the repo on v2.15.0

2024-09-03 07:54 UTC, mateusz-sekara commented on core/services/chainlink/application.go
> +	var capabilityRegistrySyncer registrysyncer.Syncer
2.15 was cut on 30th July from develop, which means that code is at least a month behind the current develop

2024-09-03 08:44 UTC, asoliman92 approved these changes

2024-09-03 09:50 UTC, asoliman92 approved these changes

2024-09-03 09:50 UTC, mateusz-sekara commented
Protobuf checks fails because of this breaking change https://github.com/smartcontractkit/chainlink/pull/13750

2024-09-03 09:53 UTC, makramkd requested changes

2024-09-03 09:53 UTC, makramkd commented on .swp
remove

2024-09-03 09:55 UTC, makramkd approved these changes

2024-09-03 10:15 UTC, RensR approved these changes

2024-09-03 10:15 UTC, merged