Self Serve Token Pool Factory Contract
smartcontractkit/ccip pull request #1410
Opened 2024-09-04 15:15 UTC by jhweintraub

## Motivation

To better ease the process of deploying and configuring self-serve token pools, a factory contract has been deployed which will deploy the tokens, pools, etc. and configure them with the token admin registry. This reduces the number of transactions the end user must make to configure a pool from >12 to ~3-4.

## Solution

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +import {console2 as console} from "forge-std/console2.sol";
✂️

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +  bytes32 internal constant s_salt = keccak256(abi.encode("FAKE_SALT"));
nit: technichaly not a storage var because it's a constant. Better to use SCREAMING_SNAKE_CASE.

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +
nit: ✂️

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  }
nit: struct packing comments

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  address internal immutable i_ccipRouter;
do any contracts inherit from `TokenPoolFactory`? If not these should be private :)

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  bytes4 public constant EMPTY_PARAMETER_FLAG = 0x8fc9a1e4;
nit: I would just do this...
```solidity
bytes4 public constant EMPTY_PARAMETER_FLAG = bytes4(keccak256("EMPTY_PARAMETER_FLAG"));
```
it doesn't affect the end result and this way the code kinda speaks for itself

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    bytes memory tokenPoolInitArgs,
is calldata an option? cheaper!

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    OwnerIsCreator(token).transferOwnership(address(msg.sender)); // 2 step ownership transfer
super nit: I would lean towards using an interface here like `IOwnable`

2024-09-17 15:39 UTC, RyanRHall commented on contracts/src/v0.8/shared/util/DeterministicContractDeployer.sol
> +library DeterministicContractDeployer {
could we have used OZ's [Create2 util contract?](https://docs.openzeppelin.com/contracts/5.x/api/utils#Create2) seems better to not reinvent the wheel if we don't have to

2024-09-17 15:50 UTC, jhweintraub commented on contracts/src/v0.8/shared/util/DeterministicContractDeployer.sol
> +library DeterministicContractDeployer {
It just wasn't included in the vendor files already I didn't wanna add it cause I wasn't sure exactly where it would go.

2024-09-17 15:51 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  bytes4 public constant EMPTY_PARAMETER_FLAG = 0x8fc9a1e4;
@RensR Can you weigh in please I know you prefer it pre-calculated as opposed to explicit like that. Either is fine with me.

2024-09-17 15:53 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    bytes memory tokenPoolInitArgs,
I was chosen as memory since the initCode/initArgs are modified in place often to prevent a stack too deep error.

2024-09-17 16:13 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  bytes4 public constant EMPTY_PARAMETER_FLAG = 0x8fc9a1e4;
I don't mind explicit

2024-09-17 16:16 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  function typeAndVersion() external pure returns (string memory) {
use the same way as all other constant: a constant string not a function

2024-09-17 16:17 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    RateLimiter.Config inboundRateLimiterConfig;
Probably OK to assume inbound is outbound, saves the entire second arg

2024-09-17 16:19 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    _setTokenPool(token, poolAddress);
name should be more explicit

2024-09-17 16:21 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +        if (bytes4(remoteTokenPools[i].remoteTokenAddress) == EMPTY_PARAMETER_FLAG) {
why not just check length == 0?

2024-09-17 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +          bytes memory remotePoolInitArgs = abi.encode(
can inline

2024-09-17 16:22 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  bytes4 public constant EMPTY_PARAMETER_FLAG = 0x8fc9a1e4;
Must've been Matt then that said he wanted it this way then. Works for me.

2024-09-17 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    bytes memory tokenPoolInitArgs,
I don't see tokenPoolInitCode being modified at all?

2024-09-17 16:23 UTC, RensR commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +
nit: remove newline

2024-09-17 16:23 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +
nit: remove newline

2024-09-17 16:25 UTC, RensR commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +  function setCCIPAdmin(address newAdmin) public onlyOwner {
nit: add comment stating that address(0) is a correct arg to revoke the admin role

2024-09-17 16:25 UTC, RensR commented on contracts/src/v0.8/shared/util/DeterministicContractDeployer.sol
> +library DeterministicContractDeployer {
We only add stuff that's used, that doesn't mean other contract shouldn't be added. Please use OZ wherever possible

2024-09-17 16:32 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +        if (bytes4(remoteTokenPools[i].remoteTokenAddress) == EMPTY_PARAMETER_FLAG) {
I had that before and someone asked that we use a specific flag to prevent unexpected issues for users by making it more explicit. I can change it back if we decide.

2024-09-17 16:39 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    bytes memory tokenPoolInitArgs,
good catch. That parameter can be inlined too in the deployment function to reduce a stack slot also.

2024-09-18 07:47 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +        if (bytes4(remoteTokenPools[i].remoteTokenAddress) == EMPTY_PARAMETER_FLAG) {
Who asked? I'd love to hear the reasoning. Feels like this will just add more contextual load to anyone integrating with it and it's not in line with other CCIP contracts. Is it because this is user input? Would this contract not be exclusively called through the UI, meaning we can sanity check in there as well?

2024-09-18 07:53 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  /* solhint-disable gas-struct-packing */
Please use the `next-line` syntax and `//` comments like we do in other files

2024-09-18 07:53 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    RateLimiter.Config outboundRateLimiterConfig; // The rate limiter config for token messages to be used in the pool.
Why not just rename it to rateLimiterConfig?

2024-09-18 07:54 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    bytes remotePoolAddress; // The address of the remote pool to either deploy or use as is. If
If we're doing multi-line comments, I'd prefer for them all to be above the item. The only exception is when struct packing but as that's not relevant here I think we're good

2024-09-18 07:54 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    /// The factory contract on the remote chain
/// is for natspec, use // for normal comments. Single line comments can go after the declaration instead of a newline

2024-09-18 07:55 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  bytes4 public constant EMPTY_PARAMETER_FLAG = bytes4(keccak256("EMPTY_PARAMETER_FLAG"));
nit: I prefer consts then immutable then mutable state, always starting with typeAndversion

2024-09-18 07:56 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    salt = keccak256(abi.encodePacked(salt, msg.sender));
Is this a normal thing to do? Honestly curious

2024-09-18 07:57 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    address token = Create2.deploy(0, salt, tokenInitCode);
Why assign token to a local var and below don't do that with poolAddress. Also, poolAddress and token naming are inconsistent as both are addresses. Probably fine to remove `address`. Imo it's nicer to assign to a local var than the return val when gas is not critical

2024-09-18 07:58 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    OwnerIsCreator(token).transferOwnership(address(msg.sender)); // 2 step ownership transfer
@jhweintraub I see you now import IOwnable but don't use it here?

2024-09-18 08:00 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    /// use the standard burn/mint token pool params. Since the user can provide custom token pool init code,
inconsistent `///` `//`

2024-09-18 08:01 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +          bytes memory remotePoolInitcode = abi.encodePacked(
This is not used except hashed, we can hash before we store it to save a lot of gas

2024-09-18 08:02 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +          chainUpdate.remotePoolAddress =
dup line?

2024-09-18 08:07 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    OwnerIsCreator(token).transferOwnership(address(msg.sender)); // 2 step ownership transfer
// 2 step ownership transfer comment is stale with the one above?

2024-09-18 08:10 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    OwnerIsCreator(token).transferOwnership(address(msg.sender)); // 2 step ownership transfer
msg.sender is an address, no need to cast it

2024-09-18 08:10 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    // If the user doesn't want to provide any special parameters which may be neededfor a custom the token pool then
typo: needfor

2024-09-18 08:16 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +          remoteChainSelector: remoteTokenPools[i].remoteChainSelector,
assign remoteTokenPools[i] to memory as you're using it a lot

2024-09-18 08:17 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    // Stack Scoping to reduce pressure on stack too deep
This does nothing, at least not after the suggested changes below

2024-09-18 08:19 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +      // For Each remote chain in the remoteTokenPools array
useless comment

2024-09-18 08:39 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  function _createTokenPool(
Refactored to be more readable and significantly more gas efficient


```
  /// @notice Deploys a token pool with the given token information and remote token pools
  /// @param token The token to be used in the token pool
  /// @param remoteTokenPools An array of remote token pools info to be used in the pool's applyChainUpdates function
  /// @param tokenPoolInitCode The creation code for the token pool
  /// @param tokenPoolInitArgs The arguments to be passed to the token pool's constructor and concatenated with the
  /// initCode to be passed into the deployer function
  /// @param salt The salt to be used in the create2 deployment of the token pool
  /// @return poolAddress The address of the token pool that was deployed
  function _createTokenPool(
    address token,
    RemoteTokenPoolInfo[] calldata remoteTokenPools,
    bytes calldata tokenPoolInitCode,
    bytes memory tokenPoolInitArgs,
    bytes32 salt
  ) internal returns (address) {
    // Create an array of chain updates to apply to the token pool
    TokenPool.ChainUpdate[] memory chainUpdates = new TokenPool.ChainUpdate[](remoteTokenPools.length);

    for (uint256 i = 0; i < remoteTokenPools.length; i++) {
      RemoteTokenPoolInfo memory remoteTokenPool = remoteTokenPools[i];
      RemoteChainConfig memory remoteChainConfig = s_remoteChainConfigs[remoteTokenPool.remoteChainSelector];

      // If the user provides the empty parameter flag, then the address of the token needs to be predicted
      // otherwise the address provided is used.
      if (bytes4(remoteTokenPool.remoteTokenAddress) == EMPTY_PARAMETER_FLAG) {
        // The user must provide the initCode for the remote token, so we can predict its address correctly. It's
        // provided in the remoteTokenInitCode field for the remoteTokenPool
        remoteTokenPool.remoteTokenAddress = abi.encode(
          salt.computeAddress(keccak256(remoteTokenPool.remoteTokenInitCode), remoteChainConfig.remotePoolFactory)
        );
      }

      // If the user provides the empty parameter flag, the address of the pool should be predicted
      if (bytes4(remoteTokenPool.remotePoolAddress) == EMPTY_PARAMETER_FLAG) {
        // Generate the initCode that will be used on the remote chain. It is assumed that tokenInitCode
        // will be the same on all chains, so it can be reused here.

        // Combine the initCode with the initArgs to create the full initCode
        bytes32 remotePoolInitcode = keccak256(
          bytes.concat(
            type(BurnMintTokenPool).creationCode,
            // Calculate the remote pool Args with an empty allowList, remote RMN, and Remote Router addresses.
            abi.encode(
              abi.decode(remoteTokenPool.remoteTokenAddress, (address)),
              new address[](0),
              remoteChainConfig.remoteRMNProxy,
              remoteChainConfig.remoteRouter
            )
          )
        );

        // Predict the address of the undeployed contract on the destination chain
        remoteTokenPool.remotePoolAddress =
          abi.encode(salt.computeAddress(remotePoolInitcode, remoteChainConfig.remotePoolFactory));
      }

      chainUpdates[i] = TokenPool.ChainUpdate({
        remoteChainSelector: remoteTokenPool.remoteChainSelector,
        allowed: true,
        remotePoolAddress: remoteTokenPool.remotePoolAddress,
        remoteTokenAddress: remoteTokenPool.remoteTokenAddress,
        outboundRateLimiterConfig: remoteTokenPool.outboundRateLimiterConfig,
        inboundRateLimiterConfig: remoteTokenPool.outboundRateLimiterConfig
      });
    }

    // If the user doesn't want to provide any special parameters which may be neededfor a custom the token pool then
    /// use the standard burn/mint token pool params. Since the user can provide custom token pool init code,
    // they must also provide custom constructor args.
    if (bytes4(tokenPoolInitArgs) == EMPTY_PARAMETER_FLAG) {
      tokenPoolInitArgs = abi.encode(token, new address[](0), i_rmnProxy, i_ccipRouter);
    }

    // Construct the code that will be deployed from the initCode and the initArgs
    address poolAddress = Create2.deploy(0, salt, abi.encodePacked(tokenPoolInitCode, tokenPoolInitArgs));

    // Apply the chain updates to the token pool
    TokenPool(poolAddress).applyChainUpdates(chainUpdates);

    // Being the 2 step ownership transfer of the token pool to the msg.sender.
    IOwnable(poolAddress).transferOwnership(address(msg.sender)); // 2 step ownership transfer

    return poolAddress;
  }
```

2024-09-18 11:06 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    uint64[] calldata remoteChainSelectors,
We would generally create a new struct for the args of a function like this so we are sure the lengths match

2024-09-18 11:06 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    for (uint256 i = 0; i < remoteChainSelectors.length; i++) {
i++

2024-09-18 11:06 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +      s_remoteChainConfigs[remoteChainSelectors[i]] = remoteConfigs[i];
No validation required?

2024-09-18 11:06 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    // Set the pool address in the token admin registry
These comments don't add anything over the function call name

2024-09-18 15:00 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    RateLimiter.Config outboundRateLimiterConfig; // The rate limiter config for token messages to be used in the pool.
now that we got rid of different params for in and outbound yea that would make sense

2024-09-18 15:04 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    bytes remotePoolAddress; // The address of the remote pool to either deploy or use as is. If
that was an automated thing by the linter/formatter but i'll change it.

2024-09-18 15:04 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    bytes remotePoolAddress; // The address of the remote pool to either deploy or use as is. If
that was an automated thing by the linter/formatter but i'll change it.

2024-09-18 15:09 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    salt = keccak256(abi.encodePacked(salt, msg.sender));
Yes. I've used this pattern tons of times in the past. The address of the deployment is a function of the salt, the deployer, and the initcode hash so this ensures that even if two people use the same salt they would get unique deployment addresses without having to worry about deployment frontrunning or other deployment DoS related issues.

2024-09-18 15:20 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  function _createTokenPool(
idk how i'll ever recover from being flexed on so hard.

2024-09-18 15:35 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +        if (bytes4(remoteTokenPools[i].remoteTokenAddress) == EMPTY_PARAMETER_FLAG) {
I don't remember but it doesn't matter. I had it originally as `length == 0` but I think it was argued that it should be an explicit flag to avoid accidental misconfiguration on behalf of the user. It will not be used exclusively through the front-end, but that is its intended use, which is why I think it was decided to use the explicit flag, to avoid accidental misconfiguration

2024-09-24 16:53 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +        if (bytes4(remoteTokenPools[i].remoteTokenAddress) == EMPTY_PARAMETER_FLAG) {
After talking to various people I've decided to go with the `length == 0` check instead of the explicit flag. Issue is resolved.

2024-09-25 01:05 UTC, RyanRHall requested changes

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +pragma solidity ^0.8.24;
pragmas should be fixed to a single version whenever possible!

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +contract TokenPoolFactory is OwnerIsCreator, ITypeAndVersion {
nit: contract natspec (usually at least a `@notice` to describe what the thing does)

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  // solhint-disable-next-line gas-struct-packing
so annoying lol 🤦

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  bytes4 public constant EMPTY_PARAMETER_FLAG = bytes4(keccak256("EMPTY_PARAMETER_FLAG"));
this should be private and exposed through a getter func if it needs to be read offchain or by other contracts.

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  }
just saying: I have a slight preference for accepting the actual contract type in the constructor instead of typecasting an address because I'm a strongly-typed maximilist 🙃. But also I think it helps us write better tests / deployment scripts.

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  RegistryModuleOwnerCustom internal immutable i_registryModuleOwnerCustom;
`private` yeah? I don't see the need for `internal`

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  mapping(uint64 remoteChainSelector => RemoteChainConfig remoteConfig) internal s_remoteChainConfigs;
`private`

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    address token = Create2.deploy(0, salt, tokenInitCode);
what happens if the token requires init args? As far as I can tell this is basically a BYO token init code. Some might take args yeah?

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    salt = keccak256(abi.encodePacked(salt, msg.sender));
@jhweintraub Can you help me understand better what we're protecting against here? I don't quite get it 🙃.

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  ) internal returns (address) {
`private`

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +      RemoteChainConfig memory remoteChainConfig = s_remoteChainConfigs[remoteTokenPool.remoteChainSelector];
optimization: it's cheaper to instantiate the var _outside_ the loop. Otherwise we spend some gas re-instantiating on every iteration.

```solidity
RemoteTokenPoolInfo memory remoteTokenPool;
RemoteChainConfig memory remoteChainConfig;
for (uint256 i = 0; i < remoteTokenPools.length; i++) {
  remoteTokenPool = remoteTokenPools[i];
  remoteChainConfig = s_remoteChainConfigs[remoteTokenPool.remoteChainSelector];
  // ...
}
```

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  function _setTokenPoolInTokenAdminRegistry(address token, address pool) internal {
private

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/shared/test/token/ERC20/BurnMintERC20.t.sol
> +pragma solidity 0.8.19;
No way to use 0.8.24?

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +  }
is there a `ICCIPCompatibleToken` interface that enforces presence of this function (and any other function we expect these tokens to have)?? If not, adding one might be a good idea :)

2024-09-25 01:05 UTC, RyanRHall commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +contract BurnMintERC20 is IBurnMintERC20, IERC165, ERC20Burnable, OwnerIsCreator {
From what I can tell this is basically a carbon-copy of `BurnMintERC677`, only w/o the 677 stuff. From a code-hygiene perspective, I would love to refactor `BurnMintERC677` so that it inherits this `BurnMintERC20`, and then just adds the 677 functions. I think we could DRY up the test suites too since there is a lot of duplication there.

WDYT about that @RensR? If we don't want to touch `BurnMintERC677` maybe we could just create a backlog ticket to do this refactor at some point when it makes sense?

2024-09-25 14:24 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    address token = Create2.deploy(0, salt, tokenInitCode);
It is assumed that the init args are already appended to the end of the initCode. We don't need to do anything with the args themselves so they should just be part of the initCode when it gets to this contract. The tooling we do for this factory contract will reflect this, and I will add a comment above that line.

2024-09-25 14:27 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    salt = keccak256(abi.encodePacked(salt, msg.sender));
Attacks where bots front-run your deployment either locally or on a remote chain with your salt and initcode and prevent you from deploying as a DoS vector.

2024-09-25 14:28 UTC, jhweintraub commented on contracts/src/v0.8/shared/test/token/ERC20/BurnMintERC20.t.sol
> +pragma solidity 0.8.19;
You can I just copied the test file directly from `BurnMintERC677.t.sol` since it's almost exactly the same for simplicity purposes.

2024-09-25 14:30 UTC, jhweintraub commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +contract BurnMintERC20 is IBurnMintERC20, IERC165, ERC20Burnable, OwnerIsCreator {
That sounds reasonable to me and I didn't love the amount of dry duplication here but it was in a the `shared` folder so I didn't wanna go and start refactoring a ton of stuff without permission or knowledge of the potential implications.

2024-09-25 14:30 UTC, jhweintraub commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +  }
There is not as far as i'm aware but that's a good idea.

2024-09-25 14:38 UTC, jhweintraub commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +  }
`IGetCCIPAdmin`. Will add. Good catch.

2024-09-26 09:11 UTC, RensR commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +contract BurnMintERC20 is IBurnMintERC20, IERC165, ERC20Burnable, OwnerIsCreator {
As we talked about yesterday, we should have a burnMint erc20 in `shared` which means in `chainlink` not in `ccip`. This token should then also become the default testing token for all onchain and offchain tests, leaving the 677 one kinda just for the Chainlink token. If you want I could take this part of the factory work, as it's fully separate from the ccip work? Imo those should be 2 separate tickets

2024-09-26 09:11 UTC, RensR commented on contracts/gas-snapshots/shared.gas-snapshot
> +BurnMintERC20_approve:testApproveSuccess() (gas: 55477)
we don't work in `shared` in ccip, only in chainlink

2024-09-26 09:13 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +  string public constant typeAndVersion = "TokenPoolFactory 1.0.0-dev";
Generally, we version things based on their release, which would make this 1.7.0-dev probably

2024-09-26 09:14 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory.sol
> +    for (uint256 i = 0; i < remoteTokenPools.length; i++) {
style guide: never i++, always ++i

2024-09-26 13:30 UTC, jhweintraub commented on contracts/src/v0.8/shared/token/ERC20/BurnMintERC20.sol
> +contract BurnMintERC20 is IBurnMintERC20, IERC165, ERC20Burnable, OwnerIsCreator {
I did not know that. Yes please that would be helpful

2024-10-02 10:51 UTC, RensR commented on contracts/src/v0.8/ccip/test/legacy/TokenPoolAndProxy.t.sol
> +    s_pool = new BurnWithFromMintTokenPoolAndProxy(
Why did this change?

2024-10-02 10:51 UTC, RensR commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +
fix imports

2024-10-02 10:52 UTC, RensR commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +pragma solidity ^0.8.24;
Either `^0.8.0/4` for interfaces or `0.8.24` for implementations, not `^0.8.24`

2024-10-02 10:53 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +
rm newline

2024-10-02 10:53 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +pragma solidity ^0.8.0;
This uses custom errors, cannot be 0.8.0

2024-10-02 10:53 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +// SPDX-License-Identifier: MIT
Not MIT, default to BUSL

2024-10-02 10:53 UTC, RensR commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +pragma solidity ^0.8.24;
missing license

2024-10-02 10:55 UTC, RensR commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +contract FactoryBurnMintERC20 is IBurnMintERC20, IGetCCIPAdmin, IERC165, ERC20Burnable, OwnerIsCreator {
I thought we said we want one shared BurnMintERC20 and use that as base for tokens like this

2024-10-02 14:23 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +contract FactoryBurnMintERC20 is IBurnMintERC20, IGetCCIPAdmin, IERC165, ERC20Burnable, OwnerIsCreator {
https://github.com/smartcontractkit/chainlink/pull/14605

Once that is merged I will refactor.

2024-10-02 14:24 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/legacy/TokenPoolAndProxy.t.sol
> +    s_pool = new BurnWithFromMintTokenPoolAndProxy(
`forge fmt`

2024-10-02 14:25 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +pragma solidity ^0.8.0;
I'll change it but doesn't the carrot mean it will compile with 0.8.24 since highest without breaking changes?

2024-10-02 14:26 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +// SPDX-License-Identifier: MIT
I kept it MIT because the existing BurnMintERC677 was also marked at MIT license and I wanted to maintain uniformity since this will be deployed for the end-user who may not want to use that license.

2024-10-02 14:27 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +pragma solidity ^0.8.24;
See Above MIT vs. BUSL

2024-10-15 20:14 UTC, RyanRHall requested changes

2024-10-15 20:14 UTC, RyanRHall commented on contracts/src/v0.8/ccip/interfaces/IRegistryModuleOwnerCustom.sol
> +pragma solidity ^0.8.19;
Does this need to be `^0.8.19`? Could probably be `^0.8.0` yeah?

2024-10-15 20:14 UTC, RyanRHall commented on contracts/src/v0.8/ccip/interfaces/IRegistryModuleOwnerCustom.sol
> +interface IRegistryModuleOwnerCustom {
what is the point of this interface? I can't figure out where it is used.

2024-10-15 20:14 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +pragma solidity ^0.8.0;
nit: but tests I would fix to a specific pragma

2024-10-15 20:14 UTC, RyanRHall commented on contracts/src/v0.8/shared/test/token/ERC677/OpStackBurnMintERC677.t.sol
> +
✂️

2024-10-15 20:14 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +pragma solidity ^0.8.24;
I think this comment still applies ☝️

2024-10-15 20:14 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +  event BurnAccessRevoked(address indexed burner);
instead of re-definning all the events you want to test for... are you able to emit events directly from the contract you are testing [like this](https://github.com/smartcontractkit/ccip/blob/4377d9ab5cfd40622a1d2f21ca5527f76d5daabb/contracts/src/v0.8/ccip/test/offRamp/OffRamp.t.sol#L75)? I think this is doable only in newer versions of solidity, so you might need to bump the version on the test file.

2024-10-15 20:20 UTC, jhweintraub commented on contracts/src/v0.8/ccip/interfaces/IRegistryModuleOwnerCustom.sol
> +interface IRegistryModuleOwnerCustom {
ah dang you're right I totally forgot to change the `RegistryModuleOwnerCustom` to `IRegistryModuleOwnerCustom` in the token pool factory. I'll remove it.

2024-10-21 17:58 UTC, RyanRHall requested changes
just a handful of nits left. Sorry to be so picky!

2024-10-21 17:58 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +  address internal s_mockPool = address(6243783892);
For stuff like this, I like to use foundry's [makeAddr](https://book.getfoundry.sh/reference/forge-std/make-addr)

2024-10-21 17:58 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +    s_burnMintERC20 = new FactoryBurnMintERC20(name, symbol, decimals, maxSupply, 1e18, s_alice);
nit: I feel like we could just assert against the contract deployed in the setup() function, rather than deploying a new one

2024-10-21 17:58 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +  function testApproveSuccess() public {
nit: convention in our codebass is to add underscores ex `test_Approve_Success`

2024-10-21 17:58 UTC, RyanRHall commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/TokenPoolFactory.t.sol
> +  uint256 public constant PREMINT_AMOUNT = 1e20; // 100 tokens in 18 decimals
can also do `100 ether`

2024-10-21 17:58 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/FactoryBurnMintERC20.sol
> +
✂️

2024-10-21 17:58 UTC, RyanRHall commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/TokenPoolFactory.sol
> +  ) internal pure virtual returns (bytes32) {
can this be made private?

2024-10-21 17:58 UTC, RyanRHall commented on contracts/src/v0.8/shared/token/ERC677/OpStackBurnMintERC677.sol
>  import {BurnMintERC677} from "./BurnMintERC677.sol";
I don't think these are grouped according to styleguide

2024-10-21 17:58 UTC, RyanRHall requested changes
just a handful of nits left. Sorry to be so picky!

2024-10-22 14:16 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +  address internal s_mockPool = address(6243783892);
I usually do too but I didn't write a lot of these tests, they were copied from the `BurnMintERC677.t.sol` file for simplicity since we knew those tests were appropriate. I'll change it anyways but just informing you that's why some  things are the way they are

2024-10-22 14:17 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +    s_burnMintERC20 = new FactoryBurnMintERC20(name, symbol, decimals, maxSupply, 1e18, s_alice);
I could've sworn that coverage tests don't apply to the setup function which is why there's always a testConstructorSuccess() function

2024-10-22 14:19 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/tokenAdminRegistry/FactoryBurnMintERC20.t.sol
> +  function testApproveSuccess() public {
They are. I'll change it all but for reference @RensR is the one who wrote all of those tests in the original version of that file.

2024-10-22 14:21 UTC, jhweintraub commented on contracts/src/v0.8/ccip/tokenAdminRegistry/TokenPoolFactory/TokenPoolFactory.sol
> +  ) internal pure virtual returns (bytes32) {
Not if we want to make it virtual, which I kept in there for potential modifications and inheritance in the next version of the contract which will be worked on next year.

2024-10-23 15:16 UTC, closed without merging