CCIP-3420: Fix IsRequestTriggeredWithinTimeframe
smartcontractkit/ccip pull request #1445
Opened 2024-09-16 21:31 UTC by b-gopalswami

## Motivation
The prior approach to find if there is traffic in a lane was not detecting the transactions properly. It could be due to the `CCIPSendRequestedWatcher` captures the event after it is initiated not any transaction before that.

## Solution
The revised approach is to use the FilterCCIPSendRequested by a past derived block number and see if there is any traffic. The block number is derived by this formula:
`filterFromBlock  = latestBlockNumber - (SkipRequestIfAnotherRequestTriggeredWithin/avgBlockTime)`
By this approach, we will be able to find traffic better.

2024-09-16 21:48 UTC, AnieeG requested changes

2024-09-16 21:48 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	iterator, err := onRampContract.FilterCCIPSendRequested(&bind.FilterOpts{
no need for additional filtering you can just set the start block in existing  watchEvents

2024-09-17 17:09 UTC, b-gopalswami commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	iterator, err := onRampContract.FilterCCIPSendRequested(&bind.FilterOpts{
I tried that approach, but it appears that the filter is effective for retrieving historical events, while the watcher captures live events. As discussed, I have added a new function: it uses the filter approach for the first message to handle historical events and the watcher approach for subsequent messages to handle live events.

2024-09-18 08:15 UTC, gheorghestrimtu approved these changes

2024-09-18 17:25 UTC, AnieeG approved these changes

2024-09-18 17:35 UTC, merged