[CCIP-3376] Add component into CCIP price estimators to account for c…
smartcontractkit/ccip pull request #1446
Opened 2024-09-18 15:06 UTC by valerii-kabisov-cll

…hain specific logic for Mantle

## Motivation

## Solution

2024-09-19 04:55 UTC, matYang commented on core/services/relay/evm/evm.go
> +	mantleInterceptor, err := mantle.NewInterceptor(ctx, r.chain.Client(), r.chain.Config().EVM().ChainType())
note:
1. we need the interceptor both for CCIPCommit and CCIPExec;
2. CCIPCommit reads only when source chain is Mantle, then reports to dest chain. CCIPExec reads when dest chain is mantle, and uses it to calc boosting in batching

to minimize misconfig risk, might make sense to wire Mantle only when Commit + Mantle + IsSourceProvider, and Exec + Mantle + !IsSourceProvider, let me know if my understanding is correct

2024-09-19 04:55 UTC, matYang commented on core/services/relay/evm/evm.go
> +	mantleInterceptor, err := mantle.NewInterceptor(ctx, r.chain.Client(), r.chain.Config().EVM().ChainType())
why not
```
if chaintype == mantle {
  mantle.NewInterceptor...
}
```

2024-09-19 04:55 UTC, matYang commented on core/services/ocr2/plugins/ccip/prices/da_price_estimator.go
> +		gasPrice = g.feeEstimatorConfig.ModifyDAGasPrice(gasPrice)
note the `gasPrice` here is encoded, i.e higher order 112 bit for DA + lower order 112 bit for exec, we do not want the interceptor to know this detail, can probably do 
```
gasPrices := []{
  { type: DA, value: big.Int },
  { type: Exec, value: big.Int },
}
g.feeEstimatorConfig.ModifyDAGasPrice(gasPrices)
```
no need to defer, prefer explicit control flow

2024-09-19 05:05 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	interceptor.tokenRatio, err = interceptor.getMantleGasPrice(ctx)
let's do the initial fetching under `processUpdate`, so that an occasional RPC error does not fail the interceptor initialization

`ModifyDAGasPrice` can be named `ModifyGasPriceComponents`, and it can error; e.g if TokenRatio is not ready, Mantle interceptor can error, da_price_estimator can bubble it up during `GetGasPrice`

2024-09-19 05:15 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	go interceptor.processUpdate(ctx)
Commit/Exec jobs can reboot many times, to make the call in a periodic background process, we need to manage its lifecycle like a service, should be easier to just use a cached solution that occasionally blocks, for example, read once, then only read it again if time has passed >1hr

2024-09-20 02:03 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/config.go
> +	ModifyGasPriceComponents(ctx context.Context, gasPrice, daGasPrice *big.Int) (*big.Int, *big.Int, error)
`execGasPrice, daGasPric`

2024-09-20 02:17 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/config.go
> +	ModifyGasPriceComponents(ctx context.Context, gasPrice, daGasPrice *big.Int) (modGasPrice, modDAGasPrice *big.Int, err error)
ditto

2024-09-20 02:17 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	newGasPrice := new(big.Int).Add(gasPrice, daGasPrice)
?
we want tokenRatio to be applied on top of execGasPrice and daGasPrice

2024-09-20 02:17 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	rpcBatchCalls := []rpc.BatchElem{
this is a single RPC call, no need to use batch call, you can use 
```
i.client.CallContract(ctx, ethereum.CallMsg{
		To:   &rollups.OPGasOracleAddresss,
		Data: tokenRatioCallData,
	}, nil)
```

2024-09-20 02:17 UTC, matYang commented on core/services/ocr2/plugins/ccip/prices/da_price_estimator.go
> +	gasPrice, err = g.execEstimator.GetGasPrice(ctx)
we would prefer this to be specifically `execGasPrice`, not the generic `gasPrice`

2024-09-20 02:17 UTC, matYang commented on core/services/ocr2/plugins/ccip/prices/da_price_estimator.go
> +		gasPrice, daGasPrice, err = g.feeEstimatorConfig.ModifyGasPriceComponents(ctx, gasPrice, daGasPrice)
don't have to do this in if-else, you can run this right before the daGasPrice check, and just ignore daGasPrice in the interceptor if it is nil

2024-09-20 02:18 UTC, matYang commented on core/services/relay/evm/evm.go
> +		if err != nil {
NewInterceptor should not be able to return error, we do not want RPC issue to stop plugin initialization

2024-09-20 11:58 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/prices/da_price_estimator.go
> +		gasPrice, daGasPrice, err = g.feeEstimatorConfig.ModifyGasPriceComponents(ctx, gasPrice, daGasPrice)
fair point 👍

2024-09-20 17:26 UTC, ogtownsend commented on core/services/ocr2/plugins/ccip/estimatorconfig/config.go
> +	for _, interceptor := range c.gasPriceInterceptors {
What's an example of when we'd want to have multiple interceptors for a given estimator? Or is storing all interceptors for all chains?

2024-09-20 18:17 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/config.go
> +	for _, interceptor := range c.gasPriceInterceptors {
For example storing interceptors for multiple chains. Apply some additional rules, like if the gas value is 0 and the chain is ZKSync, set the minGasFee value. Tbh I don't know how else it can be used, but it implemented in flexible way.

2024-09-21 04:51 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	// returns result of (execGasPrice+daGasPrice)*i.tokenRatio as a execGasPrice, daGasPrice not modified.
why? we want
```
execGasPrice = execGasPrice *tokenRatio 
daGasPrice = daGasPrice * tokenRatio
```

2024-09-21 13:18 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	// returns result of (execGasPrice+daGasPrice)*i.tokenRatio as a execGasPrice, daGasPrice not modified.
No reason, actually, I didn't get calculation method initially and brought it from the first PoC implementation.

2024-09-21 13:18 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	// returns result of (execGasPrice+daGasPrice)*i.tokenRatio as a execGasPrice, daGasPrice not modified.
fixed

2024-09-23 05:07 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +func (i *Interceptor) getMantleGasPrice(ctx context.Context) (*big.Int, error) {
nit: `getMantleTokenRatio`

2024-09-23 05:07 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	tokenRatio, err := i.client.CallContract(ctx, ethereum.CallMsg{
Just checked Mantle docs, there is a `[DECIMALS](https://mantlescan.xyz/address/0x420000000000000000000000000000000000000F#readProxyContract)` function on their gas oracle

example of it being fetched: https://github.com/smartcontractkit/ccip/blob/ccip-develop/core/chains/evm/gas/rollups/op_l1_oracle.go#L508

we want to scale the tokenRatio result down by # of decimals, e.g if it returns `4213`, it really means `0.004213`

DECIMALS is supposed to be constant, you can fetch it the 1st time, cache it and never need to refresh again.

2024-09-23 05:07 UTC, matYang commented on core/services/ocr2/plugins/ccip/prices/da_price_estimator.go
> +func (g DAGasPriceEstimator) GetGasPrice(ctx context.Context) (execGasPrice *big.Int, err error) {
nite, the returned value is not execGasPrice, it is the 2D encoded gas price that contains both da and exec

2024-09-23 07:57 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/prices/da_price_estimator.go
> +func (g DAGasPriceEstimator) GetGasPrice(ctx context.Context) (execGasPrice *big.Int, err error) {
yes, right, I confused with naming🤕

2024-09-23 12:20 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	tokenRatio, err := i.client.CallContract(ctx, ethereum.CallMsg{
@matYang I've implemented a separate request to fetch the decimal value.  Could you please recheck it?

2024-09-24 04:44 UTC, matYang commented on core/services/ocr2/plugins/ccip/prices/da_price_estimator.go
> +	gasPrice, err := g.execEstimator.GetGasPrice(ctx)
nit: result of `execEstimator.GetGasPrice(ctx)` should still be called `execGasPrice`

2024-09-24 04:45 UTC, matYang approved these changes

2024-09-24 09:26 UTC, mateusz-sekara requested changes

2024-09-24 09:26 UTC, mateusz-sekara commented on core/services/relay/evm/evm.go
> +	if r.chain.Config().EVM().ChainType() == chaintype.ChainMantle && commitPluginConfig.IsSourceProvider {
Here we have `commitPluginConfig.IsSourceProvider` , but in exec there is a negation of `!execPluginConfig.IsSourceProvider`. Any comment on that? Looks like bug

2024-09-24 09:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		log.Panicf("failed to parse GasPriceOracle %s() method ABI for Mantle; %v", tokenRatioMethod, err)
Why `log.Panicf`? If you want to log it then use logger. However, I think you should return an error from the contructor. Right now you will silently log errors and return broken struct, right?

2024-09-24 09:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		mantleTokenRatio, err := i.getMantleTokenRatio(ctx)
I guess we can't just call contracts directly from the plugin logic, can we @dimkouv . I think it should belong to some reader to stay compliant with loops

2024-09-24 09:28 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		i.tokenRatio, i.tokenRatioLastUpdate = mantleTokenRatio, time.Now()
Is it thread-safe to do it like this? Any chance multiple routines will try to do it simultaneously?

2024-09-24 09:30 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	tokenRatioUpdateInterval = 60 * time.Minute
Are we sure about this value? If it's hardcoded then adjustment will require a new release

2024-09-24 10:23 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		log.Panicf("failed to parse GasPriceOracle %s() method ABI for Mantle; %v", tokenRatioMethod, err)
It shouldn't return an error, @matYang was against it. But it not silently logging. It panic.

2024-09-24 10:25 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		i.tokenRatio, i.tokenRatioLastUpdate = mantleTokenRatio, time.Now()
yes, even in concurrent write situations, it not fail the app execution flow. Just the second process will write slightly different time.

2024-09-24 10:32 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	tokenRatioUpdateInterval = 60 * time.Minute
we guess that it would be sufficient :)

2024-09-24 11:12 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		log.Panicf("failed to parse GasPriceOracle %s() method ABI for Mantle; %v", tokenRatioMethod, err)
I don't think panic is a good approach, misconfig will bring the plugin down, what's wrong with returning error? This is exactly what we do in the parent function when something is misconfigured or fail to init

2024-09-24 12:27 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	tokenRatioUpdateInterval = 60 * time.Minute
Mantle updates like like very 30min, it's a ratio of price of Eth / price of Mantle, 60min resolution should be adequate

2024-09-24 12:29 UTC, matYang commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		log.Panicf("failed to parse GasPriceOracle %s() method ABI for Mantle; %v", tokenRatioMethod, err)
I think my suggestion was against making an RPC call and return an error in `NewInterceptor`, we don't want temp RPC issue to block plugin initialization, it does make sense to error if there is a misconfig

2024-09-24 12:34 UTC, matYang commented on core/services/relay/evm/evm.go
> +	if r.chain.Config().EVM().ChainType() == chaintype.ChainMantle && commitPluginConfig.IsSourceProvider {
EvmFeeEstimator is called for the source chain price reporting in Commit, and called for dest chain cost estimation in Exec, this is where the Commit -> Source, Exec -> !Source came from

would indeed be great to add comments; and maybe it doesn't matter if it's source or not, we might always add the interceptor for Mantle, @valerii-kabisov-cll you can double check if always adding it has side effects

2024-09-24 12:51 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		log.Panicf("failed to parse GasPriceOracle %s() method ABI for Mantle; %v", tokenRatioMethod, err)
We don't call RPC in the constructor so we should return error instead of panic ;)

2024-09-24 12:52 UTC, mateusz-sekara commented on core/services/relay/evm/evm.go
> +	if r.chain.Config().EVM().ChainType() == chaintype.ChainMantle && commitPluginConfig.IsSourceProvider {
cool, let's have a doc for that

2024-09-24 13:03 UTC, valerii-kabisov-cll commented on core/services/relay/evm/evm.go
> +	if r.chain.Config().EVM().ChainType() == chaintype.ChainMantle && commitPluginConfig.IsSourceProvider {
Actually, I don't see all corner cases here. My initial idea was always to add a mantle interceptor and check chain type in the `ModifyGasPriceComponents` method. I don't know which is more robust

2024-09-24 13:54 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		log.Panicf("failed to parse GasPriceOracle %s() method ABI for Mantle; %v", tokenRatioMethod, err)
fixed

2024-09-24 13:56 UTC, mateusz-sekara approved these changes

2024-09-24 14:23 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +		mantleTokenRatio, err := i.getMantleTokenRatio(ctx)
Since this logic is hidden behind the custom provider interface it should still be compliant with loops.

2024-09-24 14:26 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	"github.com/ethereum/go-ethereum"
chain specific dependencies should not live with product specific code

2024-09-24 14:43 UTC, valerii-kabisov-cll commented on core/services/ocr2/plugins/ccip/estimatorconfig/interceptors/mantle/interceptor.go
> +	"github.com/ethereum/go-ethereum"
Moved to core/services/relay/evm/interceptors/mantle/interceptor.go

2024-09-24 15:28 UTC, patrickhuie19 approved these changes

2024-09-24 15:31 UTC, merged