CCIP-3461: Optimize mainnet soak test
smartcontractkit/ccip pull request #1458
Opened 2024-09-20 22:01 UTC by b-gopalswami

Motivation
Optimize the resource and fund consumption of the mainnet soak test. Currently, the mainnet soak test runs every six hours in Kubernetes, executing one CCIP transaction per hour for a duration of five hours across 28 bidirectional lanes. This setup is designed to provide consistent observability data on the CCIP mainnet, allowing us to differentiate between service outages and quiet periods. However, these tests are inefficient, consuming Kubernetes resources and significant mainnet funds.

Ideas:

Discussion [thread](https://chainlink-core.slack.com/archives/C02PBKHCP28/p1726678958525029) is initiated with o11y team and decided that it's not required to create txs for every hour instead create one tx if there are no activity for last 24h.
Convert to smoke test as we are planning to fire only one request instead of Soak test.
Converting to smoke will elevate the K8 resource consumption as the test will run using github runner.
Solution

- [ ]  1. Modify the pipeline to run it as smoke test
- [ ]  2. Add traffic check to smoke test
- [ ]  3. Add new set of additional 21 lanes and resulted in total of 49 lanes. (i.e 98 unique lanes)
- [ ]  5. Add RPCs, Wallet key for new lanes to test secrets
- [ ]  6. Load funds for new lanes
- [ ]  7. Schedule pipeline to run for every 6hrs

2024-09-23 15:12 UTC, b-gopalswami commented
Hey @matYang @kalverra @AnieeG  @emate @andrevmatos @mateusz-sekara, Could you all please take a look at this PR and share your feedback?

2024-09-23 17:26 UTC, kalverra requested changes, later dismissed

2024-09-23 17:26 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +		err = iterator.Close()
Can just change this to `interatorErr` and log it if it's not nil instead of changing the outer err.

```suggestion
		iterErr = iterator.Close()
		if iterErr != nil {
		     sourceCCIP.Logger.Error().Err(err).Msg("Error closing iterator")
		 }
```

2024-09-23 17:26 UTC, kalverra commented on .github/workflows/ccip-live-network-tests.yml
>      needs: [ build-chainlink, build-test-image ]
Do we need to keep any of the load test options around if this is fully converting to just smoke? Is this used for other purposes?

2024-09-23 17:52 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/override/mainnet.toml
> +PhaseTimeout = '40m'
Why?

2024-09-23 17:52 UTC, AnieeG commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	lookBackDuration := TestCfg.TestGroupInput.SkipRequestIfAnotherRequestTriggeredWithin
It's better to create a separate test for this. Otherwise when you cannot run usual deployment smoke test with same config.

2024-09-23 17:52 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/override/mainnet.toml
> +  'ETHEREUM_MAINNET,BLAST_MAINNET', # added as batch 3
what does this comment mean?

2024-09-23 17:54 UTC, AnieeG commented on .github/workflows/ccip-live-network-tests.yml
>      needs: [ build-chainlink, build-test-image ]
Also if it's only smoke now, it might make sense to run this directly in github action instead of remote runner, It will save a lot of time reducing the step for building the test image, Also no need for K8 env for that.

2024-09-23 18:04 UTC, b-gopalswami commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	lookBackDuration := TestCfg.TestGroupInput.SkipRequestIfAnotherRequestTriggeredWithin
Usual run on this test won't have this variable SkipRequestIfAnotherRequestTriggeredWithin defined. In that case, it works exactly the way how it works now. That variable will be defined only in this workflow for now.

2024-09-23 18:04 UTC, b-gopalswami commented on .github/workflows/ccip-live-network-tests.yml
>      needs: [ build-chainlink, build-test-image ]
As discussed, I left that as is to have capability available and we can run it whenever we need to.

2024-09-23 18:06 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/override/mainnet.toml
> +  'ETHEREUM_MAINNET,BLAST_MAINNET', # added as batch 3
Do you know what's the comment meaning # added as batch 1 & 2? I just thought of keep it consistent without even knowing why? 😄

2024-09-23 18:08 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/override/mainnet.toml
> +PhaseTimeout = '40m'
The phase timeouts are varies widely between lanes. I think we need a better solution to define this per lane. This 20m timeout works for fastest lanes but fails to wait for most of the lanes. Even with this 40m update, still there may be lanes which takes more time than that!

2024-09-23 19:32 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/override/mainnet.toml
> +PhaseTimeout = '40m'
Need to report those lanes.

2024-09-23 19:34 UTC, AnieeG commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	lookBackDuration := TestCfg.TestGroupInput.SkipRequestIfAnotherRequestTriggeredWithin
You will need two configs for mainnet deployment test ( one for periodic run and another for usual mainnet deployment sanity test if required) which will be confusing.

2024-09-23 19:35 UTC, AnieeG commented
Why not update the cron schedule as well?

2024-09-24 19:41 UTC, b-gopalswami commented on integration-tests/ccip-tests/smoke/ccip_test.go
> +	lookBackDuration := TestCfg.TestGroupInput.SkipRequestIfAnotherRequestTriggeredWithin
Added as a separate test

2024-09-24 19:41 UTC, b-gopalswami commented on integration-tests/ccip-tests/testconfig/override/mainnet.toml
> +  'ETHEREUM_MAINNET,BLAST_MAINNET', # added as batch 3
Removed it all together.

2024-09-24 19:43 UTC, b-gopalswami commented on .github/workflows/ccip-live-network-tests.yml
>      needs: [ build-chainlink, build-test-image ]
@kalverra @AnieeG Fixed the workflow run using github runner along with matrix option to handle load in parallel and for better debugging. Have also provided option to override the phase timeout so that based on slower chains, we can update this.

2024-09-24 19:44 UTC, b-gopalswami commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +		err = iterator.Close()
Updated

2024-09-24 19:46 UTC, b-gopalswami commented
> Why not update the cron schedule as well?
I think we can keep this as is and can reduce it if needed.

2024-09-25 21:47 UTC, AnieeG approved these changes

2024-09-26 17:01 UTC, makramkd approved these changes

2024-09-26 17:45 UTC, merged