Ccip 1039 publish test image on each release with release tag
smartcontractkit/ccip pull request #171
Opened 2023-09-27 14:31 UTC by jasonmci

## Motivation

## Solution

2023-09-28 13:12 UTC, chainchad requested changes

2023-09-28 13:12 UTC, chainchad commented on .github/workflows/integration-tests-publish.yml
> +        run: echo "::set-output name=tag::$(git describe --tags --match 'v*' --exact-match 2>/dev/null)"
You might be able to get rid of this step completely. If you do need output, I would go with the new format (set-output is [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)): `echo "tag=$(...)" >> "$GITHUB_OUTPUT"`

2023-09-28 13:12 UTC, chainchad commented on .github/workflows/integration-tests-publish.yml
> +        run: echo "::set-output name=tag::$(git describe --tags --match 'v*' --exact-match 2>/dev/null)"
This workflow runs on other triggers besides a tag push. When it runs on a branch, should you completely avoid setting a `RELEASE_TAG`?

2023-09-28 13:12 UTC, chainchad commented on .github/workflows/integration-tests-publish.yml
We should be able to get rid of this:
```

env:
  ECR_TAG: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink-ccip-tests:develop
```

Now that it's no longer ref'd, right?

2023-09-28 13:12 UTC, chainchad commented on .github/workflows/integration-tests-publish.yml
> +          RELEASE_TAG="${{ steps.extract_tag.outputs.tag != '' && format('{0}.dkr.ecr.{1}.amazonaws.com/chainlink-ccip-tests:{2}', secrets.QA_AWS_ACCOUNT_NUMBER, secrets.QA_AWS_REGION, steps.extract_
We have to account for the fact that this workflow could run in situations where there's not a tag push (like branch or manual dispatch). For that, we usually add a conditional to the step:

`if: startsWith(github.ref, 'refs/tags/')`

Then, once you know it's a tag, you can refer to the tag name in the GitHub Actions context of `${{ github.ref_name }}` which should let you avoid the `extract_tag` tag step above.

If this is triggered on a branch push, is it OK if the input value for `other_tags` is an empty string? If so, I might do that.

2023-10-12 07:06 UTC, jasonmci commented on .github/workflows/integration-tests-publish.yml
> +        run: echo "::set-output name=tag::$(git describe --tags --match 'v*' --exact-match 2>/dev/null)"
resolved. removed this completely

2023-10-12 07:07 UTC, jasonmci commented on .github/workflows/integration-tests-publish.yml
I don't know how this is used. As long as I can have more than one tag on an image, I think it meets what people need. If we dont need it, I can remove it.

2023-10-12 17:36 UTC, chainchad approved these changes

2023-10-12 18:17 UTC, AnieeG approved these changes

2023-10-12 19:20 UTC, connorwstein approved these changes

2023-10-12 19:27 UTC, merged