CCIP telemetry
smartcontractkit/ccip pull request #235
Opened 2023-10-26 01:37 UTC by sirenko

## Motivation

## Solution

2023-11-03 10:03 UTC, mateusz-sekara requested changes

2023-11-03 10:03 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin_test.go
> +			if p.monitoringEndpoint == nil {
How about 
```go
require.NotNil(p.monitoringEndpoint, "msg")
```

2023-11-03 10:03 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	telem := r.collectCommitTelemetry(&report, &epochAndRound)
How about moving this responsibility outisde of the already huge commit/exec plugin? I feel that we keep adding logic to the plugin which doesn't belong there, over 1k LoC and still growing :D 

Having this a separate type gives us additionally ability to easily mock by just passing Noop implementation or mock with single function mocked 

For instance
```go
type TelemetryReporter interface {
	ReportCommit(report *ccipdata.CommitStoreReport, epochAndRound *types.ReportTimestamp)
	ReportExec(observedMessages []ObservedMessage)
}

type telemetryReporter struct {
	monitoringEndpoint commontypes.MonitoringEndpoint
	lggr               logger.Logger
}

func NewTelemetryReporter(monitoringEndpoint commontypes.MonitoringEndpoint, lggr logger.Logger) *telemetryReporter {
	return &telemetryReporter{
		monitoringEndpoint: monitoringEndpoint,
		lggr:               lggr,
	}
}

func (r *telemetryReporter) ReportCommit(report *ccipdata.CommitStoreReport, epochAndRound *types.ReportTimestamp) {
	telem := &telemPb.CCIPTelemWrapper{
		Msg: &telemPb.CCIPTelemWrapper_CommitReport{
			CommitReport: &telemPb.CCIPCommitReportSummary{
				LenTokenPrices: uint32(len(report.TokenPrices)),
				LenGasPrices:   uint32(len(report.GasPrices)), // XXX: if the len is short, would it be better to send the actual gas prices?
				Epoch:          epochAndRound.Epoch,
				Round:          uint32(epochAndRound.Round),
			},
		},
	}
	r.maybeSend(telem)
}

func (r *telemetryReporter) ReportExec(observedMessages []ObservedMessage) {
	var telem *telemPb.CCIPTelemWrapper
	if len(observedMessages) > 0 {
		telem = &telemPb.CCIPTelemWrapper{
			Msg: &telemPb.CCIPTelemWrapper_ExecutionReport{
				ExecutionReport: &telemPb.CCIPExecutionReportSummary{
					LenTokenData: uint32(len(observedMessages[0].MsgData.TokenData)),
				},
			},
		}
	}
	r.maybeSend(telem)
}

func (r *telemetryReporter) maybeSend(telemetry *telemPb.CCIPTelemWrapper) {
	bytes, err := proto.Marshal(telemetry)
	if err != nil || r.monitoringEndpoint == nil {
		// Telemetry related errors are not critical and must not affect
		// execution, so we log them and continue.
		r.lggr.Errorw("cannot marshal or send telemetry", "err", err)
	} else {
		r.monitoringEndpoint.SendLog(bytes)
	}
}
```

Then in exec/commit plugin you can make it as simple as possible by
```go
func (r *CommitReportingPlugin) Report(ctx context.Context, epochAndRound types.ReportTimestamp, _ types.Query, observations []types.AttributedObservation) (bool, types.Report, error) {
       // ...
       defer r.telemReporter.ReportCommit(report, epochAndRound)
}
```

2023-11-03 10:03 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin_test.go
> +func genMonitoringEndpoint(t *testing.T) commontypes.MonitoringEndpoint {
Mocking too many internals imo, check the comment above about using separate struct for telemetry reporting

2023-11-03 10:03 UTC, mateusz-sekara commented on core/services/synchronization/telem/telem_ccip.proto
> +    uint32 len_token_data = 1;
Why don't we report as well?
```
    uint32 epoch = 3;
    uint32 round = 4;
```


It would make both metrics more "symmetric" and it would be probably easier to identify which OCR round/epoch produced that particular data point

2023-11-03 10:03 UTC, mateusz-sekara commented on core/services/synchronization/telem/telem_ccip.proto
> +message CCIPCommitReportSummary {
I don't know what are the limitation here's, but wow about reporting mix/max sequence numbers? Or number of messages included into the root? This would give us some insights on how many msgs are pushed to chain. Number of messages within a single root can be computed as `Interval.Max - Interval.Min`

2023-11-03 10:18 UTC, mateusz-sekara commented on core/services/synchronization/telem/telem_ccip.proto
> +    uint32 len_token_data = 1;
Maybe also tracking the number of messages pushed within a single report?

2023-11-03 10:19 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +					LenTokenData: uint32(len(observedMessages[0].MsgData.TokenData)),
Hmm, only the first message is tracked? I don't see much value in that tbh

2023-11-06 11:31 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +			monitoringEndpoint: rf.config.monitoringEndpoint,
You can initialize TelemetryCollector here ;)

2023-11-06 11:32 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +			monitoringEndpoint: rf.config.monitoringEndpoint,
You can initialize `TelemetryCollector` here ;)

2023-11-07 08:36 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/telemetry_collector.go
> +	telemOnce.Do(func() { // For Java/GOF fans -- it's a singleton.
Is it possible for `monitoringEndpoint` to change and restart the job without restarting the entire node? If yes, then we will end up using the same singleton and previous values from monitoringEndpoint. Just double checking, maybe that's not a case

2023-11-07 08:36 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	telemetryCollector *telemetryCollector
I think `//Telemtry` comment id redundant as the variable is self explanatory ;)

2023-11-07 21:41 UTC, sirenko commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin_test.go
> +			if p.monitoringEndpoint == nil {
Done.

2023-11-07 21:42 UTC, sirenko commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	telem := r.collectCommitTelemetry(&report, &epochAndRound)
Refactored.

2023-11-08 00:05 UTC, sirenko commented on core/services/ocr2/plugins/ccip/telemetry_collector.go
> +	telemOnce.Do(func() { // For Java/GOF fans -- it's a singleton.
Outlined above scenario is unlikely to happen. Real-time team runs stateless, horizontally scalable, monitoring EPs behind LB. They should be able to restart them in a rolling manner with no downtime, EP change, nor data loss.

2023-11-08 00:06 UTC, sirenko commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	telemetryCollector *telemetryCollector
Cleaned out.

2023-11-08 00:06 UTC, sirenko commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +			monitoringEndpoint: rf.config.monitoringEndpoint,
Done.

2023-11-08 05:29 UTC, sirenko commented on core/services/synchronization/telem/telem_ccip.proto
> +message CCIPCommitReportSummary {
Added.

2023-11-08 05:29 UTC, sirenko commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +					LenTokenData: uint32(len(observedMessages[0].MsgData.TokenData)),
Changed it to aggregated length.

2023-11-08 05:31 UTC, sirenko commented on core/services/synchronization/telem/telem_ccip.proto
> +    uint32 len_token_data = 1;
Added.

2023-11-08 10:24 UTC, mateusz-sekara approved these changes

2023-11-08 16:28 UTC, dadaism commented
@sirenko need to fix the following issues:
```
Error: core/services/ocr2/plugins/ccip/execution_reporting_plugin.go:77:84: undefined: bind
Error: core/services/ocr2/plugins/ccip/execution_reporting_plugin.go:77:107: undefined: custom_token_pool
Error: core/services/ocr2/plugins/ccip/execution_reporting_plugin.go:158:98: undefined: bind
Error: core/services/ocr2/plugins/ccip/execution_reporting_plugin.go:158:121: undefined: custom_token_pool
Error: core/services/ocr2/plugins/ccip/execution_reporting_plugin.go:159:12: undefined: custom_token_pool
```

2023-11-08 16:31 UTC, dadaism commented
Need to add import `"github.com/smartcontractkit/chainlink/v2/core/gethwrappers/ccip/generated/custom_token_pool"`

2023-11-08 19:35 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin_test.go
> +	// me := genMonitoringEndpoint(t)
to remove?

2023-11-08 19:35 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	telemetryCollector *telemetryCollector
should be using the TelemetryCollector interface here? O/w the abstraction doesn't help much

2023-11-08 19:35 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/telemetry_collector.go
> +func (tc *telemetryCollector) ReportCommit(report *ccipdata.CommitStoreReport, epochAndRound *types.ReportTimestamp) {
I think accepting structs is better here, with pointers we risk report.TokenPrices panicking

2023-11-08 19:35 UTC, connorwstein commented on core/services/synchronization/telem/telem_ccip.proto
> +message CCIPExecutionReportSummary {
any reason we chose report info instead of observation information? I'd imagine observation information is more helpful for debugging

2023-11-08 19:35 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	r.telemetryCollector.ReportCommit(&report, &epochAndRound)
is this a blocking call or async? If its async lets add a comment, if its blocking we may need to make it async here

2023-11-08 22:24 UTC, sirenko commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin_test.go
> +	// me := genMonitoringEndpoint(t)
Cleaned it out.

2023-11-08 22:31 UTC, sirenko commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	r.telemetryCollector.ReportCommit(&report, &epochAndRound)
It's async. 
Comments were added.

2023-11-08 22:31 UTC, sirenko commented on core/services/ocr2/plugins/ccip/telemetry_collector.go
> +func (tc *telemetryCollector) ReportCommit(report *ccipdata.CommitStoreReport, epochAndRound *types.ReportTimestamp) {
Done.

2023-11-08 22:31 UTC, sirenko commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	telemetryCollector *telemetryCollector
(copilot magic) Fixed.

2023-11-09 06:03 UTC, sirenko commented on core/services/synchronization/telem/telem_ccip.proto
> +message CCIPExecutionReportSummary {
Added observation telemetry to execution and commit phases.

2023-11-13 07:11 UTC, sirenko commented
Stashing for now. See [CCIP-1174](https://smartcontract-it.atlassian.net/browse/CCIP-1174?focusedCommentId=176897) for more details.

2023-11-13 07:11 UTC, closed without merging