Remove duplicated logic in loaders
smartcontractkit/ccip pull request #243
Opened 2023-10-30 17:27 UTC by jarnaud

## Motivation

We have a responsibilities and code duplication between `loaders.go` and `onramp_reader.go` , `offramp_reader.go` and `commit_store_reader.go`

(see https://github.com/smartcontractkit/ccip/blob/ccip-develop/core/services/ocr2/plugins/ccip/internal/contractutil/loaders.go)

## Solution

- get rid of all LoadXXX functions from the loaders.go (probably entire file can be removed) and replace it with NewXXXReader
- move mocks to their own package (`ccipdata/mocks`) to avoid CodeCov complaining about mocks being not covered.

## Prerequisite

This PR builds on top of the change described in CCIP-1204 (PR: https://github.com/smartcontractkit/ccip/pull/241)

2023-10-31 11:16 UTC, mateusz-sekara requested changes

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_plugin.go
> +func getDestChain(spec *job.OCR2OracleSpec, chainSet evm.LegacyChainContainer) (evm.Chain, error) {
It's used by both exec and commit plugin so it shouldn't be there. At this moment we have a single package for both plugins, but eventually we want to keep them separate.  Maybe it could be part of ccip/config package

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +	destChain, err := getDestChain(spec, chainSet)
:+1: for extracting that

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +	destChain, err := getDestChain(spec, chainSet)
:+1: for extracting that

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +	destChain, err := getDestChain(spec, chainSet)
Food for thought, but I see that `destChain.ID().Int64()` is used very often, maybe it's worth to return that value from the `getDestChain`, for instance:

```go
func getDestChain(spec *job.OCR2OracleSpec, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {}
```

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +		return nil, nil, errors.Wrap(err, "Could not get commitStore static config")
I think that error messages in Go start with lower case

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +		return nil, nil, errors.Wrap(err, "Could not get commitStore static config")
Probably previous error message was good enough, no?

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +		offRampAddr, err := r.config.offRampReader.GetOffRampAddress()
We can probably fetch offRampAddr once before the loop starts, right? It seems not to change during iteration

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin_test.go
> +			offRampReader:     offRampReader,
Let's keep the previous naming and prefix mocks with `mock`, in this case it would be `mockOffRampReader`

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin_test.go
> +			// Mock calls to reader.
This comment is not needed I believe, especially if you rename the variable

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_v1_0_0.go
> +	if c.commitStore == nil {
Is it possible to have a `CommitStoreReader` without `commitStore` initialized? I think this check is not used in other functions

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_v1_2_0.go
> +	if c.commitStore == nil {
Same, `commitStore` being nil is probably some dev bug and scenario from which it would be very hard to recover

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		return *new(uint8), err
You can return `0, err` I believe

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		return *new(uint64), err
I think returning 0 together with error is good enough, no need to call `*new(primitive)`

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/onramp_v1_2_0.go
> +	if o.onRamp == nil {
I think these checks don't give us much value, OnRampReader can't be nil and if needed should be verified during construction

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/observability/offramp.go
> +func (o *ObservedOffRampReader) GetOffRampAddress() (common.Address, error) {
Cool, I think we might need similar updates in observability?commit_store and observability/onramp, right?

2023-10-31 11:16 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_reader.go
> +	GetOffRampAddress() (common.Address, error)
Doesn't it return the same value as `Address() common.Address` function which is already present there?

2023-10-31 11:25 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +		return nil, nil, errors.Wrap(err, "Could not get commitStore static config")
Ah thanks for the tip, I used to write error msg with uppercase. Changed it for consistency, but I will revert to the previous state.

2023-10-31 13:07 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/execution_plugin.go
> +func getDestChain(spec *job.OCR2OracleSpec, chainSet evm.LegacyChainContainer) (evm.Chain, error) {
Moving the function to its own file.

2023-10-31 13:09 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +	destChain, err := getDestChain(spec, chainSet)
Good idea, adding the chain id in return

2023-10-31 13:28 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_v1_2_0.go
> +	if c.commitStore == nil {
Feels like opening a potential gap, but the NewX() method check the commitStore value indeed.

2023-11-01 10:42 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_reader.go
> +	GetOffRampAddress() (common.Address, error)
Indeed, removing

2023-11-01 17:14 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/execution_plugin.go
> +	onRampAddress := common.HexToAddress(spec.ContractID)
this is the offRamp, not the onRamp. 
onRampAddress := offRampConfig.OnRamp

2023-11-03 15:07 UTC, dimkouv requested changes

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +		return *new(evm.Chain), 0, errors.New("chainID must be provided in relay config")
you can return `nil` instead of `*new(evm.Chain)`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func GetDestChain(spec *job.OCR2OracleSpec, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
I suggest renaming this to `GetChainFromSpec`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func GetChain(chainSelector uint64, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
And this one rename to `GetChainByChainSelector` and swap the order of the params to accept the `chainSet` as first param in both

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func GetDestChain(spec *job.OCR2OracleSpec, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
and then the comment might not even be needed

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func getChainInChainset(chainId uint64, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
and rename this one to `GetChainByChainID`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func getChainInChainset(chainId uint64, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
OR maybe create a wrapper for chainSet and add methods

```
chainSet.GetChainByID
chainSet.GetChainByChainSelector
chainSet.GetChainFromSpec
...
```

up to you

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +	staticConfig, err := ccipdata.FetchCommitStoreStaticConfig(commitStoreAddress, destChain.Client())
We will have to refactor this soon if we keep it like this.
The problem is the `destChain.Client()` which is evm specific.
Ideally we want to make this logic abstract.

---

to give you an idea

Eventually we will have a single parameter, a `ServiceProvider`:
```
type ServiceProvider interface {
    NewServiceX() (X, error)
    NewServiceY()  (Y, error)
}

func jobSpecToCommitPlugin(s ServiceProvider) {
    ....
}
```

So you need to have some kind of `CommitStoreConfigFetcher`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/execution_plugin.go
> +		return nil, nil, errors.Wrap(err, "Could not get offRamp static config")
error should not start with uppercase

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/execution_plugin.go
> +		return nil, nil, errors.Wrap(err, "Could not get offRamp static config")
and i suggest not using `could not do this..` `error fetching that....` etc
a simple message `get offramp static config` should be fine, since we know that this is an error

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/execution_plugin.go
> +	commitStoreReader = observability.NewObservedCommitStoreReader(commitStoreReader, destChainId, ExecPluginLabel)
NIT: in go it's preferred `destChainId` -> `destChainID`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_reader.go
> +	GetCommitStoreStaticConfig() (commit_store.CommitStoreStaticConfig, error)
Important: we don't want to have types from gethwrappers in `ccipdata`. We should define specific types under `ccipdata` and map the types accordingly.

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_reader.go
> +	GetCommitStoreStaticConfig() (commit_store.CommitStoreStaticConfig, error)
all methods should accept a context as first arg, and context should be passed in `bind.CallOpts`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_v1_0_0.go
> +	legacyConfig, err := c.commitStore.GetStaticConfig(&bind.CallOpts{})
use context here

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_v1_0_0.go
> +		return *new(commit_store.CommitStoreStaticConfig), errors.New("Could not get commitStore static config")
always return nil instead of `*new()`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_reader.go
> +	GetOffRampStaticConfig(opts *bind.CallOpts) (evm_2_evm_offramp.EVM2EVMOffRampStaticConfig, error)
pass `context` not bind.CallOpts

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_reader.go
> +	GetOffRampStaticConfig(opts *bind.CallOpts) (evm_2_evm_offramp.EVM2EVMOffRampStaticConfig, error)
please also refactor the other methods, i think it makes sense to do so in this PR

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		return *new(evm_2_evm_offramp.EVM2EVMOffRampStaticConfig), fmt.Errorf("offramp not initialized")
nil

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		return *new(evm_2_evm_offramp.EVM2EVMOffRampStaticConfig), fmt.Errorf("error while retrieving offramp config: %v", err)
nil

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		return *new(evm_2_evm_offramp.EVM2EVMOffRampStaticConfig), fmt.Errorf("error while retrieving offramp config: %v", err)
use `fmt.Errorf("retrieve offramp config: %w", err)`
using `%w` gives the flexibility of searching for errors with `errors.Is`

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/onramp_reader.go
> +	GetOnRampDynamicConfig() (evm_2_evm_onramp.EVM2EVMOnRampDynamicConfig, error)
should not return `gethwrappers` specific types. (i added a similar comment)

2023-11-03 15:07 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/onramp_reader.go
> +	GetOnRampDynamicConfig() (evm_2_evm_onramp.EVM2EVMOnRampDynamicConfig, error)
I suggest renaming
`GetOnRampAddress` -> `Address`
and
`GetOnRampDynamicConfig` -> `GetDynamicConfig`

it should be self-explanatory that they return onRamp specific details

2023-11-03 15:12 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func getChainInChainset(chainId uint64, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
I would avoid another level of indirection just for that case

2023-11-03 15:21 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func getChainInChainset(chainId uint64, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
also renaming the parameter to `chainID` then

2023-11-03 16:50 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/execution_plugin.go
> +		return nil, nil, errors.Wrap(err, "Could not get offRamp static config")
I followed the pattern by Connor in the other msg, e.g.:
`return nil, nil, errors.Wrap(err, "could not load source registry")`

2023-11-06 09:39 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/commit_plugin.go
> +	staticConfig, err := ccipdata.FetchCommitStoreStaticConfig(commitStoreAddress, destChain.Client())
It should be part of another PR.

2023-11-06 11:10 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/onramp_v1_0_0.go
> +	if o.onRamp == nil {
If you remove this nil check then the function signature could be simplified to return only `common.Address`

2023-11-06 11:10 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/config/chain_config.go
> +func GetDestChain(spec *job.OCR2OracleSpec, chainSet evm.LegacyChainContainer) (evm.Chain, int64, error) {
Agree, whether it's dest or source chain depends on context, so it's rather `GetChainFromSpec`

2023-11-06 11:10 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/config/chain_config_test.go
> +func TestGetChainFromSpec_success(t *testing.T) {
If you have more than one similar test for a single function, I would suggest using a single function like this

```go
func TestGetChainFromSpec(t *testing.T) {
	testChainID := int64(1337)

	tests := []struct {
		name        string
		spec        job.OCR2OracleSpec
		expectedErr bool
	}{
		{
			name: "success",
			spec: job.OCR2OracleSpec{
				RelayConfig: job.JSONConfig{
					"chainID": testChainID,
				},
			},
		},
	}

	mockChain := evmORMMocks.NewChain(t)
	mockChain.On("ID").Return(big.NewInt(testChainID))

	mockChainSet := evmORMMocks.NewLegacyChainContainer(t)
	mockChainSet.On("Get", strconv.FormatInt(testChainID, 10)).Return(mockChain, nil)

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			chain, chainID, err := GetChainFromSpec(&tt.spec, mockChainSet)
			if tt.expectedErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
				require.Equal(t, mockChain, chain)
				require.Equal(t, testChainID, chainID)
			}
		})
	}
}
```

2023-11-06 13:45 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/onramp_v1_0_0.go
> +	if o.onRamp == nil {
mmm this code is outdated, it has already been changed

2023-11-07 09:40 UTC, dimkouv approved these changes

2023-11-07 11:02 UTC, mateusz-sekara approved these changes

2023-11-07 11:04 UTC, dimkouv approved these changes

2023-11-07 11:05 UTC, merged