Monitor USDC Attestation API
smartcontractkit/ccip pull request #277
Opened 2023-11-09 17:46 UTC by jarnaud

## Motivation

We should add observability to track:

- the number of RPS we fire towards attestation API
- the duration of the attestation queries (millis)
- the error rate (success/failure)
- (opt) catching 429 error codes in case of actually being rate-limited?

## Solution

This should give us better visibility on this non-deterministic part of the system. 
Prometheus's Histogram should be enough for that.

2023-11-13 10:57 UTC, mateusz-sekara requested changes

2023-11-13 10:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/observability/usdc.go
> +func (o *ObservedUSDCTokenDataReader) ReadTokenData(ctx context.Context, msg internal.EVM2EVMOnRampCCIPSendRequestedWithMeta) ([]byte, error) {
Hmm, we don't need that level of granularity, do we? IIUC `ReadTokenData` calls Attestation API (which is already covered) and the DB (also already covered)

2023-11-13 10:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/observability/usdc.go
> +	}, []string{"plugin", "function", "status", "success"})
This is a bit of YAGNI in this case. We use Attestation API only from the exec plugin and I believe it's not gonna change anytime soon, so probably no need to add that. I also don't see much value in `function` label here, `GetWithTimeout` and `Get` are basically the same, the only difference is the applied timeout, I think would merge these metrics together and get rid of `function`

2023-11-13 10:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/usdc/http_client.go
> +func (s *HttpClient) Get(ctx context.Context, url string) ([]byte, int, error) {
This is not used, as we always rely on `GetWithTimeout`. I think interface will be cleaner if we have only `Get` function which accepts optional `timeout`

2023-11-13 11:12 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/tokendata/observability/usdc.go
> +func (o *ObservedUSDCTokenDataReader) ReadTokenData(ctx context.Context, msg internal.EVM2EVMOnRampCCIPSendRequestedWithMeta) ([]byte, error) {
I'm assuming it could be useful for monitoring if we have a delta between the token data reader and the client for example?

2023-11-13 11:30 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/observability/usdc.go
> +func (o *ObservedUSDCTokenDataReader) ReadTokenData(ctx context.Context, msg internal.EVM2EVMOnRampCCIPSendRequestedWithMeta) ([]byte, error) {
Why? `ReadTokenData` does the following:
* read database
* do some in-memory operations
* call API
As long as it's simple, we don't need that metric. Maybe once we introduce more `ReadTokenData` implementations. I would say that there are more places that require more in-depth monitoring than this :D

2023-11-13 12:29 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/tokendata/observability/usdc.go
> +	}, []string{"plugin", "function", "status", "success"})
Ok, it will simplify tests as well.

2023-11-13 12:30 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/tokendata/usdc/http_client.go
> +func (s *HttpClient) Get(ctx context.Context, url string) ([]byte, int, error) {
Indeed, kept that as a cleaning task.

2023-11-14 07:48 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/observability/http_client.go
> +func NewObservedIHttpClient(origin usdc.IHttpClient, pluginName string) *ObservedIHttpClient {
`NewObservedIHttpClient` is not used, I think we should inject that into the TokenDataReader, no?

2023-11-14 07:48 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/observability/http_client.go
> +func NewObservedIHttpClient(origin usdc.IHttpClient, pluginName string) *ObservedIHttpClient {
I believe `pluginName` is not needed at this moment. Also it would be easier to construct that in the `TokenReader` without pluginName.

2023-11-14 07:48 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/usdc/usdc.go
> +		httpClient:            &HttpClient{},
`NewObservedIHttpClient()` probably

2023-11-14 07:48 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/observability/http_client.go
> +	latencyBuckets = []float64{
At this moment timeout is set to `5s` so I recommend adding two more buckets to the metrics. For instance `3s, 4s, 5s`

2023-11-14 09:18 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/tokendata/usdc/usdc.go
> +		httpClient:            &HttpClient{},
We cannot introduce a circular dependency between usdc and observed, but I can add a parameter and make the default constructor more explicit.

2023-11-14 09:19 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/tokendata/observability/http_client.go
> +func NewObservedIHttpClient(origin usdc.IHttpClient, pluginName string) *ObservedIHttpClient {
Removing `pluginName`

2023-11-14 11:21 UTC, mateusz-sekara approved these changes

2023-11-14 11:21 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/tokendata/http/observed_http_client.go
> +type MetricDetails struct {
I think this struct is not needed, you can have `*prometheus.HistogramVec` directly under `ObservedIHttpClient`

2023-11-14 11:38 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/tokendata/usdc/usdc.go
> +		httpClient:            &HttpClient{},
Actually moving the http client to its own package.

2023-11-14 11:43 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/tokendata/http/observed_http_client.go
> +type MetricDetails struct {
Removed MetricDetails

2023-11-14 11:50 UTC, merged