CCIP-1184 Reduce number of logs to be scanned when checking for cache staleness
smartcontractkit/ccip pull request #287
Opened 2023-11-15 12:12 UTC by mateusz-sekara

## Motivation

## Solution

2023-11-15 18:05 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +	currentBlockNumber, err := c.logPoller.LatestBlockByEventSigsAddrsWithConfs(
`latestBlock` and `currentBlockNumber` sound similar, i suggest renaming

2023-11-15 18:05 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +		// Intentionally ignore the error here
maybe we want to log the error?

2023-11-15 18:05 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +func (c *CachedChain[T]) maybeCacheLatestFinalizedBlock(block logpoller.LogPollerBlock) {
`maybe` seems confusing since we always set a value
you can make it a bit more self-explanatory and lock-efficient and rename?
```
// will set latest changed block only if the provided block is greater than the cached value
setLatestChangedBlock(...) {
	if block.Finalizednum >  c.lastChangeBlock {
	   c.lastChangeBlock = block.FinalizedNum
	}
```

2023-11-15 18:05 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +		// Pick whichever is higher
i suggest updating the comment, since it's self explanatory that max, will pick the higher.

maybe explain why we pass the block number

```
// the block number that we pass is marked as the latest block number that an event 
was found
// on the next run query starts looking from this block till the most recent one
```

2023-11-15 18:05 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +	defer c.maybeCacheLatestFinalizedBlock(latestBlock)
since in any case we update `c.lastChangeBlock` why not do it in one place?
i.e. remove that logic from `c.fetchFromOrigin`?
```
if currentBlockNumber > lastChangeBlock {
   results = c.fetchFromOrigin(ctx)
}

defer c.maybeCacheLatestFinalizedBlock(max(currentBlockNumber, latestBlock))
```

2023-11-16 07:48 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +	defer c.maybeCacheLatestFinalizedBlock(latestBlock)
It's not that simple, because we need update cache value together with the latest block. It has to be atomic and done within a single locking. Otherwise, it might lead to race conditions between routines. The only simplification that comes to my mind at this moment is sth like this

```go
if currentBlockNumber > lastChangeBlock {
   results = c.fetchFromOrigin(ctx)
   cached := false
} else {
  results = c.fetchFromCache()
  cached := true
}

defer c.maybeCache(results, block, cached)
return results
```

There will be one entry point for in-memory caching, but the code will be probably less understandable

2023-11-16 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +		// Intentionally ignore the error here
`cache` doesn't have access to lggr, not sure if it would give us much value tbh

2023-11-16 11:19 UTC, dimkouv requested changes

2023-11-16 11:19 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +		if value, err1 := c.origin.CallOrigin(ctx); err != nil {
you are checking `err` not `err1`

2023-11-16 11:19 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +			c.updateCache(value, chainLastChangeBlock)
`else` not required

2023-11-16 11:19 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +			c.updateCache(value, chainLastChangeBlock)
you can do `value, err := c.origin.CallOrigin(ctx)` out of the if

2023-11-16 11:56 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +		if value, err1 := c.origin.CallOrigin(ctx); err != nil {
Nice, this should be caught be linter :D

2023-11-16 11:58 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +			c.updateCache(value, chainLastChangeBlock)
I can't just remove else when using ;ok pattern. I think there are two ways of doing that. Not sure which is better/cleaner tbh. I think we don't have a clear rules on which one to follow 

```go
if value, err1 := c.origin.CallOrigin(ctx); err1 != nil {
			return err1
		} else {
			c.updateCache(value, chainLastChangeBlock)
		}
```

or
```go
value, err! := := c.origin.CallOrigin(ctx);
if err1 != nil {
   return err1
}
return c.updateCache(value, chainLastChangeBlock)
```

2023-11-16 12:02 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +		if value, err1 := c.origin.CallOrigin(ctx); err != nil {
I'm gonna add a test for that

2023-11-16 14:23 UTC, dimkouv approved these changes

2023-11-16 21:54 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +func (c *CachedChain[T]) maybeCacheLatestFinalizedBlock(cachedLastBlock int64, lastBlock logpoller.LogPollerBlock) {
whole block not needed here, can just pass the last finalized block number

2023-11-16 21:54 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +	// We can update lastChangeBloWe use finalizedBlock for that to prevent missing data when chain is reorganized.
typo - also could be more clear, the reason it prevents large db scans is because we keep updating the lower bound of our search query

2023-11-16 21:54 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +	// Ordering matters here, we need to fetch latestBlock, before we fetch logs.
hmm can you elabourate on the specific edge case? On a likely related note, I think it'd be much safer/easier to follow if we just use logpoller.Finalized instead of optimistic confs for LatestBlockByEventSigsAddrsWithConfs. Means we react a little slower to adding a new token but thats totally fine

2023-11-17 09:30 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/cache.go
> +	// Ordering matters here, we need to fetch latestBlock, before we fetch logs.
I made the comment more specific explaining the edge case scenario I had in mind. Also, I got rid of `optimisticUpdates`, we rely on finality here

2023-11-20 22:13 UTC, connorwstein approved these changes

2023-11-21 07:56 UTC, merged