offchain - move caching logic behind reader interfaces
smartcontractkit/ccip pull request #297
Opened 2023-11-17 11:17 UTC by dimkouv

Currently the plugins are calling both the `cache` and the `readers` packages.
Also the cache calls the readers package:

```mermaid
graph LR
    A{Plugin} -- calls --> B{Cache}
    A -- calls --> C{Readers}
    B -- calls --> C
```

The idea is to simplify the architecture so that it eventually looks like this:

```mermaid
graph LR
	A{Plugin} -- calls --> B{Readers}
    B -- calls --> C{Cache}
```

That way the caching complexity is removed from the plugin code and abstracted away behind readers.
To achieve this architecture we have to also make the `Readers` to call the `Cache` and not vice versa as it is now.

Changes:

- Removed cache instances from both plugins
- Simplified the cache to not be responsible for calling the 'origin' on expiration.
- Removed several methods from the reader packages which were only used by the cache and replaced some of them with new ones.
- Simplified the plugin logic to not treat the `decimals` map as the source of truth for the supported tokens.
- Removed embedded internal caches inside the `cache` package (e.g. for keeping the decimals).

2023-11-20 14:38 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +// TODO: batched calls
followup

2023-11-21 20:37 UTC, connorwstein requested changes

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/price_registry_v1_0_0.go
> +func NewPriceRegistryV1_0_0(lggr logger.Logger, priceRegistryAddr common.Address, lp logpoller.LogPoller, ec client.Client, sourceFinality int64) (*PriceRegistryV1_0_0, error) {
sourceFinality is unused

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipcalc/slice.go
> +func FlattenUniqueSlice[T comparable](slices ...[]T) []T {
not really a ccip specific calculation, I think better as part of ccipcommon

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_reader.go
> -	// TODO Needed for caching, maybe caching should move behind the readers?
🥳

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		// that way the scanning window is shorter in the next run
this looks incorrect to me - in https://github.com/smartcontractkit/ccip/pull/287, we keep updating the lastChangeBlock to the latest _finalized_ block number in the steady state where there are no new events. Here newEventBlockNum returned from hasExpired will be just the latest unfinalized block if there are no new events?

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +			if destToken, isAddr := v.(common.Address); isAddr {
should never be not an address right? lets log an error if so

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/price_registry_reader.go
>  	FeeTokenEvents() []common.Hash
shouldnt be needed now that caches are inside. Looks like its used in one test still, we should adjust that test and remove it

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +			destTokens[i] = destTokensFromRpc[j]
it looks like BatchCall will always return responses in order of the requests, lets document that in the BatchCall interface though as we now rely on it externally here

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
>  func (o *OffRampV1_0_0) TokenEvents() []common.Hash {
can remove now

2023-11-21 20:37 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +			[]common.Hash{
could put it into a local variable tokenEvents then re-use in these 3 spots

2023-11-22 10:57 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		// that way the scanning window is shorter in the next run
https://github.com/smartcontractkit/ccip/pull/297/commits/9c255583888c23101b8448a43ba4b464743060f3

2023-11-22 15:57 UTC, mateusz-sekara requested changes

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) set(_ context.Context, value T, blockNum int64) bool {
`bool` return value is ignored for all invocations, probably we can just remove that

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +	latestBlock, err := c.logPoller.LatestBlock(pg.WithParentCtx(ctx))
The previous version has a detailed comment about the importance of ordering of these operations. It's hard to simulate that in tests so I would keep that comment (adjust to the new version if needed)
```
// Ordering matters here, we need to do operations in the following order:
	// * get LatestBlock
	// * get LatestBlockByEventSigsAddrsWithConfs
	// * fetch data from Origin
	// It's because LogPoller keep progressing in the background, and we want to prevent missing data.
	// If we do it in the opposite order, we might store in cache block that after logs that
	// were not scanned by LatestBlockByEventSigsAddrsWithConfs. And therefore ignore them and not update the cache.
	// (this will ignore logs produced between LatestBlockByEventSigsAddrsWithConfs and LatestBlock calls).
	// Calling LatestBlock first gives us guarantee that we never miss anything.
```

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		c.lastChangeBlock,
Bug, accessing shared data without mutex acquired

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		[]common.Address{c.address},
Nit, but it could be packed into a slice on the constructor level

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		latestBlockNumber = latestBlock.FinalizedBlockNumber
I would keep the comment about this being a perf improvement. Otherwise, it might be super weird for the person new to the codebase

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +	if blockOfLatestEvent > latestBlockNumber {
nit, but this `if` can be simplified as just using`math.max(blockOfLatestEvent, latestBlockNumber)`, no? One line instead of three, but still quite understandable

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) Get(ctx context.Context, syncFunc func(ctx context.Context) (T, error)) (T, error) {
Out of curiosity, why do we need so deep refactoring here? If I understand correctly the only difference between the old and the new implementation is that `CallOrigin` instead of being part of the implementation is passed as a lambda. Asking, because multithreading is always tricky and previous version was already battle-tested

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	eg.Go(func() error {
This is a candidate for batching, isn't it?

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +func FlattenUniqueSlice[T comparable](slices ...[]T) []T {
Could be simplified a lot with new `Set` thing, right?

2023-11-22 15:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/observability/offramp.go
> -func (o *ObservedOffRampReader) GetPoolByDestToken(ctx context.Context, address common.Address) (common.Address, error) {
I think you need to add observability to the new methods instead of just removing previous ones

2023-11-23 10:39 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		[]common.Address{c.address},
I prefer to not keep it as a slice, since it's always going to be one element.

2023-11-23 10:45 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +	if blockOfLatestEvent > latestBlockNumber {
IMO it's cleaner this way

2023-11-23 10:46 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) Get(ctx context.Context, syncFunc func(ctx context.Context) (T, error)) (T, error) {
it's actually the same :S
i copied most of the logic from the existing one

2023-11-23 10:47 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	eg.Go(func() error {
yeah, i added a comment about using batch call as a followup

2023-11-23 10:47 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +func FlattenUniqueSlice[T comparable](slices ...[]T) []T {
no because the set is unordered

2023-11-28 15:21 UTC, makramkd reviewed
Mostly minor comments, I like the cleaner organization :-)

2023-11-28 15:21 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +	supportedTokensCache    cache.AutoSync[[]common.Address] // source tokens
Naming nit: why not `sourceTokensCache`?

2023-11-28 15:21 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		if v, exists := o.sourceToDestTokensCache.Load(tokenAddress); exists {
Does this cache not need to get expired at some frequency? Or can we keep them in this cache forever?

2023-11-28 15:21 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +	sourceToDestTokensCache sync.Map
Whats the reason for not using `cache.AutoSync` here?

2023-11-28 15:21 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/ccipdata/price_registry_v1_0_0.go
> +	tokenDecimalsCache sync.Map
Similar Q here, why not use `cache.AutoSync`

2023-11-28 15:21 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +	latestBlockNumber := int64(0)
Naming nit: calling this `latestFinalizedBlock` would make this code easier to read, right now it can be easy to interpret this as the latest _unfinalized_.

2023-11-28 17:09 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	destTokensDecimals, err := r.destPriceRegistryReader.GetTokensDecimals(ctx, destTokens)
We fetch tokenDecimals only to pass them to `calculateUSDPrice`. Maybe not a scope of this PR, but I believe it could be encapsulated within a single function and moved outside of the plugin logic (maybe part of PriceRegistry reader?)

for instance
```go
// usage
func (r *CommitReportingPlugin) generatePriceUpdate() {
     var destTokens []common.Address
     tokensPrices := calculateTokenPrices(destTokens)
    // sth
}
```

and then
```go
func calculateTokenPrices(tokens []common.Address) {
   rawTokenPrices := ...
   tokenDecimals := ...
   
   for i, token := range token {
		tokenPricesUSD[token] = calculateUsdPer1e18TokenAmount(rawTokenPricesUSD[token], destTokensDecimals[i])
	}
    return tokenPricesUSD
}```

2023-11-28 17:09 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +func FlattenUniqueSlice[T comparable](slices ...[]T) []T {
Then I think it's worth mentioning in the comment that `FlattenUniqueSlice` preserves ordering

2023-11-29 09:11 UTC, mateusz-sekara requested changes

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +// AutoSync IMPORTANT: Cache refresh relies on the events that are finalized. This introduces some delay between the event onchain occurrence
I feel this comment is true only for the implementation `LogpollerEventsBased`, not necessarily for the interface

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +type LogpollerEventsBased[T any] struct {
I kinda miss all the detailed comments that were present in a previous implementation. Did you intentionally remove them? Were they too detailed? 

Of course they require some rewording with the new implementation (previous version)
```go
// CachedChain represents caching on-chain calls based on the events read from logpoller.LogPoller.
// Instead of directly going to on-chain to fetch data, we start with checking logpoller.LogPoller events (database request).
// If we discover that change occurred since last update, we perform RPC to the chain using ContractOrigin.CallOrigin function.
// Purpose of this struct is handle common logic in a single place, you only need to override methods from ContractOrigin
// and Get function (behaving as orchestrator) will take care of the rest.
// IMPORTANT: Cache refresh relies on the events that are finalized. This introduces some delay between the event onchain occurrence
// and cache refreshing. This is intentional, because we want to prevent handling reorgs within the cache.
//
// That being said, adding caching layer to the new contract is as simple as:
// * implementing ContractOrigin interface
// * registering proper events in log poller
```

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) Get(ctx context.Context, syncFunc func(ctx context.Context) (T, error)) (T, error) {
In terms of black-box, it's the same, but when you take a closer look, the flow is different (code-wise), and some comments are missing.

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		c.set(ctx, latestValue, newEventBlockNum)
This is different compared to a previous implementation. If a new thread steps in (between syncFunc and c.set) and fetches a more recent value then you will still return a stale one, maybe it's not that critical, but it's a regression compared to a previous version. Is that intentional? 

The previous version works as follows:
* check if the cache has expired
* try updating the cache if expired
* **return value from cache** (you return value from origin)

This is why I suggested not rewriting the entire caching logic. It's easy to make a bug here, because there are some ordering critical parts. I think that the only change that the previous implementation requires is replacing `callOrigin` with the function that is passed as an argument.
If you feel like the cache requires major refactoring then I would suggest doing that as a separate PR to limit the scope of changes.

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	eg.Go(func() error {
Is that a regression compared to a previous version?

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/rpclib/evm.go
> +	// BatchCall executes all the provided EvmCall and returns the results in the same order
👍

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		c.set(ctx, latestValue, newEventBlockNum)
With the `syncFuncion` passed as argument it's actually easier to test, because you can pass one function that sleeps and another that return immediately and you will get stale results

2023-11-29 09:11 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) Get(ctx context.Context, syncFunc func(ctx context.Context) (T, error)) (T, error) {
Shouldn't `syncFunc func(ctx context.Context) (T, error)` be part of the constructor? With a signature like this, it's very easy to accidentally pass the wrong/different syncFunction with different `Get` calls for the same cache instance. I believe that syncFunction should remain the same during the entire cache lifecycle. Otherwise, it may become very tricky.

2023-11-29 16:12 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		if v, exists := o.sourceToDestTokensCache.Load(tokenAddress); exists {
I didn't touch this logic, it's supposed to not expire and contain the most recent state

2023-11-29 16:14 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +	sourceToDestTokensCache sync.Map
Because `cache.AutoSync` is a cache that expires when new logPoller events are seen.
For token decimals the decimals are not changing, same for source to dest tokens.
So there is no need to make a db query (logpoller) to determine if something is expired

2023-11-29 16:14 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/price_registry_v1_0_0.go
> +	tokenDecimalsCache sync.Map
replied above

2023-11-29 16:15 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin.go
> +	destTokensDecimals, err := r.destPriceRegistryReader.GetTokensDecimals(ctx, destTokens)
could be yeah, can you create a ticket for this?

2023-11-29 16:16 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +type LogpollerEventsBased[T any] struct {
Replaced because most parts were referring to the `origin` which does not exist now.

2023-11-30 06:45 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) Get(ctx context.Context, syncFunc func(ctx context.Context) (T, error)) (T, error) {
It cannot be part of the constructor because:

0. syncFunc is a closure
1. Arguments are not known during cache initilization
2. Making it part of the constructor would require passing Reader instances which would lead to import cycles (similar to the way it was before)

2023-11-30 06:52 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	eg.Go(func() error {
wdym

2023-11-30 06:58 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +type LogpollerEventsBased[T any] struct {
I usually try to avoid having long comments, it's a better approach to try having the code clean enough so others can go through the code rather than reading the comment.

2023-11-30 07:02 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +		c.set(ctx, latestValue, newEventBlockNum)
> This is different compared to a previous implementation. If a new thread steps in (between syncFunc and c.set) and fetches a more recent value then you will still return a stale one, maybe it's not that critical, but it's a regression compared to a previous version. Is that intentional?

Yes it's intentional, this way we make the code cleaner without dealing with complex locking.
For OCR2 rounds or any of our use-cases this should be 100% acceptable.

2023-12-04 12:26 UTC, mateusz-sekara reviewed
Looks good in general. Added minor comments related to the code style

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) get(_ context.Context) (T, int64, error) {
This never errs. No need to have `error` in the signature and pass context as an argument

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) get(_ context.Context) (T, int64, error) {
Similar case for `c.lastChangeBlock`, it's never used, no need to return it. 
Probably not gonna be used ever, but It's easy enough to add it later if required.

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +type LogpollerEventsBased[T any] struct {
I agree that code should speak for itself and should not require any comments ideally. However, I find this godoc valuable, explaining the entire meaning of the cache and the structure (how LogPoller is utilized and when/why it can be done this way). It's not that obvious based on the code when you read it for the first time.

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/autosync.go
> +func (c *LogpollerEventsBased[T]) set(_ context.Context, value T, blockNum int64) {
Don't pass context if it's not used. This is private function that is not exposed outside

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	eg.Go(func() error {
I was asking if we did it sequentially in a previous or in parallel. I've checked, it was sequential. Please create a ticket to add batching to that

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/price_registry_reader.go
> +	// TODO: consider moving this method to a different interface since it's not related to the price registry
Please let's track it in JIRA, not in code. TODO can stay, but please create a ticket for that

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0_test.go
> +	if rpcURL == "" {
Hmm, what's the point of this test? It's always skipped, I believe you used that for some kind of debugging, but probably should be removed now, right?

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		abihelpers.MustGetEventID("PoolAdded", abiOffRampV1_0_0),
This is duplicated, worth extracting to some variables like `ExecutionStateChangedEventV1_0_0`

```go
{
	Name:      logpoller.FilterName(EXEC_TOKEN_POOL_ADDED, addr.String()),
	EventSigs: []common.Hash{abihelpers.MustGetEventID("PoolAdded", abiOffRampV1_0_0)},
	Addresses: []common.Address{addr},
},
{
	Name:      logpoller.FilterName(EXEC_TOKEN_POOL_REMOVED, addr.String()),
	EventSigs: []common.Hash{abihelpers.MustGetEventID("PoolRemoved", abiOffRampV1_0_0)},
	Addresses: []common.Address{addr},
},
```

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		destinationTokensCache: cache.NewLogpollerEventsBased[[]common.Address](
Hmm, these caches are exactly the same but storing a bit different values. They are related to the offramp, rely on the same events (so they will refresh/expire together) and they are called sequentially in the exec plugin. 
I think that single cache for offramp tokens would be just simpler and require less code, for instance:

```go
cache.NewLogPollerEventsBased[OfframpTokens]

type OfframpTokens struct {
   sourceTokens []common.Address
   destTokens []common.Address
   destPool map[common.Address]common.Address
}

func syncFunc() {
     batch(
        offramp.getSupportedToken,
        offramp.getDestTokens,
       offramp.getPools
      )

```

* SourceTokens cache doesn't have to know about destTokens cache etc - it makes the interactions simpler and there are less coupling 
* You can batch all these calls under a single syncFunc

2023-12-04 12:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		destinationTokensCache: cache.NewLogpollerEventsBased[[]common.Address](
Just double-checking, but the previous implementation for destToken also relied upon `feetokenchange` event. I believe it's a part of the price registry now, right?

2023-12-04 12:45 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> +		destinationTokensCache: cache.NewLogpollerEventsBased[[]common.Address](
yes
```
feeTokensCache: cache.NewLogpollerEventsBased[[]common.Address](
			lp,
			[]common.Hash{feeTokenAdded, feeTokenRemoved},
			priceRegistryAddr,
		),
```

2023-12-04 13:10 UTC, mateusz-sekara approved these changes

2023-12-04 13:10 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_v1_0_0.go
> -	tokenEvents := []common.Hash{
Sorry, I wasn't clear enough in a previous comment I was thinking about the code above as well

```go
var (
	ExecutionStateChangedEventV1_0_0                    = abihelpers.MustGetEventID("ExecutionStateChanged", abiOffRampV1_0_0)
      PoolAddedEvent...
      PoolRemovedEvent...
)
filters := []logpoller.Filter{
		{
			Name:      logpoller.FilterName(EXEC_EXECUTION_STATE_CHANGES, addr.String()),
			EventSigs: []common.Hash{ExecutionStateChangedEventV1_0_0},
			Addresses: []common.Address{addr},
		},
		{
			Name:      logpoller.FilterName(EXEC_TOKEN_POOL_ADDED, addr.String()),
			EventSigs: []common.Hash{PoolAddedEventV1_0_0},
			Addresses: []common.Address{addr},
		},
		{
			Name:      logpoller.FilterName(EXEC_TOKEN_POOL_REMOVED, addr.String()),
			EventSigs: []common.Hash{PoolRemovedEventV1_0_0},
			Addresses: []common.Address{addr},
		},
	}
```

2023-12-04 16:30 UTC, connorwstein approved these changes

2023-12-04 16:30 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/ccipdata/offramp_reader_test.go
> -	destTokens, err := th.reader.GetDestinationTokensFromSourceTokens(ctx, tokens)
we can include coverage of the 2 new functions here GetSourceToDestTokensMapping GetDestinationTokenPools easily

2023-12-05 07:23 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	eg.Go(func() error {
that would be hard, it's not really supported (batching between different reader calls)

2023-12-05 08:30 UTC, merged