Bring back lint:ccip in precommit
smartcontractkit/ccip pull request #346
Opened 2023-12-03 21:03 UTC by matYang

## Motivation
Resurrecting `lint:ccip` in `make ccip-precommit`, which was removed in the previous merge from main. I'm not sure if that was done by mistake. 
Happy to drop this PR if it was intentional.

2023-12-04 11:24 UTC, mateusz-sekara approved these changes

2023-12-04 13:51 UTC, RensR requested changes
lint:ccip is just running solhint. It should be removed

2023-12-06 11:31 UTC, RensR approved these changes

2023-12-06 11:33 UTC, RensR commented on contracts/package.json
> +    "solhint": "solhint --ignore-path .solhintignore --max-warnings 404 \"./src/v0.8/ccip/**/*.sol\""
This is used by CI, let's not change this

2023-12-06 11:34 UTC, RensR requested changes
Currently it would change CI and it would allow 404 warnings in CCIP files

2023-12-12 22:57 UTC, matYang commented
changing this to a backlog item on reduce warnings from CCIP tests

2023-12-12 22:57 UTC, closed without merging