Version namespacing
smartcontractkit/ccip pull request #355
Opened 2023-12-06 16:14 UTC by jarnaud

## Motivation

Currently, all readers are in one big folder, we should group the chain contract readers into subfolders per version (1.0, 1.1, 1.2, 1.3)

## Solution

- This PR creates sub-packages for each version (`v1_X_0`).

- The versioned readers constructors are moved into a `readers` package to break circular dependencies between readers definitions and versioned implementations (this circular dependency was hidden because all files were in the same (`ccipdata`) package before).

2023-12-07 15:13 UTC, RensR commented
I still see a lot of cross-version imports, I assume this PR is simply moving files around and no changes, and then we do a follow up to remove 1.0/1.1 and fix the version imports?

2023-12-07 15:17 UTC, jarnaud commented
Yes, this change is about the packages layout and namespacing, no change in code itself.

2023-12-11 10:33 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_2_0/offramp.go
>  type ExecOnchainConfigV1_2_0 evm_2_evm_offramp.EVM2EVMOffRampDynamicConfig
I think there is no need to add 1_2_0 suffix to the struct name if you already have a package prefix. I'd personally remove all version suffixes in favor of packages

2023-12-11 10:47 UTC, mateusz-sekara requested changes
I would suggest skipping all the version suffixes, because the version is already present in the package name. It would make the code cleaner in my opinion.

2023-12-11 10:47 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_2_0/offramp.go
>  type ExecOnchainConfigV1_2_0 evm_2_evm_offramp.EVM2EVMOffRampDynamicConfig
I think there is no need to add 1_2_0 suffix to the struct name if you already have a package prefix. I'd personally remove all version suffixes in favor of packages

2023-12-11 10:47 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/price_registry.go
> +func ApplyPriceRegistryUpdateV1_0_0(t *testing.T, user *bind.TransactOpts, addr common.Address, ec client.Client, gasPrice []ccipdata.GasPrice, tokenPrices []ccipdata.TokenPrice) {
Remove suffix if the test is designed for 1.0.0 and don't use other versions

2023-12-11 10:47 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_reader_test.go
> +	ccipdata.AssertFilterRegistration(t, new(lpmocks.LogPoller), func(lp *lpmocks.LogPoller, addr common.Address) ccipdata.Closer {
Shouldn't that be in ccipdata_test instead?

2023-12-11 10:47 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/readers/commit_store.go
> +package readers
nit, but everything in ccipdate package seems to be related to readers. Maybe rename that package to `factory` as it only contains factory methods?

2023-12-11 10:47 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/offramp.go
> +	Lggr                    logger.Logger
Imo this is wrong. Some fields are exported and some not, it makes the code very brittle. Also making these public is just a workaround for moving different versions to different packages. I think it's used only in the V1.2.0, so in my opinion you should keep the fields private, but encapsulate them within v1.2.0 during construction

```go
func create1_2_0(ec, lggr, estimator) 
    parent := 1_0_0(ec, lggr, estimator)
    return 1_2_0{
        ec: ec,
        lggr: lggr,
        estimator: estimator,
        v1_0_0: parent
   }
```

2023-12-11 10:47 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +func LogsConfirmations(finalized bool) logpoller.Confirmations {
This is very generic and probably could go to some place with all the utils. Maybe `reader.go`?

2023-12-11 13:35 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_reader_test.go
> +	ccipdata.AssertFilterRegistration(t, new(lpmocks.LogPoller), func(lp *lpmocks.LogPoller, addr common.Address) ccipdata.Closer {
It seems that we cannot import functions declared in other test packages (only normal packages) from a test package. Therefore `v1_X_0_test` package won't be able to use ccipdata_test package. However it can import the normal package.
Please correct me if I missed something, as I would definitely prefer not having to put this function in ccipdata_test indeed.

2023-12-11 13:39 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_2_0/offramp.go
>  type ExecOnchainConfigV1_2_0 evm_2_evm_offramp.EVM2EVMOffRampDynamicConfig
Removed suffixes

2023-12-11 13:40 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/readers/commit_store.go
> +package readers
Renamed package to factory

2023-12-11 13:40 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +func LogsConfirmations(finalized bool) logpoller.Confirmations {
Indeed, moved to reader.go.

2023-12-11 13:55 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/offramp.go
> +	Lggr                    logger.Logger
Indeed it's cleaner that way.

2023-12-11 15:28 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_reader_test.go
> +	ccipdata.AssertFilterRegistration(t, new(lpmocks.LogPoller), func(lp *lpmocks.LogPoller, addr common.Address) ccipdata.Closer {
I think there is file `utils_test.go` which is scoped to `ccip_data`. Probably you could just move `AssertFilterRegistration` there and make it lowercase, right?

2023-12-11 15:38 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_reader_test.go
> +			want:      v1_2_0.CommitOffchainConfigV1_2_0{},
Remove suffix ;)

2023-12-11 15:38 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/factory/commit_store.go
> +	return v1_2_0.EncodeCommitReportV1_2_0(abihelpers.MustGetEventInputs(v1_0_0.ReportAccepted, commitStoreABI), report)
remove suffix

2023-12-11 15:38 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/price_registry_reader_test.go
> +	v1_0_0.ApplyPriceRegistryUpdateV1_0_0(t, user, addr, ec, gasPriceUpdatesBlock1, tokenPriceUpdatesBlock1)
remove suffix

2023-12-11 15:56 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/commit_store_reader_test.go
> +	ccipdata.AssertFilterRegistration(t, new(lpmocks.LogPoller), func(lp *lpmocks.LogPoller, addr common.Address) ccipdata.Closer {
The content of utils_test won't be accessible to subpackages.
After discussion we agreed to move its content to test_utils (normal package).

2023-12-11 16:44 UTC, mateusz-sekara approved these changes

2023-12-11 17:49 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin_test.go
> +		encodedReport, err := factory.EncodeCommitReport(report)
NIT: `factory.EncodeCommitStore` mm.. factory is responsible for encoding commit store seems a bit odd. Maybe it's just the naming

2023-12-11 17:49 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/price_registry.go
> +func ApplyPriceRegistryUpdate(t *testing.T, user *bind.TransactOpts, addr common.Address, ec client.Client, gasPrice []ccipdata.GasPrice, tokenPrices []ccipdata.TokenPrice) {
if it's only used in tests probably shouldn't be here

2023-12-12 09:42 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/commit_reporting_plugin_test.go
> +		encodedReport, err := factory.EncodeCommitReport(report)
Actually this method has a comment indicating that it should be removed. This is not the point of this PR but we will have to deprecate it soon.

2023-12-12 09:55 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/price_registry.go
> +func ApplyPriceRegistryUpdate(t *testing.T, user *bind.TransactOpts, addr common.Address, ec client.Client, gasPrice []ccipdata.GasPrice, tokenPrices []ccipdata.TokenPrice) {
It seems we have this method for each version, therefore it has to stay in the versioned packages. We could move it to another file however?

2023-12-12 11:52 UTC, dimkouv approved these changes
nice improvements!

2023-12-12 12:45 UTC, merged