Version compatibility tests
smartcontractkit/ccip pull request #388
Opened 2023-12-18 20:30 UTC by AnieeG

## Motivation

## Solution
Introduced two tests -

1. CCIP set up with DON including nodes integrated with different version of postgres (please refer to `integration-tests/ccip-tests/testconfig/tomls/db-compatibility.toml`)

2. CCIP set up with DON which starts all CL nodes with last ccip release, and then upgrades few of the nodes to recent `github-sha` under test. During the version upgrade the flow of ccip requests continues and the test verifies that pre/post upgrade whether all pending requests get delivered.
  - This test is currently skipped. Current version of gethwrappers generate 1.3 versioned contracts with which the last release of ccip is not compatible. Need to come up with a strategy to use specific compatible gethwrappers with corresponding offchain version.

2023-12-18 22:43 UTC, tateexon approved these changes

2023-12-18 23:21 UTC, kalverra requested changes

2023-12-18 23:21 UTC, kalverra commented on .github/workflows/ccip-load-tests.yml
> +  ccip_version_compatibility_test:
nit: use `-` rather than `_` for separator for consistency

2023-12-18 23:21 UTC, kalverra commented on .github/workflows/integration-tests.yml
> +            os: ubuntu20.04-16cores-64GB
Is it possible to do this with a weaker runner?

2023-12-18 23:21 UTC, kalverra commented on integration-tests/ccip-tests/testconfig/global.go
> +		upgradeImage, _ := osutil.GetEnv(fmt.Sprintf("UPGRADE_IMAGE-%d", i+1))
Why bother with the section before the loop if you change it in here anyway?

2023-12-18 23:21 UTC, kalverra commented on integration-tests/ccip-tests/testsetups/test_env.go
> +func RestartNodes(
Should this be named something more specific to indicate it's only for image upgrades? Or can this be more general?

2023-12-18 23:23 UTC, AnieeG commented on integration-tests/ccip-tests/testconfig/global.go
> +		upgradeImage, _ := osutil.GetEnv(fmt.Sprintf("UPGRADE_IMAGE-%d", i+1))
`c.Nodes` is not always provided. Mostly the tests use `c.Common`

2023-12-19 15:53 UTC, kalverra approved these changes

2023-12-19 20:44 UTC, merged