publish workflow to use reusable action
smartcontractkit/ccip pull request #392
Opened 2023-12-19 22:30 UTC by AnieeG

## Motivation

## Solution

2023-12-20 13:46 UTC, chainchad requested changes
Nice simplification but had some feedback/changes.

2023-12-20 13:46 UTC, chainchad commented on .github/workflows/publish.yml
>        - name: Generate Docker image version tag
I took a quick look at our recent [tags](https://github.com/smartcontractkit/ccip/tags) (going back a month or so ago) and it looks like we're not using semver build metadata (denoted by a `+` symbol in the tag) so I think we can remove this step entirely 👍

2023-12-20 13:46 UTC, chainchad commented on .github/workflows/publish.yml
> +          ecr-image-name: ${{ env.AWS_ECR_REPO_PUBLIC_REGISTRY }}/w0i8p0z9/chainlink-ccip
```suggestion
          ecr-image-name: w0i8p0z9/chainlink-ccip
```

2023-12-20 13:46 UTC, chainchad commented on .github/workflows/publish.yml
> +          git-commit-sha: ${{ steps.generate-docker-image-tag.outputs.tag }}
```suggestion
```
I'd remove this entirely, the default is fine. If we did want to use it, we could pass in a git shasum but we wouldn't use the tag here.

2023-12-20 13:46 UTC, chainchad commented on .github/workflows/publish.yml
> -      - name: Fetch operator-ui
Making sure that it's OK to remove this?

2023-12-20 15:35 UTC, momentmaker commented on .github/workflows/publish.yml
> +            ecr-image-name: ${{ secrets.AWS_ECR_REPO_URL }}
this would be the image name no?

2023-12-20 15:45 UTC, momentmaker commented on .github/workflows/publish.yml
> +          aws-role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_PROD_PUBLISH_ARN }}
@chainchad I think we need a new role for `sdlc` for this right?

2023-12-20 15:56 UTC, AnieeG commented on .github/workflows/publish.yml
> +            ecr-image-name: ${{ secrets.AWS_ECR_REPO_URL }}
With the previous docker_meta action this was used as image name-
```
  with:
          images: ${{ secrets.AWS_ECR_REPO_URL }}
```
Ported from that. Should I keep it blank ?

2023-12-20 16:17 UTC, AnieeG commented on .github/workflows/publish.yml
> +          aws-role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_PROD_PUBLISH_ARN }}
This is the image published to prod separate from the image built for QA ecr. Do we still need sdlc role?

2023-12-20 16:26 UTC, chainchad commented on .github/workflows/publish.yml
> +          aws-role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_PROD_PUBLISH_ARN }}
I think we can use the existing role in `secrets.AWS_OIDC_IAM_ROLE_PROD_PUBLISH_ARN` here.

2023-12-20 16:28 UTC, chainchad commented on .github/workflows/publish.yml
> +            ecr-image-name: ${{ secrets.AWS_ECR_REPO_URL }}
Should be the same as this [suggestion](https://github.com/smartcontractkit/ccip/pull/392/files#r1432732054), I think.

2023-12-20 19:50 UTC, AnieeG commented on .github/workflows/publish.yml
> -      - name: Fetch operator-ui
This is now built as part of `make generate `and committed to the repo. There is no need to build it again here

2023-12-20 19:53 UTC, chainchad requested changes

2023-12-20 19:53 UTC, chainchad commented on .github/workflows/publish.yml
> +            ecr-hostname: ${{ secrets.AWS_ECR_REPO_URL }}
```suggestion
            ecr-hostname: ${{ secrets.AWS_ECR_REPO_URL }}
            ecr-image-name: w0i8p0z9/chainlink-ccip
```

2023-12-20 20:10 UTC, chainchad commented on .github/workflows/publish.yml
> +            ecr-hostname: ${{ secrets.AWS_ECR_REPO_URL }}
We also need to potentially pass in the correct ecr-image-name.

2023-12-20 20:29 UTC, chainchad approved these changes

2023-12-20 20:42 UTC, momentmaker approved these changes

2023-12-21 11:52 UTC, mateusz-sekara commented on .github/workflows/publish.yml
> +      - "release/**"
Releng docs state that we should use `ccip-release/*` branch naming cc @chainchad

2023-12-21 15:15 UTC, RensR approved these changes

2023-12-21 15:16 UTC, merged

2023-12-21 18:26 UTC, chainchad commented on .github/workflows/publish.yml
> +      - "release/**"
Good point. Should we update our docs to match release/** instead? IIRC there was talk about migrating /ccip code back into the /chainlink repo which would have necessitated that ccip- prefix. But if that's not in the cards, maybe we use release/** and update the docs?

2023-12-22 09:06 UTC, mateusz-sekara commented on .github/workflows/publish.yml
> +      - "release/**"
I'm open to any solution as long as it's aligned with the docs and the current state. At this moment, we have all possible options in use 
<img width="325" alt="image" src="https://github.com/smartcontractkit/ccip/assets/18304098/48c4b857-66f4-44cc-8887-4ddc3d98edc4">

2023-12-22 16:31 UTC, chainchad commented on .github/workflows/publish.yml
> +      - "release/**"
Thanks, tagged you all in a separate PR to update the docs.