Don't fail when some token prices are missing
smartcontractkit/ccip pull request #401
Opened 2023-12-22 09:09 UTC by mateusz-sekara

## Motivation

## Solution

2023-12-22 09:43 UTC, makramkd commented
Two questions:
* Should this behavior be documented in the PriceGetter interface? If we don't error out here I expect us to follow similar behavior in e.g a price getter that uses Mercury/CCIP price serve.
* This is just for price updates right? Merkle roots will still be committed for CCIP sends that involve the token that has a missing price?

2023-12-22 09:46 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/pricegetter/pipeline.go
> +			d.lggr.Errorw("missing token from tokensForFeeCoin spec", "token", token.Hex())
In the plugin we have this check: https://github.com/smartcontractkit/ccip/blob/3c25ced34a096e75d1ad948dfc30972406bdc016/core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go#L222-L227.

Won't this error out in the plugin still?

2023-12-22 09:55 UTC, mateusz-sekara commented
> Two questions:
> 
> * Should this behavior be documented in the PriceGetter interface? If we don't error out here I expect us to follow similar behavior in e.g a price getter that uses Mercury/CCIP price serve.
Yes, it should be documented, as it's part of the contract. I'm gonna add that

> * This is just for price updates right? Merkle roots will still be committed for CCIP sends that involve the token that has a missing price?

Yes, just price updates. That means that if there is a drift between offramp's tokens and jobspec's tokens, the plugin will keep working and committing. Also, it will keep transmitting prices, but only for tokens that are found.

2023-12-22 09:59 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/pricegetter/pipeline.go
> +			d.lggr.Errorw("missing token from tokensForFeeCoin spec", "token", token.Hex())
Ah you are right. It seems that this check is duplicated - it's both present in the PriceGetter and CommitPlugin. Probably we should get rid of one and keep it only in one place. Maybe the CommitPlugin is the one to decide, not PriceGetter. What do you think @makramkd ?

2023-12-22 10:09 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/pricegetter/pipeline.go
> +			d.lggr.Errorw("missing token from tokensForFeeCoin spec", "token", token.Hex())
I think it makes more sense for the plugin itself to decide since the logic being there is more obvious and usually the first place to check, rather than hidden in the price getter, which feels non-intuitive.

However I think the price getter behavior has to change either way because right now as you noted it'll return `nil` if a single token is missing from the spec.

So maybe gather all the missing tokens in a single `error` and check `errors.Cause` or similar in the plugin?

One idea:

```golang
var ErrMissingToken = errors.New("missing token from tokensForFeeCoin spec")

// The mapping of token address to source of token price has to live offchain.
// Best we can do is sanity check that the token price spec covers all our desired execution token prices.
var errs error
for _, token := range tokens {
	if _, ok = tokenPrices[token]; !ok {
		errs = multierr.Append(errs, errors.Wrap(ErrMissingToken, token.Hex()))
	}
}

return tokenPrices, errs
```

2023-12-22 10:15 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/pricegetter/pipeline.go
> +			d.lggr.Errorw("missing token from tokensForFeeCoin spec", "token", token.Hex())
On the plugin side, maybe you can use `multierr.Every`:

```golang
rawTokenPricesUSD, err := r.priceGetter.TokenPricesUSD(ctx, queryTokens)
if !multierr.Every(err, pricegetter.ErrMissingToken) {
	return nil, nil, err
}
// at this point, if there is an error, its ErrMissingToken
lggr.Infow("Raw token prices", "rawTokenPrices", rawTokenPricesUSD, "err", err)
```

2023-12-22 10:32 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/pricegetter/pipeline.go
> +			d.lggr.Errorw("missing token from tokensForFeeCoin spec", "token", token.Hex())
Hmm, returning both value and error? Not sure about that approach, is the Go-way? I haven't seen that anywhere in our codebase. I would say that having dedicated errors and then handling them in the Commit makes code more complex than it is supposed to be. 

I think we either want to **be available** - execute as many tokens as we get from PriceGetter, no matter the reason, or **consistent** - fail immediately. `ErrMissingToken` is very custom to the underlying implementation and might not be a good fit for any other implementation (e.g. mercury, lambda, whatever).

If we want to make this interface more generic in this PR and I would suggest the following:
```go
type PriceGetter interface {
        // Must len([]TokenPriceResult) == len(tokens) 
	TokenPricesUSD(ctx context.Context, tokens []common.Address) ([]TokenPriceResult, error)
}

type TokenPriceResult struct {
	TokenAddress common.Address
	Price        *big.Int
	Error error
}
```

This is aligned with the Batching interface. It gives the client control over the returned data and visibility of which tokens failed to fetch. For instance plugin might want to fail when feetoken is missing, but continue when other ones are missing.

2023-12-22 11:01 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/pricegetter/pipeline.go
> +			d.lggr.Errorw("missing token from tokensForFeeCoin spec", "token", token.Hex())
Yeah, that looks good. Top-level error is fatal and each result may error. What I suggested was based off of not changing the interface but I think changing the interface itself in this case is justified.

2023-12-22 11:03 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/pricegetter/pipeline.go
> +			d.lggr.Errorw("missing token from tokensForFeeCoin spec", "token", token.Hex())
You can even add tests for all implementations of `PriceGetter` that assert: `if err == nil { assert.Equal(t, len(tokens), len(tokenPriceResults))` to keep all implementations honest.

2023-12-22 15:15 UTC, makramkd approved these changes
LGTM. Lets also make sure this is called out in the release notes for the next release so that everyone is aware 👍

2023-12-29 10:02 UTC, RensR requested changes
Requesting changes to make sure this isn't merged before more discussion. Maybe I missed where we decided this but I'm not fully convinced yet. 

Not starting on missing tokens was an intentional choice, as missing token prices are hard to spot otherwise. While prices are missing, sending the tokens that don't have prices will result in reverting txs on the sending side. 

We lose the invariant that if commit runs, we have all the prices, which I guess will be lost when we move to a dedicated pricing job as well.

2024-01-03 18:43 UTC, connorwstein requested changes

2024-01-03 18:43 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	// We don't want to fail in case of spotting missing token, but rather log it. This should make CCIP more resilient.
this is insufficient - there are checks in Report as well (see validateObservations) ensuring we have all the relevant prices. You'd have to remove that `len(destTokens) != len(obs.TokenPricesUSD) ` check and then ensure that calculatePriceUpdates only includes medians of token prices if there is >= f+1 observations of that token price. Has a small drawback that now the f value is scattered. Worth writing a test that covers the observe->report interaction I think.

2024-02-13 16:26 UTC, closed without merging