Weekly merge
smartcontractkit/ccip pull request #409
Opened 2024-01-05 22:56 UTC by connorwstein

## Motivation

## Solution

2024-01-05 22:58 UTC, connorwstein commented on core/chains/evm/logpoller/log_poller_test.go
> +	require.Error(t, commonutils.JustError(db.Exec(`invalid query`)))
Small change here

2024-01-05 22:58 UTC, connorwstein commented on core/chains/evm/logpoller/observability_test.go
> +	"github.com/smartcontractkit/chainlink/v2/core/chains/evm/utils"
Ditto

2024-01-05 22:58 UTC, connorwstein commented on integration-tests/types/config/node/core.go
> -	"github.com/smartcontractkit/chainlink/v2/core/utils/config"
@AnieeG would be good to double check this, was a conflict

2024-01-06 01:34 UTC, AnieeG commented on integration-tests/types/config/node/core.go
> -	"github.com/smartcontractkit/chainlink/v2/core/utils/config"
looks right.

2024-01-08 17:38 UTC, AnieeG commented on integration-tests/go.mod
> +module github.com/smartcontractkit/chainlink/integration-tests
we need to change it back to `ccip`.

2024-01-08 17:39 UTC, AnieeG commented on integration-tests/go.mod
> -	github.com/smartcontractkit/chainlink/integration-tests => ../integration-tests
This is required as well

2024-01-08 17:40 UTC, AnieeG requested changes
`integration-tests/go.mod` needs changes

2024-01-08 17:53 UTC, AnieeG approved these changes

2024-01-09 11:40 UTC, makramkd approved these changes

2024-01-09 13:59 UTC, RensR approved these changes

2024-01-09 14:11 UTC, merged