Weekly merge 2
smartcontractkit/ccip pull request #433
Opened 2024-01-12 16:16 UTC by dimkouv

## Motivation

## Solution

2024-01-12 20:48 UTC, AnieeG requested changes, later dismissed

2024-01-12 20:48 UTC, AnieeG commented on integration-tests/go.mod
> +module github.com/smartcontractkit/chainlink/integration-tests
This should be github.com/smartcontractkit/ccip/integration-tests

2024-01-12 20:48 UTC, AnieeG commented on integration-tests/go.mod
> -	k8s.io/apimachinery => k8s.io/apimachinery v0.25.11
This is required

2024-01-17 10:59 UTC, makramkd commented
Looks good - can we squash the fix commits into 1?

2024-01-17 15:15 UTC, makramkd approved these changes

2024-01-17 17:16 UTC, RensR commented
still quite a few to be squashed

2024-01-18 10:43 UTC, RensR approved these changes

2024-01-18 10:43 UTC, merged