Price getter and pipeline
smartcontractkit/ccip pull request #470
Opened 2024-01-26 12:02 UTC by jarnaud

## Motivation

## Solution

2024-02-02 00:39 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/ocr2.go
> +	dynamicPriceGetter pricegetter.PriceGetter
should keep one of this

2024-02-02 00:59 UTC, dimkouv approved these changes

2024-02-03 05:39 UTC, dimkouv requested changes
LGTM, just fix the tests, nice work

2024-02-05 10:43 UTC, makramkd requested changes

2024-02-05 10:43 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		}
I think we saw an example where the source and dest chain clients are not sufficient for a particular lane (e.g the (WeMix <-> Kroma lanes that use an arbitrum feed, which is neither the source nor the dest chain).

2024-02-05 10:43 UTC, makramkd commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
Why is this a plain string and not a structure? You can define any structure you like and stick it in here. For an example, you can see https://github.com/smartcontractkit/ccip/blob/6d519493d34e3e742170df78de569b3dfddb0372/core/services/ocr2/plugins/rebalancer/models/config.go#L15.

The plugin config is specified in the job spec as TOML and not JSON - there is always a 1-1 mapping between these two formats. For example, I think you want something like this:

```toml
[pluginConfig.priceGetterConfig.aggregatorPrices.0x0820c05e1fba1244763a494a52272170c321cad3]
chainID = "1000"
contractAddress = "0xb8dabd288955d302d05ca6b011bb46dfa3ea7acf"

[pluginConfig.priceGetterConfig.aggregatorPrices.0x4a98bb4d65347016a7ab6f85bea24b129c9a1272]
chainID = "1337"
contractAddress = "0xb80244cc8b0bb18db071c150b36e9bcb8310b236"

[pluginConfig.priceGetterConfig.staticPrices.0xec8c353470ccaa4f43067fcde40558e084a12927]
chainID = "1057"
price = "1000000000000000000"
```

You can maybe make this more compact, IIRC you can put inline dictionaries in TOML but I can't remember offhand right now.

This suggests a Go structure of the following format:

```go
type AggregatorPrice struct {
	ContractAddress string
	ChainSelector uint64
}

type StaticPrices struct {
	Price *utils.Big
	ChainSelector uint64
}

type PriceGetterConfig struct {
	AggregatorPrices map[string]AggregatorPrice
	StaticPrices map[string]StaticPrice
}
```

Note the use of chain selectors instead of chain ID's and `string`s instead of `common.Address`. If we're not going to use chain selectors, then we should be more explicit and say `evmChainID` rather than plain `chainID`

2024-02-05 10:43 UTC, makramkd commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
cc @dimkouv in case there is a better way re: chain agnosticism.

2024-02-05 10:43 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/pricegetter/evm.go
> +const latestRoundDataMethodName = "latestRoundData"
Should assert that this method exists in an `init` function or similar. The ABI could change from underneath us.

```go
func init() {
	aggregatorABI, err := abi.JSON(strings.NewReader(offchainaggregator.OffchainAggregatorABI))
	if err != nil {
		panic(err)
	}
	method, ok := aggregatorABI.Methods[latestRoundDataMethod]
	if !ok {
		panic(fmt.Sprintf("latestRoundData method not found on abi: %+v", aggregatorABI.Methods))
	}
}
```

2024-02-05 10:43 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/pricegetter/evm.go
> +	Price   uint64 `json:"price,string"`
This should be `utils.Big`, prices can exceed 64 bits

2024-02-05 10:43 UTC, makramkd commented on core/services/ocr2/plugins/ccip/testhelpers/integration/jobspec.go
> +	// NB: make this test mandatory once we switch to dynamic price getter only.
Can create a ticket for these items, will get lost in a comment

2024-02-05 10:43 UTC, makramkd commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
Note that this approach is much easier on the eyes for reading a job spec, we could easily have a massive one-line JSON config that is hard to parse with just our eyes.

2024-02-05 10:44 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		}
I think you need to extract all the chain IDs specified in the dynamic price getter config and get all the clients for those.

2024-02-05 16:15 UTC, AnieeG approved these changes
The test changes look good to me

2024-02-05 17:26 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
I believe there are pros/cons here, agree that it's easier to read it with toml but I'm leaning towards the idea of having the config as json because it's just one key/val pair in the job spec and for me (that I don't read jobspecs at least) seems simpler.

2024-02-05 17:28 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		}
So for wemix<->kroma we fetch the price from a contract that lives on arbitrum?
if yes, why do we do that?

2024-02-05 17:34 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		}
Yes. We do that because there are no feeds on either WeMix or Kroma

2024-02-06 15:43 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/testhelpers/integration/jobspec.go
> +	// NB: make this test mandatory once we switch to dynamic price getter only.
Created follow-up ticket here: https://smartcontract-it.atlassian.net/browse/CCIP-1612

2024-02-06 15:43 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/pricegetter/evm.go
> +	Price   uint64 `json:"price,string"`
Changing `Price` type to bigInt.

2024-02-06 15:43 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/pricegetter/evm.go
> +const latestRoundDataMethodName = "latestRoundData"
Added init check

2024-02-06 15:44 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
I would definitely prefer keeping the JSON format for this entry, which is kind of complex and self-contained.
Also there are other exemples of suck JSON embedding in our codebase already.

2024-02-07 15:26 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		}
Indeed, verified the current job spec for Wemix->Kroma:
```
[pluginConfig]
tokenPricesUSDPipeline = """
// Token LINK
encode_call_token1_usd  [type=\"ethabiencode\" abi=\"latestRoundData()\"]

call_token1_usd [type=\"ethcall\"
evmChainId=42161
contract=\"0x86E53CF1B870786351Da77A57575e79CB55812CB\"
data=\"$(encode_call_token1_usd)\"]
...
```

Both calls are referencing chain 42161 which is Arbitrum One.

2024-02-07 15:41 UTC, makramkd commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
I would say reach out to EngOps and ask them - I think they wrote the tooling to go from RDD -> job spec and they probably read the job spec a lot?

2024-02-07 17:31 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
Jordan sent me an example of such configuration: https://github.com/smartcontractkit/chainlink/blob/develop/core/services/job/testdata/pretty.toml

2024-02-07 20:34 UTC, dimkouv approved these changes

2024-02-08 10:01 UTC, makramkd commented on core/services/ocr2/plugins/ccip/config/config.go
> +	PriceGetterConfig string `json:"priceGetterConfig"`
Multi-line strings in TOML - guess that makes things better!

2024-02-08 10:06 UTC, makramkd approved these changes

2024-02-08 10:06 UTC, makramkd commented on core/services/ocr2/plugins/ccip/clo_ccip_integration_test.go
> +	fmt.Printf("===>Running CLO flow with pipeline:\n%v\n===>price getter:\n'%v'\n===>chain ID: %v\n", tokenPricesUSDPipeline, priceGetterConfiguration, ccipTH.Source.ChainID)
Nit: Use `t.Log/t.Logf` for tests instead of `fmt.Printf`

2024-02-08 10:44 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/clo_ccip_integration_test.go
> +	fmt.Printf("===>Running CLO flow with pipeline:\n%v\n===>price getter:\n'%v'\n===>chain ID: %v\n", tokenPricesUSDPipeline, priceGetterConfiguration, ccipTH.Source.ChainID)
Actually this log should be removed

2024-02-08 11:14 UTC, RensR approved these changes

2024-02-08 14:27 UTC, merged