Log params before plugin init completes
smartcontractkit/ccip pull request #522
Opened 2024-02-17 20:21 UTC by matYang

## Motivation
If plugin init errors, e.g. due to misconfig, it's hard to debug because config is only logged at end of successful init.

## Solution

2024-02-19 08:59 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	lggr.Infow("Initializing commit plugin", "params", params)
I can't comment on the exact line, but should we pass `params`, or some subset thereof, to the `commitLggr` object intialization?

```
commitLggr := lggr.Named("CCIPCommit").With("sourceChain", sourceChainName, "destChain", destChainName, "initParams", params)
```

2024-02-19 08:59 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/initializers.go
> +	lggr.Infow("Initializing exec plugin", "params", params)
Ditto here re: params in the logger fields.

2024-02-22 07:02 UTC, makramkd approved these changes

2024-02-22 07:57 UTC, mateusz-sekara requested changes

2024-02-22 07:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	lggr.Infow("Initializing commit plugin", "params", params)
Sure about that? Adding that to the logger will print these params with every log emitted by the Commit plugin. 

```go
type jobSpecParams struct {
	pluginConfig         ccipconfig.CommitPluginJobSpecConfig
	commitStoreAddress   cciptypes.Address
	commitStoreStaticCfg commit_store.CommitStoreStaticConfig
	sourceChain          legacyevm.Chain
	destChain            legacyevm.Chain
}
```
source,dest chain will be duplicated
pluginConfig contains the entire price getter configuration (which is rather large on mainnet).

I think that the impact on the logs size might be huge, no? IIUC, @matYang intention is to log the entire config before init, because during misconfig plugin doesn't start. So what's the point of logging that config with every log from Commit?

2024-02-22 08:13 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	lggr.Infow("Initializing commit plugin", "params", params)
The more context we have in the log the better. Ideally we can selectively include as much context as we can that is useful when debugging issues. Perhaps everything in the plugin config except for the price configs (though that would be useful too in certain situations when debugging price update issues, however its probably not worth the impact on logs).

2024-02-22 08:19 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	lggr.Infow("Initializing commit plugin", "params", params)
Yeah, couldn't agree more, but we need to find some sweet spot between number of details and the cost of storing these logs. I don't know what would be the exact impact here and I don't know how to estimate that. It would be great to maybe discuss things like this with infra nops team. What is more, `jobSpecParams` is a struct of structs. I don't know how deep the logger goes when deserializing that. Probably worth testing how would that log will look like anyway.

2024-02-28 04:49 UTC, matYang commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	lggr.Infow("Initializing commit plugin", "params", params)
Tested it out today, indeed the logger cannot print nested structs. I flattened it out to key contract addresses.

2024-02-28 09:35 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		"DestChainSelector", params.commitStoreStaticCfg.ChainSelector)
@mateusz-sekara would you opposed to these fields being in the logger itself?

2024-02-28 09:52 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		"DestChainSelector", params.commitStoreStaticCfg.ChainSelector)
Do you mean moving these params to `lggr.With(...)`? We already have source/dest chain IDs in the logger. Still not sure what would be the point of logging CommitStore/OnRamp/ArmProxy addresses with every log message? Are there search use cases for that?

2024-02-28 11:18 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		"DestChainSelector", params.commitStoreStaticCfg.ChainSelector)
Search use cases no, but if you search for a particular msg and it shows up on multiple lanes, having this info there in the log without having to consult the monster that is RDD would be nice.

2024-02-28 11:19 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		"DestChainSelector", params.commitStoreStaticCfg.ChainSelector)
Anyway I don't feel to strongly about it, LGTM.

2024-02-28 12:13 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +		"DestChainSelector", params.commitStoreStaticCfg.ChainSelector)
>  but if you search for a particular msg and it shows up on multiple lanes

This is very unlikely when searching by msg id, not sure if I follow. What is more, you have a job name (which consists of source and dest chain names) in the log

2024-02-28 12:13 UTC, mateusz-sekara approved these changes

2024-02-28 15:47 UTC, merged