Detect onramp dynamic config changes
smartcontractkit/ccip pull request #544
Opened 2024-02-22 10:17 UTC by jarnaud

## Motivation

## Solution

2024-02-28 13:32 UTC, mateusz-sekara requested changes

2024-02-28 13:32 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	priceRegistryAddress, err := r.onRampReader.GetPriceRegistry()
Yeah, that could work, but we add an extra RPC call every OCR round. We are addressing an edge case here, the config will change probably once or twice, but we keep scanning blockchain every round. I'm thinking about reusing the existing caching mechanism here

First of all, you need to register proper filter in LogPoller in OnRampReader
```go
filters := []logpoller.Filter{
		{
			Name:      logpoller.FilterName(ccipdata.COMMIT_CCIP_SENDS, onRampAddress),
			EventSigs: []common.Hash{CCIPSendRequestEventSig},
			Addresses: []common.Address{onRampAddress},
		},
		{
			Name:      logpoller.FilterName("Dynamic config changed", onRampAddress),
			EventSigs: []common.Hash{abihelpers.MustGetEventID("ConfigSet", onRampABI)},
			Addresses: []common.Address{onRampAddress},
		},
	}
```

There is an even emitted by OnRamp
```solidity
  event ConfigSet(StaticConfig staticConfig, DynamicConfig dynamicConfig);
```

Then you need to init cache
```go
onrampConfigCache: cache.NewLogpollerEventsBased[cciptypes.Address](
	sourceLP,
	[]common.Hash{abihelpers.MustGetEventID("ConfigSet", onRampABI)},
	onRampAddress,
),
```

Then in `GetPriceRegistry` you could have
```go
func (o *OnRamp) GetPriceRegistry() (cciptypes.Address, error) {
	return o.onrampConfigCache.Get(ctx, func(ctx context.Context) (cciptypes.Address, error) {
		c, err := o.GetDynamicConfig()
		if err != nil {
			return "", err
		}
		return c.PriceRegistry, nil
	})
}
```

You can take a look how cache is implemented in offramp. @connorwstein any thoughts?

2024-02-28 13:32 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +		r.SourcePriceRegistry = sourcePriceRegistry
Probably you should call `.Close()` to unregister all filters before replacing priceRegistry

2024-02-28 13:32 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	SourcePriceRegistry         ccipdata.PriceRegistryReader
Why public?

2024-02-28 13:32 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +		r.SourcePriceRegistry = sourcePriceRegistry
Can we have parallel access to this field from multiple routines?

2024-02-29 09:27 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	SourcePriceRegistry         ccipdata.PriceRegistryReader
This field needs to be updated in case of price registry address change (in `prepareTokenExecData`)

2024-02-29 09:49 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	SourcePriceRegistry         ccipdata.PriceRegistryReader
no need anymore, fixing

2024-02-29 11:13 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	priceRegistryAddress, err := r.onRampReader.GetPriceRegistry()
That seems like a nice improvement!

2024-03-01 08:17 UTC, mateusz-sekara reviewed
I would love to see some tests for that ;)

2024-03-01 08:17 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	if r.sourcePriceRegistryProvider == nil {
Do we need that condition check? This has to be initialized on plugin boot, if not we can probably panic here because of null pointer

2024-03-01 08:17 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	priceRegistryAddress, err := r.onRampReader.GetPriceRegistry(ctx)
This new code could be extracted to a separate function/metho (e.g. `maybeReinitializeSourcePriceRegistry`) with some nice godoc why we need that and when it's valid. Also it would make it more testable

2024-03-04 13:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +			Name:      logpoller.FilterName(ccipdata.DYNAMIC_CONFIG_CHANGED, onRampAddress),
`CONFIG_CHANGE` would be better, because this event is emitted for both static and dynamic configs 

```solidyt
  event ConfigSet(StaticConfig staticConfig, DynamicConfig dynamicConfig);
```

2024-03-04 13:46 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	if r.sourcePriceRegistryProvider == nil {
Changing to a panic

2024-03-04 13:46 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	priceRegistryAddress, err := r.onRampReader.GetPriceRegistry(ctx)
Yes this block is easy to extract actually

2024-03-04 13:47 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +			Name:      logpoller.FilterName(ccipdata.DYNAMIC_CONFIG_CHANGED, onRampAddress),
Should we check only on dynamic config change for the price registry?

2024-03-04 13:50 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +			Name:      logpoller.FilterName(ccipdata.DYNAMIC_CONFIG_CHANGED, onRampAddress),
Not sure if I follow, what do you mean by checking only dynamic config change?

2024-03-04 14:03 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +			Name:      logpoller.FilterName(ccipdata.DYNAMIC_CONFIG_CHANGED, onRampAddress),
Just renamed the const

2024-03-05 11:43 UTC, mateusz-sekara reviewed
Can we have a dedicated test suite for that logic?

2024-03-05 11:43 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +	cachedOnRampPriceRegistryAddress cache.AutoSync[cciptypes.Address]
nit, but `cachedSourcePriceRegistryAddress` would be better

2024-03-05 11:43 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/onramp.go
> +func (o *OnRamp) GetPriceRegistry(ctx context.Context) (cciptypes.Address, error) {
I think this should be renamed to `SourcePriceRegistryAddress`, it would be more aligned with other function that don't return gethwrappers but addresses (e.g. `RouterAddress`)

2024-03-05 13:56 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	if r.sourcePriceRegistry == nil || priceRegistryAddress != r.sourcePriceRegistry.Address() {
nit, but these changes gonna be extremely rare, so you can achieve better performance with R/W locking here. Current solution limits multithreading to a single reader, because entire section is locked 

```go
    var needsUpdate bool
    
    // Use read lock to check the condition
    r.mutex.RLock()
    priceRegistryAddress, err := r.onRampReader.SourcePriceRegistryAddress(ctx)
    if err != nil {
        r.mutex.RUnlock()
        return fmt.Errorf("getting price registry from onramp: %w", err)
    }
    needsUpdate = r.sourcePriceRegistry == nil || priceRegistryAddress != r.sourcePriceRegistry.Address()
    r.mutex.RUnlock()
    
    // Only proceed to update if needed
    if !needsUpdate {
        return nil
    }

    r.mutex.Lock()
    defer r.mutex.Unlock()
   // update logic
   //...
```

2024-03-05 14:26 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +		r.SourcePriceRegistry = sourcePriceRegistry
Added RW mutex to protect access to the critical section.

2024-03-05 17:10 UTC, mateusz-sekara approved these changes

2024-03-06 09:34 UTC, merged

2024-03-06 15:34 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	if err = r.ensurePriceRegistrySynchronization(ctx); err != nil {
Shouldn't this call be made when the observation round starts?
Otherwise we might miss price registry getting synchronized.
For example going one step back:

```
	if len(unexpiredReports) == 0 {
		return []ccip.ObservedMessage{}, nil
	}

	getExecTokenData := cache.LazyFunction[execTokenData](func() (execTokenData, error) {
		return r.prepareTokenExecData(ctx)
	})
```

in that case `prepareTokenExecData` and eventually `ensurePriceRegistrySynchronization` are never called.

2024-03-06 15:34 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/cciptypes/onramp.go
> +	SourcePriceRegistryAddress(ctx context.Context) (Address, error)
This should be include under chainlink-common:
https://github.com/smartcontractkit/chainlink-common/tree/main/pkg/types/ccip

I will get rid of `cciptypes` package and import chainlink-common very soon

2024-03-06 15:34 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_5_0/onramp.go
> +			[]common.Hash{abihelpers.MustGetEventID("ConfigSet", onRampABI)},
Lot's of `"ConfigSet"`. Can we use a constant?

2024-03-06 15:46 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	if err = r.ensurePriceRegistrySynchronization(ctx); err != nil {
@jarnaud

2024-03-06 16:26 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	if err = r.ensurePriceRegistrySynchronization(ctx); err != nil {
Created another PR to move the sync code: https://github.com/smartcontractkit/ccip/pull/586/files

2024-03-06 16:28 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/cciptypes/onramp.go
> +	SourcePriceRegistryAddress(ctx context.Context) (Address, error)
This refactoring doesn't seem immediately related to this ticket

2024-03-06 16:39 UTC, jarnaud commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_5_0/onramp.go
> +			[]common.Hash{abihelpers.MustGetEventID("ConfigSet", onRampABI)},
Indeed, added some const here: https://github.com/smartcontractkit/ccip/pull/586

2024-03-06 17:57 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +	if err = r.ensurePriceRegistrySynchronization(ctx); err != nil {
> in that case prepareTokenExecData and eventually ensurePriceRegistrySynchronization are never called.

@dimkouv @jarnaud why is that a problem? At this moment, the source price registry is used only in a single place, so what's the point of eagerly synchronizing that? I understand that in case of adding any other reference to the source price registry might end up trying to call stale object.