PoC exposing isHealthy function in LogPoller
smartcontractkit/ccip pull request #584
Opened 2024-03-06 10:48 UTC by mateusz-sekara

## Motivation

## Solution

2024-03-06 18:04 UTC, reductionista commented on core/chains/evm/logpoller/log_poller.go
> +	isReorged      *atomic.Bool
Can we change this to something like `finalityViolated` ? `isReorged` seems misleading, since the chain gets re-orged all the time and it's usually not a problem

2024-03-07 08:57 UTC, makramkd reviewed
Is it possible to go from `finalityViolated == true` to `finalityViolated == false` during normal operation without restarting and changing finality depth manually?

2024-03-07 09:00 UTC, mateusz-sekara commented
> Is it possible to go from `finalityViolated == true` to `finalityViolated == false` during normal operation without restarting and changing finality depth manually?

Deleting blocks and logs from the database doesn't require a restart. Please see the test, this case is included there ;)

2024-03-07 13:33 UTC, roman-kashitsyn commented on core/chains/evm/logpoller/log_poller.go
> +		finalityViolated:         &isReorged,
nit: we don’t need to put `false`, the doc explicitly states that the zero value is `false`.

> The zero value is false.
-- https://pkg.go.dev/sync/atomic@go1.22.1#Bool

That’s also what most devs should expect because it’s consistent with the standard zero-init rules.

Also, I find it confusing to name the variable `isReorged` in one place and assign it to `finalityViolated` later because reorg != finality violation in general.

```suggestion
		finalityViolated:         new(atomic.Bool),
```

2024-03-07 13:33 UTC, roman-kashitsyn commented on core/chains/evm/logpoller/log_poller.go
> +	finalityViolated *atomic.Bool
What are the semantics of this field? Can it ever become `false` after it became `true`?

2024-03-07 13:59 UTC, mateusz-sekara commented on core/chains/evm/logpoller/log_poller.go
> +	finalityViolated *atomic.Bool
Makram already asked that question, please see the tests documenting that thing. I can add detailed description if it's still not obvious

2024-03-07 14:10 UTC, roman-kashitsyn commented on core/chains/evm/logpoller/log_poller_test.go
> +			assert.Error(t, th.LogPoller.Ready())
Should we assert that the error is `ErrFinalityViolated`?

2024-03-07 14:14 UTC, roman-kashitsyn approved these changes

2024-03-07 14:26 UTC, makramkd commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
This PR looks good overall but what's the difference between `Ready` and `Healthy` in this context? We already have a `HealthReport` method that calls `lp.Healthy()` but since that's not implemented on the LP itself it calls it on the `StateMachine` object from chainlink-common which is embedded in the LP struct.

2024-03-07 14:26 UTC, makramkd commented on core/chains/evm/logpoller/log_poller.go
>  	lp.SvcErrBuffer.Append(rerr)
It would be nice if we can use this but the semantics seem weird, it seems like the buffer is flushed whenever you read it, so it's not really super usable for our use case.

2024-03-07 14:26 UTC, makramkd commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
The added "benefit" of implementing `Healthy` is that `HealthReport` will return a meaningful report now since we return whether finality has been violated.

2024-03-07 14:26 UTC, makramkd commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
Keep in mind I'm not 100% sure how these functions are consumed outside of this particular context we want to consume them in now.

2024-03-07 14:42 UTC, mateusz-sekara commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
Oh nice catch, I wasn't aware of `healthy` function when going through the interfaces. @reductionista could you please advise which is better for this case?

2024-03-07 15:24 UTC, connorwstein requested changes

2024-03-07 15:24 UTC, connorwstein commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
I believe healthy/ready are inherited from k8s probes. If not ready k8s won't send traffic yet and if not healthy k8s will restart the node. We only expose the ready one to k8s directly https://github.com/smartcontractkit/ccip/blob/2f10153ff81916a561f3035dee98f2530e6a17a6/core/web/health_controller.go#L27 and have a separate health report. Healthy definitely makes more sense here

2024-03-07 15:24 UTC, connorwstein commented on core/chains/evm/logpoller/log_poller.go
> +		lp.finalityViolated.Store(false)
I think still an edge case here: say a finality violation is detected and you wipe the db. We'll hit the "first poll ever on new chain" return case here and leave the bool true. I think you want a defer where any non-error return value from this function we set to false

2024-03-07 15:29 UTC, mateusz-sekara commented on core/chains/evm/logpoller/log_poller.go
> +		lp.finalityViolated.Store(false)
So you suggest marking it as false at the end of `PollAndSave` tick? It would be definitely easier if errors were bubbled up, but still doable

2024-03-07 15:32 UTC, mateusz-sekara commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
It seems that `Healthy() error` is not present in LogPoller's interface, probably it has to be added first  🤔

2024-03-07 15:43 UTC, makramkd commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
It's in the `services.StateMachine` that's embedded in the `logPoller` struct - we have to override it to get useful behavior IIUC.

2024-03-07 15:44 UTC, makramkd commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
Ah you mean the `LogPoller` interface - that's a good point. We should add it there if we want clients to call it.

2024-03-07 15:49 UTC, mateusz-sekara commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
Yeah, already added it, I'm just a bit worried about what @connorwstein said about that function being used for k8s tooling. If that's the case, then we don't want to restart pod whenever LogPoller is marked as not healthy.

2024-03-07 18:46 UTC, reductionista approved these changes

2024-03-07 19:40 UTC, connorwstein approved these changes

2024-03-07 19:40 UTC, connorwstein commented on core/chains/evm/logpoller/log_poller.go
> +		lp.finalityViolated.Store(false)
imagining something like this, can be a follow up  
```
func (lp *logPoller) getCurrentBlockMaybeHandleReorg(ctx context.Context, currentBlockNumber int64, currentBlock *evmtypes.Head) (*evmtypes.Head, err error) {
	defer func() {
                // Note careful about shadowing etc
		if err != nil {
			lp.finalityViolated.Store(false)
		}
	}()
```

2024-03-07 19:40 UTC, merged

2024-03-08 06:39 UTC, makramkd commented on core/chains/evm/logpoller/log_poller.go
> +func (lp *logPoller) Ready() error {
Who is the SME on this? Maybe someone from infra or maybe core?