Refreshing RMN state in the background
smartcontractkit/ccip pull request #596
Opened 2024-03-08 11:42 UTC by mateusz-sekara

## Motivation

## Solution

2024-03-08 13:44 UTC, roman-kashitsyn approved these changes

2024-03-08 13:44 UTC, roman-kashitsyn commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
>  	// Otherwise, it will use the cached value of the RMN curse state.
The second part of the comment (related to `forceRefresh`) became obsolete after the change.
```suggestion
	// IsHealthy checks if the chain is healthy and returns true if it is, false otherwise.
```

2024-03-08 13:44 UTC, roman-kashitsyn commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		_, _ = c.refresh(ctx)
I first thought there is a race condition between the refresher and the first call to `IsHealthy`, but then I saw that `checkIfRMNsAreHealthy` handles the first initialization. 
I’d say the code will be clearer if we execute the first `c.refresh()` synchronously in the constructor context before spawning the background worker. We can then remove this line.

2024-03-08 14:03 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		_, _ = c.refresh(ctx)
Doing that in the constructor adds yet another synchronous call to the plugin initialization :D

2024-03-08 14:26 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		_, _ = c.refresh(ctx)
@connorwstein any thoughts here?

2024-03-08 14:29 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +func newChainHealthcheckWithCustomEviction(lggr logger.Logger, onRamp ccipdata.OnRampReader, commitStore ccipdata.CommitStoreReader, globalStatusDuration time.Duration, rmnStatusRefreshInterval time.
Naming nit (feel free to ignore): for "testing only" functions we usually name them something like `xxxTestingOnly*`. I think in theory you could add a lint check in the event such a function isn't called in tests and fail in CI, but we currently don't have that.

2024-03-08 14:29 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		_, _ = c.refresh(ctx)
Somewhat related - it's possible (yet highly unlikely, given time between initialization and plugin execution) that this goroutine did not actually start running (and was only scheduled by the runtime) and that this `refresh` call is not made. What's the effect if `IsHealthy` is called when no `refresh` was ever called?

2024-03-08 14:35 UTC, connorwstein requested changes

2024-03-08 14:35 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +			case <-ctx.Done():
I traced this up to the OCR delegate and I don't see how it'd ever be cancelled? Generally I think any background services should be returned as regular services alongside the oracle https://github.com/smartcontractkit/ccip/blob/4bba1ef7de56b4143fe6a1ff0167067774a27e09/core/services/ocr2/plugins/ccip/ccipcommit/initializers.go#L72

2024-03-08 14:36 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +	// These checks are cheap and don't require any communication with the database or RPC
Is this technically true? If we call LogPoller methods won't those query the DB (or RPC if nothing in DB matches)?

2024-03-08 14:36 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +	// These checks are cheap and don't require any communication with the database or RPC
Oh cool - looks like we call `lp.Healthy` which just checks an atomic.

2024-03-08 14:41 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +			case <-ctx.Done():
So we have a similar problem here https://github.com/smartcontractkit/ccip/blob/f6b2afc88a4a21d64d52f9c67e216ed176d3b3f2/core/services/ocr2/plugins/ccip/ccipexec/initializers.go#L267

2024-03-08 14:43 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		_, _ = c.refresh(ctx)
It's refreshed synchronously during `IsHealthy`

2024-03-12 10:37 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		c.backgroundCancel()
I'm guessing you're missing a `c.wg.Wait()` here, based off of the code you have so far.

2024-03-12 10:37 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		c.backgroundCancel()
That is, if `Close` must synchronously ensure that all goroutines are shut down :-)

2024-03-12 10:37 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		c.backgroundCancel()
If not, you can probably get rid of the waitgroup.

2024-03-12 10:41 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
>  	// RMN curse state is refreshed every 20 seconds or when ForceIsHealthy is called
This comment is out of date right?

2024-03-12 10:46 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +	defaultGlobalStatusDuration    = 30 * time.Minute
Naming nit (feel free to ignore):

```suggestion
	defaultGlobalStatusExpirationDuration    = 30 * time.Minute
```

2024-03-12 10:46 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
>  	globalStatusKey = "globalStatus"
Just guessing here, but is "global status" referring to the four checks listed above on lines 22-25?

2024-03-12 10:54 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		c.lggr.Criticalw("Failed to cast cached value to RMN response", "response", rmn)
This indicates a bug in the code right?

2024-03-12 10:54 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		c.lggr.Criticalw("Failed to cast cached value to RMN response", "response", rmn)
Panic-worthy maybe?

2024-03-12 10:54 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +	c.lggr.Warnw("Refreshing RMN state from the plugin routine, this should happen only once per lane during boot")
Logger level warn? I feel like this is an info-level log no?

2024-03-12 10:54 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +				_, _ = c.refresh(c.backgroundCtx)
Should we log the error here? Just wondering if this component could be failing in the background for a while without us knowing or finding out.

2024-03-12 10:54 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		3*c.rmnStatusRefreshInterval, // Cache the value for 3 refresh intervals
The comment doesn't provide reasoning as to why 3 intervals vs. 4 or 5, just seems arbitrary.

2024-03-12 11:14 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +				_, _ = c.refresh(c.backgroundCtx)
Errors are populated to cache, so whenever error is returned it will be propagated to the plugin, but it might be worth logging here anyway

2024-03-12 11:15 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		3*c.rmnStatusRefreshInterval, // Cache the value for 3 refresh intervals
It is arbitrary, gonna make it more explicit

2024-03-12 11:21 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
>  	// RMN curse state is refreshed every 20 seconds or when ForceIsHealthy is called
No longer needed I believe

2024-03-12 11:23 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +	c.lggr.Warnw("Refreshing RMN state from the plugin routine, this should happen only once per lane during boot")
I thought about warning, because this is something that should happen once per lane when node starts and then everything should be refreshed in the background, maybe I should indeed make it info

2024-03-12 11:43 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +		c.lggr.Criticalw("Failed to cast cached value to RMN response", "response", rmn)
Yeah, I will just remove `ok` check, it will panic automatically

2024-03-12 11:57 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/cache/chain_health.go
> +				_, _ = c.refresh(c.backgroundCtx)
Ah I see, in that case might be fine then. Just concerned about visibility of the error, but if you feel now is visible enough, all good.

2024-03-12 12:30 UTC, makramkd approved these changes
🙇

2024-03-13 13:51 UTC, connorwstein approved these changes

2024-03-13 13:57 UTC, merged