CCIP-1795 merge with core-2.10-beta
smartcontractkit/ccip pull request #609
Opened 2024-03-13 22:48 UTC by AnieeG

## Motivation

## Solution

2024-03-14 11:29 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/initializers.go
> +	// FIXME: Temporary solution to make tests passing. We need to refactor bg workers to implement ServiceCtx interface
https://github.com/smartcontractkit/ccip/pull/610

2024-03-14 15:43 UTC, chainchad reviewed
The .github/ stuff looks good to me outside of some comments. Also the changesets stuff could probably be resolved by the PR I mentioned in case we want to merge that first or merge that into this.

2024-03-14 15:43 UTC, chainchad commented on .changeset/config.json
> +      "repo": "smartcontractkit/chainlink"
```suggestion
      "repo": "smartcontractkit/ccip"
```

We probably want @momentmaker's [PR](https://github.com/smartcontractkit/ccip/pull/594) though.

2024-03-14 15:43 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          ref: ${{ inputs.cl_ref }}
Is it necessary to include the `repository: ` here?

2024-03-14 15:43 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
Needed?

2024-03-14 15:43 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
Needed?

2024-03-14 15:43 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
Needed?

2024-03-14 15:43 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
Needed?

2024-03-14 15:43 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
Needed?

2024-03-14 15:43 UTC, chainchad commented on .github/workflows/live-vrf-tests.yml
> +  CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
Should this be /ccip or should we comment out this entire file perhaps if VRF is not relevant for CCIP?

2024-03-14 15:43 UTC, chainchad commented on .goreleaser.devspace.yaml
> +project_name: chainlink
```suggestion
project_name: ccip
```

2024-03-14 15:43 UTC, chainchad commented on .goreleaser.devspace.yaml
> +      - -X github.com/smartcontractkit/chainlink/v2/core/static.Sha={{ .FullCommit }}
Are these valid?

2024-03-14 18:28 UTC, AnieeG commented on .github/workflows/integration-tests.yml
> +          ref: ${{ inputs.cl_ref }}
Probably no, but I am not sure if in next merge it will again get changed to smartcontractkit/chainlink, Core 's same workflow file mentions this parameter

2024-03-14 18:29 UTC, AnieeG commented on .goreleaser.devspace.yaml
> +      - -X github.com/smartcontractkit/chainlink/v2/core/static.Sha={{ .FullCommit }}
It got copied during merge, Any change needed?

2024-03-14 18:30 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          ref: ${{ inputs.cl_ref }}
Sorry, ignore. I do see on /chainlink it's explicitly specified. I would have thought it would be implicit and we were adding it here for some reason but this seems right based on how /chainlink is.

2024-03-14 18:30 UTC, AnieeG commented on .github/workflows/live-vrf-tests.yml
> +  CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
yes . good point. deleting this

2024-03-14 18:30 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
https://github.com/smartcontractkit/ccip/pull/609#discussion_r1525332009

2024-03-14 18:30 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
https://github.com/smartcontractkit/ccip/pull/609#discussion_r1525332009

2024-03-14 18:30 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
https://github.com/smartcontractkit/ccip/pull/609#discussion_r1525332009

2024-03-14 18:30 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
https://github.com/smartcontractkit/ccip/pull/609#discussion_r1525332009

2024-03-14 18:30 UTC, chainchad commented on .github/workflows/integration-tests.yml
> +          repository: smartcontractkit/ccip
https://github.com/smartcontractkit/ccip/pull/609#discussion_r1525332009

2024-03-14 18:34 UTC, chainchad commented on .goreleaser.devspace.yaml
> +      - -X github.com/smartcontractkit/chainlink/v2/core/static.Sha={{ .FullCommit }}
Wondering about the build args being /chainlink instead of /ccip. Looks like it's a non-issue because we also have these set [here](https://github.com/smartcontractkit/ccip/blob/ccip-develop/tools/bin/ldflags#L8).

2024-03-14 20:21 UTC, matYang approved these changes

2024-03-15 08:50 UTC, dimkouv approved these changes

2024-03-15 13:15 UTC, tateexon approved these changes

2024-03-15 14:05 UTC, mateusz-sekara approved these changes

2024-03-18 09:38 UTC, makramkd requested changes

2024-03-18 09:38 UTC, makramkd commented on core/services/blockhashstore/delegate.go
> +func (d *Delegate) ServicesForSpec(ctx context.Context, jb job.Job, opt ...pg.QOpt) ([]job.ServiceCtx, error) {
This function signature is incorrect, there are no `...pg.QOpt` arguments anymore for ServicesForSpec in core develop: https://github.com/smartcontractkit/ccip/pull/609/commits/e7c63c6b95e4fe16a9c54cff96f1997df7157643#diff-92ac14d64138e4396d8f90dea421ef434e01c35e030688c7193a0c325f0c1e06R55

2024-03-18 09:38 UTC, makramkd commented on core/services/blockhashstore/delegate.go
> +func (d *Delegate) ServicesForSpec(ctx context.Context, jb job.Job, opt ...pg.QOpt) ([]job.ServiceCtx, error) {
Same applies to the rest of the ServicesForSpec changes

2024-03-18 12:24 UTC, makramkd approved these changes

2024-03-18 12:24 UTC, makramkd commented on core/services/blockhashstore/delegate.go
> +func (d *Delegate) ServicesForSpec(ctx context.Context, jb job.Job, opt ...pg.QOpt) ([]job.ServiceCtx, error) {
Addressed offline, this is to make sure that log poller filter registration/de-registration continues to work.

2024-03-18 12:51 UTC, krehermann approved these changes
code owners

2024-03-18 12:55 UTC, merged