CCIP-1732 dynamic token price update in load test
smartcontractkit/ccip pull request #622
Opened 2024-03-19 02:22 UTC by AnieeG

## Motivation

## Solution

2024-03-21 14:43 UTC, mateusz-sekara approved these changes

2024-03-21 14:43 UTC, mateusz-sekara commented on integration-tests/ccip-tests/types/config/node/core.go
> +		if evmConfig.Chain.FinalityDepth == nil && network.FinalityDepth > 0 {
👏

2024-03-22 19:41 UTC, kalverra requested changes

2024-03-22 19:41 UTC, kalverra commented on integration-tests/ccip-tests/contracts/contract_models.go
> +	if err != nil {
Curious why this is the way to handle things? Seems magic numbery to me, I think a comment would be good.

2024-03-22 19:41 UTC, kalverra commented on integration-tests/ccip-tests/load/ccip_loadgen.go
> +	// if it's not multicall set the tokens to nil to free up some space,
I appreciate this one!

2024-03-22 19:41 UTC, kalverra commented on integration-tests/ccip-tests/load/helper.go
> +	errGrp, _ := errgroup.WithContext(testcontext.Get(l.t))
Why toss the context?

2024-03-22 19:41 UTC, kalverra commented on integration-tests/ccip-tests/utils/common.go
> +	if foundNil {
👍

2024-03-22 19:41 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +// UpdateTokenPricesAtRegularInterval updates aggregator contract with updated answer at regular interval.
👍

2024-03-22 19:41 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +				if err != nil {
It's possible RPC is down for a minute or two, and this will kill the test. Best to keep trying to resubscribe, but on a backoff timer. Example [here](https://github.com/smartcontractkit/chainlink/blob/develop/integration-tests/testsetups/ocr.go#L642)

2024-03-22 19:41 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +				if err != nil {
Or hook this into your RPC connection polling somehow?

2024-03-22 21:30 UTC, AnieeG commented on integration-tests/ccip-tests/load/helper.go
> +	errGrp, _ := errgroup.WithContext(testcontext.Get(l.t))
not required. removing it

2024-03-25 14:48 UTC, kalverra approved these changes

2024-03-25 14:48 UTC, kalverra commented on integration-tests/ccip-tests/load/ccip_test.go
> +// TestLoadCCIPStableRPSAfterARMCurseAndUncurse validates that after ARM curse is lifted
👍

2024-03-25 14:48 UTC, merged