Increase default LimitDefault for CCIP
smartcontractkit/ccip pull request #664
Opened 2024-04-01 13:39 UTC by HelloKashif

2024-04-02 08:34 UTC, RensR commented on core/chains/evm/config/toml/defaults/fallback.toml
> +LimitDefault = 8_000_000
Let's use this nice underscore_format_in other places as well :)

2024-04-15 09:36 UTC, RensR commented on core/chains/evm/config/toml/defaults/fallback.toml
> +LimitDefault = 8_000_000
I mean for the 8m values you put everywhere, not unrelated entires in the fallback. Please undo any unrelated changes

2024-06-04 13:43 UTC, jmank88 commented on testdata/scripts/node/db/help.txtar
IIRC these need to be exact matches

2024-06-04 15:46 UTC, jmank88 commented on core/config/docs/chains-evm.toml
> +LimitDefault = 8000000 # Default
Let's retain the format for readability:
```suggestion
LimitDefault = 8_000_000 # Default
```

2024-06-19 09:46 UTC, RensR commented
Please remove the changesets as we no longer use them. Also please us the `8_000_000` format over `8000000`

2024-06-24 13:55 UTC, jmank88 commented on .changeset/README.md
Why are all of these changeset files being deleted?

2024-06-24 13:56 UTC, jmank88 commented on core/chains/evm/config/config_test.go
> +	assert.Equal(t, uint64(8000000), ge.LimitMax())
Go supports the `_` format too:
```suggestion
	assert.Equal(t, uint64(8_000_000), ge.LimitDefault())
	assert.Equal(t, uint64(8_000_000), ge.LimitMax())
```

2024-06-24 14:52 UTC, simsonraj commented on .changeset/README.md
+1

2024-06-24 14:52 UTC, simsonraj commented on .github/workflows/integration-tests.yml
> +          DEBUG_RESTY: true
do we need to let this on?

2024-06-24 14:53 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/fallback.toml
> +LogPrunePageSize = 10_000
I would keep this PR clean only for the changes related to the problem & not touch these fields for now

2024-06-24 14:56 UTC, simsonraj requested changes

2024-06-24 14:56 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/fallback.toml
> +GasLimit = 5_400_000
Same here, please dont change the formats for other values as part of this PR

2024-06-24 14:56 UTC, simsonraj commented on core/internal/features/features_test.go
> +			tx = cltest.NewLegacyTransaction(n, sendingKeys[0].Address, assets.Ether(801).ToInt(), 21000, big.NewInt(1000000000), nil)
odd value 801?

2024-06-24 14:56 UTC, simsonraj commented on integration-tests/testconfig/default.toml
> +chainlink_node_funding = 1
Is this enough to cover the tests?

2024-06-25 07:51 UTC, amaechiokolobi commented on .changeset/README.md
@RensR mentioned earlier to remove them as they are no longer being used https://github.com/smartcontractkit/ccip/pull/664#issuecomment-2178238991

2024-06-26 10:15 UTC, amaechiokolobi commented on integration-tests/testconfig/default.toml
> +chainlink_node_funding = 1
It seems to be fine for the tests, but I will increase it to 4 to align with the gas limit changes. I had this set as I previously had issues with the smoke tests before but now that its fixed it should be fine

2024-06-26 10:16 UTC, amaechiokolobi commented on core/internal/features/features_test.go
> +			tx = cltest.NewLegacyTransaction(n, sendingKeys[0].Address, assets.Ether(801).ToInt(), 21000, big.NewInt(1000000000), nil)
The test required 800 eth + ~1 gwei, I will change this to 1000 so it is cleaner

2024-06-26 23:48 UTC, amaechiokolobi commented on integration-tests/testconfig/default.toml
> +chainlink_node_funding = 1
Set this to 2, as I was getting many errors when it was set to 4

2024-07-01 11:28 UTC, simsonraj approved these changes

2024-07-01 11:42 UTC, RensR commented on .changeset/README.md
I meant remove the ones you created, not every single one that exists

2024-07-01 11:53 UTC, amaechiokolobi commented on .changeset/README.md
my mistake I misunderstood the message 🤦 I'll add these back now

2024-07-02 12:49 UTC, amaechiokolobi commented on .changeset/README.md
the changesets were re-added when merging, so this issue has been corrected @RensR

2024-07-05 10:33 UTC, mateusz-sekara approved these changes
Looks good, one minor question about change in the CI files

2024-07-05 10:33 UTC, mateusz-sekara commented on .github/workflows/integration-tests.yml
> +          DEBUG_RESTY: false
Why do we need this change?

2024-07-05 11:02 UTC, amaechiokolobi commented on .github/workflows/integration-tests.yml
> +          DEBUG_RESTY: false
@mateusz-sekara We only had it enabled to debug a prior issue. Or do you think I should remove the line entirely?

2024-07-11 16:45 UTC, jasonmci approved these changes
Approved.

2024-07-11 17:31 UTC, merged