usdc: Add self rate limiting to the usdc attestation API.
smartcontractkit/ccip pull request #666
Opened 2024-04-01 20:35 UTC by winder

## Motivation

Circle's USDC attestation API has a 5 minute IP ban if rate limits are exceeded. In order to avoid the 5 minute ban we should proactively limit our requests to make sure this doesn't happen.

## Solution

Use `golang.org/x/time/rate` to add rate limit calls to the USDC TokenDataReader.

2024-04-04 11:25 UTC, dimkouv requested changes
1) Highly recommend updating the bg worker logic to not depend on ocr rounds for making progress.
2) Load test with multiple usdc transfers and compare before/after.

2024-04-04 11:25 UTC, dimkouv commented on .changeset/twelve-donuts-sell.md
> Should the interval be configurable at the job spec level? That would allow turning on the new behavior on or off with a configuration.

That would be nice.

2024-04-04 11:25 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/tokendata/usdc/usdc.go
> +	RequestInterval = 100 * time.Millisecond
Let's imagine that we have the following message that contains 4 usdc transfers:
```
msgs = [
   { seqNum: 10, tokens: [("usdc", 1)("usdc", 1)("usdc", 1)("usdc", 1)] }
]
```

Messages are [pushed](https://github.com/smartcontractkit/ccip/blob/c5830c1fa5334225a647f94c206d673f719963cd/core/services/ocr2/plugins/ccip/ccipexec/ocr2.go#L178) to the token data background worker.
Every token amount is processed individually [in a loop](https://github.com/smartcontractkit/ccip/blob/4a6f68e052f1e55596b1f8238f23806a7128c541/core/services/ocr2/plugins/ccip/tokendata/bgworker.go#L158).

So this loop will always return error in the second loop iteration.
Essentially storing in the cache something like this:

```
{
   seqNum=10 [
      tokenDataForFirstUsdcTransfer,
      errSelfRateLimit,
      errSelfRateLimit,
      errSelfRateLimit,
   ]
}
```

After a while the plugin will try to [get token data](https://github.com/smartcontractkit/ccip/blob/c5830c1fa5334225a647f94c206d673f719963cd/core/services/ocr2/plugins/ccip/ccipexec/ocr2.go#L499) and will [get an error](https://github.com/smartcontractkit/ccip/blob/4a6f68e052f1e55596b1f8238f23806a7128c541/core/services/ocr2/plugins/ccip/tokendata/bgworker.go#L123).

Eventually [skipping the msg](https://github.com/smartcontractkit/ccip/blob/c5830c1fa5334225a647f94c206d673f719963cd/core/services/ocr2/plugins/ccip/ccipexec/ocr2.go#L412).

In the next round the message is added again to the token data background worker eventually making progress until all the token data are found.


Imagine the same situation but with two msgs
```
msgs = [
   { seqNum: 10, tokens: [("usdc", 1)] }
   { seqNum: 11, tokens: [("usdc", 1)] }
]
```

Messages will both be pushed to token data background worker and the second message will be skipped until next round.

This will eventually slow down usdc messages. Since they are retried on every new round essentially making small progress on each round.

1) I highly recommend load testing with multiple usdc transfers
2) I suggest updating the logic [here](https://github.com/smartcontractkit/ccip/blob/4a6f68e052f1e55596b1f8238f23806a7128c541/core/services/ocr2/plugins/ccip/tokendata/bgworker.go#L173) to retry `n times` if error is errSelfRateLimit that way we don't have to wait for the next round.

2024-04-04 12:14 UTC, winder commented on core/services/ocr2/plugins/ccip/tokendata/usdc/usdc.go
> +	RequestInterval = 100 * time.Millisecond
Instead of retrying, the rate limiter also has a `Wait(ctx)` function to block until the next call is allowed. That would be better than retrying for this specific case, except that non-usdc messages might be held up for no reason.

Seems like this loop should dispatch reads to a worker thread so that they can block or retry without effecting other messages.

2024-04-04 14:05 UTC, winder commented on core/services/ocr2/plugins/ccip/tokendata/usdc/usdc.go
> +	RequestInterval = 100 * time.Millisecond
After discussing with @dimkouv, we should simply switch to `Wait(ctx)`. The background worker already processes multiple messages concurrently, so processing each token within each message is a bit excessive.

2024-04-05 12:53 UTC, dimkouv approved these changes

2024-04-05 17:37 UTC, merged