Token pool versioned IO
smartcontractkit/ccip pull request #773
Opened 2024-04-29 14:34 UTC by RensR

Having versioned token pool IO will allow us to update to a token pool V2 without breaking the older pools. We use the supportsInterace call for this, ensuring the contract supports a given input/output format prior to calling it.

2024-04-29 16:09 UTC, elatoskinas commented on contracts/src/v0.8/ccip/libraries/Pool.sol
> +    bytes sourcePoolAddress; //       The address of the source pool, abi encoded in the case of EVM chains
q: why are we no longer using `SourceTokenData` in these args?

2024-04-29 16:09 UTC, elatoskinas commented on contracts/src/v0.8/ccip/pools/USDC/USDCTokenPool.sol
> +    Domain memory domain = s_chainToDomain[lockOrBurnIn.remoteChainSelector];
q: this looks like a fundamental check, any reason this was moved after the rate limit call?

2024-04-30 08:26 UTC, RensR commented on contracts/src/v0.8/ccip/pools/USDC/USDCTokenPool.sol
> +    Domain memory domain = s_chainToDomain[lockOrBurnIn.remoteChainSelector];
The ordering doesn't matter much, either would revert if they're wrong. Since every other pool checks rate limits first, this makes pools consistent

2024-04-30 08:28 UTC, RensR commented on contracts/src/v0.8/ccip/libraries/Pool.sol
> +    bytes sourcePoolAddress; //       The address of the source pool, abi encoded in the case of EVM chains
SourceTokenData contains 3 elements, only 2 should be passed into the pool. It's wasteful to pass in the pool address into the pool itself.

2024-04-30 09:30 UTC, elatoskinas commented on contracts/src/v0.8/ccip/pools/USDC/USDCTokenPool.sol
> +    Domain memory domain = s_chainToDomain[lockOrBurnIn.remoteChainSelector];
Wouldn't it save more gas for users, in case they use a faulty pool? The revert would be much earlier than the rate limit

2024-04-30 14:17 UTC, connorwstein commented on contracts/src/v0.8/ccip/interfaces/IPool.sol
>    struct SourceTokenData {
can be removed right

2024-04-30 20:59 UTC, connorwstein requested changes

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/libraries/Pool.sol
> +    uint256 amount; //                The amount of tokens to release or mint, denominated in the source token's decimals
nit - you can make the ordering more symmetric/intuitive between lockOrBurn/releaseOrMint and still keep the packing: 
```
  struct LockOrBurnInV1 {
    // Remote info
    bytes receiver; 
    uint64 remoteChainSelector; 
    // Local info
    address originalSender; 
    uint256 amount; 
  }

  struct ReleaseOrMintInV1 {
    // Remote info
    bytes originalSender;
    uint64 remoteChainSelector;
    // Local info
    address receiver;
    uint256 amount;
    // Remote pool info
    bytes sourcePoolAddress;
    bytes sourcePoolData;
    // Offchain pool info
    bytes offchainTokenData;
  }
```
Then they both follow the same ordering for the local/remote info

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/libraries/Pool.sol
> +    bytes offchainTokenData; //       The offchain data to process the release or mint
Good to add a loud scary comment about how offchainTokenData is untrusted and how sourcePoolAddress must be sanity checked (even if we have example code)

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/onRamp/EVM2EVMOnRamp.sol
> +      // We don't have to check if it supports the pool version in a non-reverting way here because
👍

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/interfaces/IPool.sol
>    struct SourceTokenData {
this is internally used only - should be in Internal.sol?

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/interfaces/IPool.sol
>    struct SourceTokenData {
maybe as a follow up in some upgrade later we could kill it as well just put the fields directly in the EVM2EVM message to avoid the encoding

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>          revert InvalidDataLength(32, sourceTokenData.destPoolAddress.length);
this doesn't need to be caught to mark a message failed because we check it on the onramp side before emitting the message right? Could use a comment bc subtle

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
> +      address localPoolAddress = _validateEVMAddress(abi.decode(sourceTokenData.destPoolAddress, (uint256)));
this is not safe to revert right - will DoS if I send a 32 byte precompile EVM address? I think we can just follow the same pattern as the message receiver - where we simply rely on the source chain check only. Can put this logic into a helper in the onramp and just use it for both the message.receiver and the destPoolAddress returned.
```
    if (message.receiver.length != 32) revert InvalidAddress(message.receiver);
    uint256 decodedReceiver = abi.decode(message.receiver, (uint256));
    // We want to disallow sending to address(0) and to precompiles, which exist on address(1) through address(9).
    if (decodedReceiver > type(uint160).max || decodedReceiver < 10) revert InvalidAddress(message.receiver);
```

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
> +      if (!localPoolAddress.supportsInterface(Pool.CCIP_POOL_V1)) {
I think we want the same localPoolAddress.code.length check as the message receiver. Conceptually releaseOrMint is the same a ccipReceive

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
> +        revert NotACompatiblePool(localPoolAddress);
not safe to revert? Think we want to return like we do for messages

2024-04-30 20:59 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>          revert InvalidDataLength(32, sourceTokenData.destPoolAddress.length);
update - I'd just remove this and follow the same pattern as for messages

2024-04-30 21:15 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>          Internal.MAX_RET_BYTES
wait I think the max return bytes should be set to a constant according to the pool version i.e.:
```
uint256 maxRetBytes = 0;
if (localPoolAddress.supportsInterface(Pool.CCIP_POOL_V1) {
	maxRetBytes = Pool.CCIP_POOL_V1_RET_BYTES
} else if (localPoolAddress.supportsInterface(Pool.CCIP_POOL_V2) {
	maxRetBytes = Pool.CCIP_POOL_V2_RET_BYTES
}
```

2024-04-30 21:19 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>            || InvalidEVMAddress.selector == bytes4(err) || InvalidDataLength.selector == bytes4(err)
seems more intuitive if we just use TokenHandlingError for the invalid pool return data? It includes the return data anyways so should be sufficient to debug and then we can remove InvalidEVMAddress and InvalidDataLength (assuming we follow the message pattern of source only verification)

2024-05-01 05:02 UTC, matYang commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>          Internal.MAX_RET_BYTES
since happy path returnData is 64 bytes,  it is < current `Internal.MAX_RET_BYTES`, we can probably reuse the same max length for v1 and v2, it caps the error path to same length

2024-05-01 10:13 UTC, RensR commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
> +      address localPoolAddress = _validateEVMAddress(abi.decode(sourceTokenData.destPoolAddress, (uint256)));
That only works because it's typed in the `EVM2EVMMessage`. When it's not, we have to decode it anyway, and adding these checks doesn't add much gas usage. It protects against pretty horrible failures, as abi.decode errors have no type and won't be caught. That would revert the entire batch and leads to many failed txs. Since the cost is so low, and given the major benefits if it catches something, I'd vote to keep these checks in the offRamp

2024-05-01 10:40 UTC, RensR commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>          Internal.MAX_RET_BYTES
Using Internal.MAX_RET_BYTES there will allow us to receive 4+4x32 worth of errors, the actual length required is checked just below, in the non-error case. We can move EXPECTED_POOL_RETURN_DATA_LENGTH to Pool though, that makes sense

2024-05-01 12:24 UTC, RensR commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>            || InvalidEVMAddress.selector == bytes4(err) || InvalidDataLength.selector == bytes4(err)
I'm good to throw a TokenHandlingError if the return data is wrong, but as mentioned above I'm not too convinced on the source only verification

2024-05-01 12:25 UTC, RensR commented on contracts/src/v0.8/ccip/pools/USDC/USDCTokenPool.sol
> +    Domain memory domain = s_chainToDomain[lockOrBurnIn.remoteChainSelector];
Both reverts would be edge cases. Thinking about it more, do we even need a rate limiter in the USDC pool? It's all handled by Circle anyway. I know we removed USDC from the agg rate limiter because if this

2024-05-01 14:16 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
>          Internal.MAX_RET_BYTES
I see, extra space needed for reverts

2024-05-01 15:57 UTC, connorwstein commented on contracts/src/v0.8/ccip/offRamp/EVM2EVMOffRamp.sol
> -      destTokenAmounts[i].token = _validateEVMAddress(decodedAddress);
we can still use this here right?

2024-05-01 16:22 UTC, connorwstein approved these changes

2024-05-01 19:29 UTC, matYang approved these changes

2024-05-01 19:47 UTC, merged