Chore: Update chain tomls
smartcontractkit/ccip pull request #844
Opened 2024-05-13 19:31 UTC by stackman27

## Motivation

## Solution

2024-05-13 22:18 UTC, stackman27 commented on core/chains/evm/config/toml/defaults/Polygon_Zkevm_Mainnet.toml
> +BlockHistorySize = 12
current mainnet config assigned to NOPS uses finalityTag

2024-05-13 23:01 UTC, andrevmatos approved these changes

2024-05-14 07:17 UTC, simsonraj requested changes

2024-05-14 07:17 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Metis_Sepolia.toml
> +FinalityDepth = 1
Can you please add a comment here saying, that this will need to be changed

2024-05-14 07:17 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Polygon_Zkevm_Cardona.toml
> +BlockHistorySize = 12
I think this should be a lot more for CCIP, I believe this is copied over from DF, same for Celo

2024-05-14 07:17 UTC, simsonraj commented on core/chains/evm/config/toml/defaults/Polygon_Zkevm_Mainnet.toml
> +BlockHistorySize = 12
Could we please also include Wemix, Kroma & Gnosis in the same PR? I can help you add it, if we are okay to include it here

2024-07-25 00:14 UTC, closed without merging