Offchain - Cached token pools
smartcontractkit/ccip pull request #89
Opened 2023-08-28 09:28 UTC by dimkouv

Maintain a cache for destination chain token pools to prevent making excessive RPC calls.

2023-09-12 02:23 UTC, connorwstein requested changes

2023-09-12 02:23 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +			poolAddress, err = r.config.offRamp.GetPoolByDestToken(&bind.CallOpts{Context: ctx}, dstToken)
is this defensive code in case the cache is broken? I think that might be overkill/not worth the spaghetti

2023-09-12 02:23 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
interesting - is the intention a best effort update of the cache? Seems much better to actually return an error, then the next call to Get will retry

2023-09-12 02:23 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +func NewTokenPools(
splitting this into a separate cache from the dest tokens opens this possibility:
1. Client calls cachedDestTokens.Get() gets token a,b
2. Onchain pool is added
3. Client calls cachedTokenPools.Get() gets a,b,c 

or vice versa, which I think we should avoid. Best to group all the same events in one cache imo, probably safer to merge the decimals one as well come to think of it.

2023-09-15 09:39 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
if the code looks like this
```
tokens = getDestinationAndFeeTokens()
for token in tokens:
   pool, err = offramp.getpool(token)
   if err != nil -> return err
```

and for whatever reason offRamp *always* returns an error for a specific token, e.g. token pool is not configured
then the whole observation round would die until the issue for the specific token is fixed. I want to avoid this, that's why I wrote it in such way.

Single point of failure should not be a token config for the observation round.

Ideally we want a cache that is able to fetch specific keys and do error handling on the plugin level.

```
// plugin
for token in tokens:
   decimals, err = cache.getDecimals(ctx, someAddress)
   if err != nil -> ...
```

2023-09-15 10:38 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +func NewTokenPools(
Nice catch, again issue would be resolved by making the cache work with specific keys (and also reduce boot time since not everything needs to be fetched at once, only what is specific to a batch).

```
destTokens := cache.GetDestTokens()

for tk in destTokens:
   cache.GetDecimals(tk)
   cache.GetTokenPool(tk)
```

Placing them all in the same cache introduces other issues.

For example: If you put together destTokens+decimals+tokenPools then one event will cause all of this caches to get invalidated and re-synced which might cause timeouts since there is a big amount of rpc calls involved.

Worst case scenario the issue that you described happens:

```
1. A new token was added - no issue at all - just an extra rpc call.
2. A token was removed - no issue at all - this token should not appear in any msg - if it does it will be skipped, which is normal
```

I suggest to keep current approach as is and work on the cache, that should already be in our backlog.

2023-09-15 10:40 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +			poolAddress, err = r.config.offRamp.GetPoolByDestToken(&bind.CallOpts{Context: ctx}, dstToken)
yes, we already had such issue for token decimals.
if a specific pool is not in the cache (due to rpc error for example) then we won't process it.
this code prevents that situation.

2023-09-15 16:18 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/execution_reporting_plugin.go
> +			poolAddress, err = r.config.offRamp.GetPoolByDestToken(&bind.CallOpts{Context: ctx}, dstToken)
> if a specific pool is not in the cache (due to rpc error for example)

To keep the code clean and simple we should just prevent a "partially valid cache" from ever happening. The cache should either be stale or up to date entirely, it should never be partially up to date where the caller is just implicitly assume to fill in missing data

2023-09-15 16:22 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
> e.g. token pool is not configured

I don't think this is a scenario we want graceful recovery. A one-sided token configuration is a critical failure which should never happen and if it does stopping observations is appropriate

2023-09-15 16:30 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +func NewTokenPools(
> If you put together destTokens+decimals+tokenPools then one event will cause all of this caches to get invalidated and re-synced which might cause timeouts since there is a big amount of rpc calls involved.

Again new tokens are rare its a few / month at most. Mitigations for timeout risk: a) batch all the rpc calls into one call b) put the cache loop in the background 

> I suggest to keep current approach as is and work on the cache, that should already be in our backlog.

Sounds good to me

2023-09-18 09:01 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
Ok makes sense then to return an error and stop the observation round.

2023-09-18 14:10 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool.go
> +		eg.Go(func() error {
Isn't like an amazing place to try batching? Is there an easy way to batch requests with gethwrappers?

2023-09-18 14:10 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool.go
> +	const numWorkers = 5
I think it should be a param in `tokenPools` struct

2023-09-18 14:10 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool.go
> +func (t *tokenPools) CallOrigin(ctx context.Context) (map[common.Address]common.Address, error) {
Can we have a tests for it? Checking conditions like single goroutine failing/ all are successful, etd?

2023-09-19 08:04 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool.go
> +		eg.Go(func() error {
nah, not easy to do with our current approach, we need to create some small lib for that

2023-09-19 08:06 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool.go
> +		eg.Go(func() error {
I could build something in a separate task/pr

2023-09-19 08:50 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool.go
> +func (t *tokenPools) CallOrigin(ctx context.Context) (map[common.Address]common.Address, error) {
test

2023-09-19 08:52 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool_test.go
> +	tk1src := utils.RandomAddress()
👍 for using randomly generated  input

2023-09-19 08:52 UTC, mateusz-sekara approved these changes

2023-09-19 08:58 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/cache/tokenpool_test.go
> +	tk1src := utils.RandomAddress()
very good

2023-09-19 09:54 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
After applying this change the smoke tests are failing.
@AnieeG are the token pools in the smoke tests properly configured? The `getDestinationAndFeeTokens` returns some token that returns error for `r.config.offRamp.GetPoolByDestToken` @connorwstein this is exactly the scenario I wanted to prevent from happening on prod.

2023-09-19 14:46 UTC, connorwstein commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
Sounds like we discovered a test misconfiguration that was being masked by this code. Its prevented in prod by the config checker

2023-09-27 00:09 UTC, AnieeG commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
Hey @dimkouv @connorwstein I am not providing any dest tokens into offramp [constructor](https://github.com/smartcontractkit/ccip/blob/ccip-develop/integration-tests/ccip-tests/actions/ccip_helpers.go#L1066-L1069). I am providing source tokens and corresponding dest pool. Where should I pass the dest tokens into offramp?

2023-09-27 14:02 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/cache/tokenpool.go
> +				return nil
dmed

2023-09-28 14:02 UTC, connorwstein approved these changes

2023-09-29 09:31 UTC, merged