Exec NewReportingPlugin must not error
smartcontractkit/ccip pull request #894
Opened 2024-05-21 18:54 UTC by rstout

## Motivation
Previously, any single error during the call to NewReportingPlugin for the Exec plugin would cause the OCR instance to not start. Even if the error was transient and would be resolved if NewReportingPlugin was called again, the OCR instance would remain down. 

## Solution
In order to be robust to transient errors, NewReportingPlugin is retried until it succeeds.

2024-05-31 23:49 UTC, connorwstein approved these changes
Looks great!

2024-06-03 15:43 UTC, dimkouv requested changes

2024-06-03 15:43 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/factory.go
> +	return pluginAndInfo.plugin, pluginAndInfo.pluginInfo, err
This code can panic if the error is not nil

2024-06-03 15:51 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/initializers.go
> +func defaultNewReportingPluginRetryConfig() ccipdata.RetryConfig {
Maybe better to do:
```
var defaultNewReportingPluginRetryConfig = ccipdata.RetryConfig{
	InitialDelay: time.Second,
	MaxDelay:     15 * time.Second,
}
```

2024-06-03 15:51 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	return retry.DoWithData(
If there is a critical issue that prevents plugin to boot this will spam telemetry with the errors.
Maybe better to stop retrying after a while.

2024-06-03 15:51 UTC, dimkouv commented on pnpm-lock.yaml
> -lockfileVersion: '6.0'
This shouldn't have been pushed, right?

2024-06-03 20:19 UTC, rstout commented on core/services/ocr2/plugins/ccip/ccipexec/factory.go
> +	return pluginAndInfo.plugin, pluginAndInfo.pluginInfo, err
RetryUntilSuccess will only return if err is nil, do you think it's worth being even more defensive here?

2024-06-03 20:21 UTC, rstout commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	return retry.DoWithData(
Do you think we can choose a max backoff delay that won't constitute as spam? e.g. one minute?

2024-06-03 20:23 UTC, rstout commented on pnpm-lock.yaml
> -lockfileVersion: '6.0'
I wasn't sure, wouldn't this be in .gitignore if that were the case?

2024-06-04 07:54 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/factory.go
> +	return pluginAndInfo.plugin, pluginAndInfo.pluginInfo, err
If the function never returns an error then it should just return a value, no need to return an error.
If it returns an error we should handle it.

2024-06-04 07:55 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/internal/ccipcommon/shortcuts.go
> +	return retry.DoWithData(
Yes, that sounds nice.

2024-06-04 07:56 UTC, dimkouv commented on pnpm-lock.yaml
> -lockfileVersion: '6.0'
Hmm yes, but definitely not related to the changes of this PR, right?

2024-06-04 13:01 UTC, dimkouv commented on pnpm-lock.yaml
> -lockfileVersion: '6.0'
Based on Rens's input you probably need to downgrade to pnpm 7 to be in sync.

2024-06-04 15:14 UTC, rstout commented on pnpm-lock.yaml
> -lockfileVersion: '6.0'
Why version 7 and not 6 (which is listed above)? This is going to trip up new hires, I'm in favor of pushing this with version 9.0 and having people upgrade their pnpm to v9 if they have issues. If there are larger breakages we can revert the this version bump and update the docs to have people use v6 or v7.

2024-06-05 08:38 UTC, dimkouv commented on pnpm-lock.yaml
> -lockfileVersion: '6.0'
I'm not sure @RensR any thoughts?

2024-06-05 15:27 UTC, dimkouv approved these changes

2024-06-05 16:34 UTC, merged