Load improvements - Configurable Network Chaos delay & option to introduce dummy load
smartcontractkit/ccip pull request #915
Opened 2024-05-23 10:34 UTC by AnieeG

## Motivation

## Solution

2024-05-23 19:39 UTC, kalverra requested changes

2024-05-23 19:39 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	tokenUpdateSub := event.Resubscribe(2*time.Hour, func(_ context.Context) (event.Subscription, error) {
Should this be based on something dynamic like how long the test is set to run rather than a magic number?

2024-05-24 08:45 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +	tokenUpdateSub := event.Resubscribe(2*time.Hour, func(_ context.Context) (event.Subscription, error) {
is it not how long it should retry to subscribe if there is an error? does it make sense to set the retrial period for entire test duration?

2024-05-28 13:49 UTC, kalverra requested changes

2024-05-28 13:49 UTC, kalverra commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +						break
So this will only remove a single token from the list of unused or old ones? Can there ever be more than one?

2024-05-28 13:52 UTC, AnieeG commented on integration-tests/ccip-tests/actions/ccip_helpers.go
> +						break
if one token is missing for update , we cannot consider price update is complete. We will have to retry in next ticker

2024-05-28 13:54 UTC, kalverra approved these changes

2024-05-28 14:09 UTC, kalverra approved these changes

2024-05-28 14:28 UTC, merged