Additional Fuzz Tests for EVM2EVMOffRamp
smartcontractkit/ccip pull request #919
Opened 2024-05-23 16:55 UTC by jhweintraub

## Motivation

Add additional fuzz tests in EVM2EVMOffRamp.t.sol to fill in fuzz-testing coverage gaps

## Solution

Added The following tests

Stateless fuzzing:

`getSenderNonce` with and without `i_prevOffRamp`

`getAllRateLimitTokens` & `updateRateLimitTokens`

`_trialExecute` with different messages and token data

2024-05-30 06:06 UTC, matYang requested changes

2024-05-30 06:06 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    message.data = "";
can we also fuzz with data, and verify receiver got the data in the message

2024-05-30 06:06 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +      s_offRamp.trialExecute(message, new bytes[](message.tokenAmounts.length));
ditto, let's also fuzz with offchain token data and verify token pool actually gets that data

2024-05-30 06:06 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +      messages[0].nonce++;
nonce incr logic only applies when`if (message.nonce > 0)`, please cover the scenario where Out of Order delivery (message.nonce == 0) can be interleaved with FIFO delivery, use the fuzzer to arrive at varying interleaving patterns

2024-05-30 06:06 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    for (uint256 x = 0; x < trialExecutions; x++) {
use `i` as opposed to `x`, and we always use pre-increment `++i`

apply to loops below

2024-06-04 20:31 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +import {console2 as console} from "forge-std/console2.sol";
nit: remove console

2024-06-04 20:31 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    message.data = abi.encodePacked(messageData);
nit: curious why `abi.encodePacked` when messageData is already bytes

2024-06-04 20:31 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    //Convert bytes4 into bytes memory to use in the message
nit: //[space]

2024-06-04 20:31 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    Internal.EVM2EVMMessage[] memory messages = _generateBasicMessages();
nit: if you just need 1 message, can you use `_generateAny2EVMMessageNoTokens`

2024-06-04 20:31 UTC, matYang commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    messages[0].nonce = 0;
let's test interleaving OOO messages and FIFO messages, for example:
1. take in uint256 from fuzzer, in range of [2^255, 2^256]
2. for every 1 bit, do OOO
3. for every 0 bit, do FIFO

2024-06-05 06:55 UTC, makramkd commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    messages[0].nonce = 0;
We have a fuzz test `test_Fuzz_InterleavingOrderedAndUnorderedMessages_Success` that does what you're describing, but increasing # of runs sounds fine to me.

2024-06-05 06:59 UTC, makramkd commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +  event Minted(address indexed sender, address indexed recipient, uint256 amount);
I don't think we need to re-define events anymore, they can be "imported", just need to import the relevant contract they're defined in. I wonder if it might be worse for compile times though with more imports.

2024-06-05 14:26 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    message.data = abi.encodePacked(messageData);
that actually might have been left over from some stuff I was testing earlier. In which case it can be removed.

2024-06-05 14:27 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +  event Minted(address indexed sender, address indexed recipient, uint256 amount);
That wasn't my doing and I don't really wanna remove it because of all the other compilation problems that may cause.

2024-06-05 14:30 UTC, jhweintraub commented on contracts/src/v0.8/ccip/test/offRamp/EVM2EVMOffRamp.t.sol
> +    messages[0].nonce = 0;
Sounds like I should leave it as it is then?

2024-06-10 03:16 UTC, matYang approved these changes

2024-06-21 14:43 UTC, closed without merging