CCIP-2371: Add slack thread for posting load test result and fix broken links
smartcontractkit/ccip pull request #920
Opened 2024-05-23 23:42 UTC by b-gopalswami

## Motivation
When there is a failure in a run, there are multiple notifications fired in previous implementation. It's a better to reduce the noise.

## Solution
Create a slack thread approach to collate the reporting per run.

2024-05-24 16:01 UTC, kalverra requested changes

2024-05-24 16:01 UTC, kalverra commented on .github/workflows/ccip-chaos-tests.yml
>    workflow_run:
So load tests will cover this?

2024-05-24 16:01 UTC, kalverra commented on .github/workflows/ccip-chaos-tests.yml
> +    branches: [ ccip-develop, release* ]
Do we want to do this on all release branches? Or only on [tags](https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags)?

2024-05-24 16:01 UTC, kalverra commented on .github/workflows/ccip-load-tests.yml
> +      - release*
Same here about tags vs branches. We'll probably want to restrict it just to when [tags](https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags) get published.

2024-05-24 16:29 UTC, b-gopalswami commented on .github/workflows/ccip-chaos-tests.yml
>    workflow_run:
Yes... this wrokflow runs whenever load test runs.

2024-05-24 16:31 UTC, b-gopalswami commented on .github/workflows/ccip-chaos-tests.yml
> +    branches: [ ccip-develop, release* ]
As this gets triggered when load is running and load has certain push event, do we want to restrict the branches here? If we remove it, it will run whenever load test runs irrespective of the branch in which load test is triggered.

2024-06-12 16:35 UTC, kalverra approved these changes

2024-06-12 20:03 UTC, merged