Zk Overflow in Execution Plugin
smartcontractkit/ccip pull request #947
Opened 2024-06-03 09:37 UTC by 0xnogo

## Motivation

## Solution

2024-06-04 09:27 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	txm struct{} // TODO: replace with actual TXM
You can provide the interface you expect here i.e

```golang
type txm interface {
    FindTxWithIdempotencyKeyPrefix(...)
}
```

You can then mock this out in tests to return whatever value (single, multiple, none, etc.)

2024-06-04 09:27 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		batchCtx.expectedNonces[msg.Sender] = msg.Nonce + 1
Nonce does not always get bumped with OOO execution

2024-06-04 09:27 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		batchCtx.expectedNonces[msg.Sender] = msg.Nonce + 1
Easiest way to check is checking the nonce value, if nonce is 0 then its an OOO message and don't need to bump it.

2024-06-05 07:40 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	txm struct{} // TODO: replace with actual TXM
Good idea ✅

2024-06-05 07:55 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		batchCtx.expectedNonces[msg.Sender] = msg.Nonce + 1
You are right. If the nonce of `m1` is 0, then we should not increment the expected nonce so that if we have `m2` with a nonce != 0, it can pass the nonce check.

Also added a test to reflect it.

2024-06-05 09:00 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		batchCtx.expectedNonces[msg.Sender] = msg.Nonce + 1
Thinking about it, in the `ZKOverflowBatchingStrategy`, the `expectedNonces` doesn't need to be updated as we are only gonna add 1 item to the batch.

@makramkd Which leads to a question for `BestEffortBatchingStrategy` (aka non zk chains): is it expected to use the OOO feature? The reason behind this is whether or not we need to check for nonce > 0.

2024-06-05 10:02 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		batchCtx.expectedNonces[msg.Sender] = msg.Nonce + 1
> is it expected to use the OOO feature?

Its possible for us to update it in the future to take advantage of OOO somehow, yes.

2024-06-11 08:33 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/offramp.go
> +	BatchingStrategyId uint8
Probably not needed as I think this is unsupported now (?)

2024-06-11 08:37 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	statuschecker statuschecker.TransactionStatusChecker
Build failing because of this line

2024-06-11 09:16 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +					batchBuilder.skip(msg, TXMCheckFailed)
We could potentially introduce 2 different skipping status

2024-07-04 10:14 UTC, makramkd commented on .changeset/lucky-hotels-sin.md
Don't need this, can remove

2024-07-04 10:14 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +func (bs *BaseBatchingStrategy) performCommonChecks(
Lets move this closer to the declaration of the `BaseBatchingStrategy` type

2024-07-04 10:16 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +func (bs *BaseBatchingStrategy) performCommonChecks(
Also does this really need to be a method? Why not a free func?

2024-07-04 10:30 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		}
This error seems to be swallowed, why not bubble it up?

2024-07-04 10:30 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +					batchBuilder.skip(msg, TXMCheckFailed)
What does `Finalized` mean here in this context?

2024-07-04 10:30 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +					batchBuilder.skip(msg, TXMCheckFailed)
Also this log is so familiar to the previous one I almost thought they were the same, perhaps make them more distinct?

2024-07-04 10:30 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchCtx *BatchContext,
This is minor but having this as a pointer kinda suggests that the caller intends to use it after calling this method, but looking at the calling code it doesn't really use it. Can this be a non-pointer?

2024-07-04 10:30 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> -
Why did we move this? We'd do it in all batching scenarios no?

2024-07-04 10:30 UTC, makramkd commented on core/services/ocr2/plugins/ccip/transmitter/transmitter.go
> +		return errors.Wrap(err, "skipped OCR transmission, error getting round-robin address")
Prefer `fmt.Errorf` over `errors.Wrap` where possible

2024-07-04 10:30 UTC, makramkd commented on core/services/ocr2/plugins/ccip/transmitter/transmitter.go
> +	if len(txMeta.MessageIDs) > 0 && t.statuschecker != nil {
We only want an idempotency key if len(message_ids) == 1 right?

2024-07-04 10:30 UTC, makramkd commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +//go:generate mockery --quiet --name CCIPTransactionStatusChecker --output ./mocks/ --case=underscore
nit: put this right above the `CCIPTransactionStatusChecker` type decl

2024-07-04 11:41 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchCtx *BatchContext,
`BuildBatch` doesn't modify the state of the BatchingStrategy, so I think you are right, it's better to use the non-pointer value.

2024-07-04 12:11 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		}
In the current logic, we have one occurrence where we are not skipping the item but directly stopping the batching for the report. When getting an error from `gasPriceEstimator`, we are simply returning an empty result (see [code](https://github.com/smartcontractkit/ccip/blob/ccip-develop/core/services/ocr2/plugins/ccip/ccipexec/ocr2.go#L387)).

I decided to be as close as possible to the current logic as I wasn't sure why we decided that. Most probably we are considering this error as fatal and we want to stop the batching logic here for this report?

2024-07-04 12:13 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		}
But it's a surprising behavior. I really don't see why we are returning empty instead of just skipping the item

2024-07-04 12:21 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +					batchBuilder.skip(msg, TXMCheckFailed)
> What does `Finalized` mean here in this context?

Finalized means that the tx has reached finality. I checked with Amit and they will not implement it for now (see [code](https://github.com/smartcontractkit/ccip/blob/6ebc276694fbe5e3dcd16cddd4573fabb3080649/common/txmgr/txmgr.go#L649)).

I guess for now we can just remove it (+ we are not relying on TXM for finality anyway).

2024-07-04 14:02 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/transmitter/transmitter.go
> +	if len(txMeta.MessageIDs) > 0 && t.statuschecker != nil {
Setting the check to `== 1` should be fine as the txm checks are happening on the `ZKBatchingStrategy` path only. So for non-zk, we will simply set it to nil which won't change from the original behavior ([code](https://github.com/smartcontractkit/ccip/blob/6ebc276694fbe5e3dcd16cddd4573fabb3080649/common/txmgr/txmgr.go#L504)).

2024-07-04 14:18 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/offramp.go
> +	BatchingStrategyId uint8
Still required as `// ExecOffchainConfig is the configuration for nodes executing committed CCIP messages (v1.0–v1.2).`

2024-07-04 14:27 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> -
Yes, we would need to run this in all batching scenarios. I decided to move it to the batching file as it was not used directly in `ocr2.go`, with the downside that it will have to be copied in all `BuildBatch` methods.

I don't have a strong opinion on it. I'll just move it back.

2024-07-05 13:04 UTC, makramkd approved these changes

2024-07-11 10:57 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/factory.go
> +		}
Small nit: better moving this to a constructor `NewBatchingStrategy(strategyID int)`?

2024-07-11 12:28 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		batchCtx.availableDataLen -= len(msg.Data)
I'm wondering if there's a way to also de-dup this

2024-07-11 12:28 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +			"Message added to ZKOverflow execution batch",
I think the logged msg is a bit wrong. Some nop might look at this an feel that something's wrong

2024-07-11 12:28 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		// Check if the messsage is overflown using TXM
Let's say we have 16 nodes and one overflowing message:
1. In the first round all 16 nodes will observe that message
2. one of them will transmit it and its txm will have the fatal status
3. in the next round the other 15 nodes will still observe that same msg and this one node will observe something else
4. consensus on 15 nodes -> ccip retries the failing msg
5. we repeat until consensus is that this msg is overflowing

is this flow correct?

2024-07-11 12:46 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/offramp.go
> +	BatchingStrategyId uint8
1.0 lanes are no longer used, but remember that 1.2 offramp implementation inherits some of the behaviour directly from 1.0

2024-07-11 12:46 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_2_0/offramp_test.go
> +				return
You don't need a return stmt if you wrap code within `if/else` blocks

2024-07-11 12:46 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +type BatchContext struct {
It would be easier to read if decouple that PR into two smaller PRs:
* introducing BatchContext and `batchingStrategy` - it would be basically refactoring of existing code, because there would always be a single `batchingStrategy` that is always used (no if/else logic required)
* introducing zkOverflow dedicated logic 

Right now logic related to zkOverflow and large refactoring introducing batching strategies interleaves with each other which makes it harder to review and easier to make a bug in the code.

2024-07-11 12:46 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		statuses, _, err := bs.statuschecker.CheckMessageStatus(batchCtx.ctx, hexutil.Encode(msg.MessageID[:]))
What's the overhead of that operation? Is it going to perform RPC/DB call per every message? If so, then it might become a huge bottleneck and should be done outside of the loop in a batch manner (one call for all messages within a Commit Root). Also should we cache this information or always ask TXM about the latest state? Can we assume that if a state is set to `Fatal` or `Finalized` it's never going to change?

2024-07-11 12:46 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +					batchBuilder.skip(msg, TXMCheckFailed)
What's the difference between Fatal and Finalized?

2024-07-11 12:46 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/factory.go
> +		batchingStrategyId := 0 // TODO: remove this line when the above TODO is done
Keep in mind that it has to be backward compatible, meaning it should also work with 1.2 contracts/config that don't have this field present

2024-07-11 12:50 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		// Check if the messsage is overflown using TXM
In the case of S = [1, 1, 1, ...], it is exactly what will happen. The DON will need a couple of rounds before reaching a consensus (> f).

Some parameters we could play with to increase the time to detect:
* reduce the `deltaRound` to produce reports frequently (with OCR2 it can be reduced to 0)
* Increase parallel transmissions at deltaStage 0 with something like S = [2F+1, 1, 1, 1, 1]

The usage of the inflight status is a minor improvement in wrt the DOS aspect as it is only providing NOP level visibility.

2024-07-11 12:52 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		// Check if the messsage is overflown using TXM
You can find more details in this [doc](https://docs.google.com/document/d/12DVyVM1k83rjG8IILsDSHyJN8AgBJJHa87R3pIYwajY/edit#heading=h.22gxxxntz5o8). But essentially we want to load test it under different parameters and see our level of protection.

2024-07-11 13:29 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchCtx *BatchContext,
It's a big object, always tempting to pass by reference in that case

2024-07-11 14:06 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchCtx.tokenDataRemainingDuration -= elapsed
Thinking out loud here, I realize this old logic that you moved during the rafactor. I'll create a followup ticket.

The context passed into BuildBatch should be created with a timeout according to the duration. That way there would be no need to keep track of time or time elapsed. In addition if GetTokenData performed the `len(msg.TokenAmounts) == 0` check (which it should anyway), the `getTokenDataWithTimeout` helper function could go away completely and be replaced with `tokenData, err1 := r.tokenDataWorker.GetMsgTokenData(ctxTimeout, msg)`

2024-07-11 14:11 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchCtx.tokenDataRemainingDuration -= elapsed
[Tech debt ticket.](https://smartcontract-it.atlassian.net/browse/CCIP-2825)

2024-07-11 16:07 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/factory.go
> +		batchingStrategyId := 0 // TODO: remove this line when the above TODO is done
Backward compatibility has been tested [here](https://github.com/smartcontractkit/ccip/blob/e32acaa4e58eb3cfb6ac9f55348e0c56cd2a1b39/core/services/ocr2/plugins/ccip/internal/ccipdata/v1_2_0/offramp_test.go#L168). Basically with a json without the field, we are going to serialize it as `batchingStrategyId = 0`.

2024-07-11 16:32 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		statuses, _, err := bs.statuschecker.CheckMessageStatus(batchCtx.ctx, hexutil.Encode(msg.MessageID[:]))
This is the result of a mitigation we designed with the TXM team. We are going to check the status N times for a messages to get all the statuses (including the retries).

The cache optimization was identified but we decided to start with this approach to be tested first. As we don't have any idea on the amount of retries per message, it might be an overkill to go straight into that optimization.

The batching call would require a new endpoint on TXM side. It is worth checking the effort of their side.

2024-07-11 16:35 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		statuses, _, err := bs.statuschecker.CheckMessageStatus(batchCtx.ctx, hexutil.Encode(msg.MessageID[:]))
@amit-momin Do you have any plan for developing an endpoint for batch calls? Something like providing a slice of key and returning all the statuses of the item in the slice.

In general, it would be great to have your review on this one. Main focus points:
- status filtering logic: are we making a good usage of the status?
- performance concerns with the incremental msgId querying

2024-07-11 16:42 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +type BatchContext struct {
I agree with that. Considering we are very close to finish this up I'll stick with this PR. But I will pay attention to splitting up more cleverly PRs in the future.

2024-07-11 17:13 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchCtx.tokenDataRemainingDuration -= elapsed
Good catch. The batching logic needs such improvement to make ti more digestible and less error-prone.

2024-07-11 18:15 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		batchingStrategy = &BestEffortBatchingStrategy{} // Default strategy
The default case should probably be an error. I'm trying to think about when the strategy could be set to something other than 0 or 1, all I can come up with is we introduce a 3rd option and the user hasn't updated the software yet.

2024-07-12 11:55 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		}
Yeah, I do agree, current behavior is brittle, we shouldn't swallow an error and instead skip a message and log its state as "can't estimate USD cost" or sth like this

@0xnogo can you please create a ticket for that? It could be nice onboarding task

2024-07-12 11:55 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	return true, "", messageMaxGas, tokenData, msgValue, nil
I think this `bool` item is not needed because information on whether the message is valid or not is already present in the returned data and it's hidden under `""` :D 

Just thinking out loud, but how about having const like `MessageSuccesfullyValidated` and returning that instead of `""` and then just checking for that in the calling fun? (could be different naming but you get the idea)

```go
func performCommonChecks(...)
    // ...
    return MessageSuccesfullyValidated, messageMaxGas, tokenData, msgValue, nil
}

func (m messageStatus) ShouldAddToBatch() bool {
	return m == MessageSuccesfullyValidated
}

status, messageMaxGas, tokenData, msgValue, err := performCommonChecks(ctx, batchCtx, msg, msgLggr)
if !status.ShouldAddToBatch() {
			batchBuilder.skip(msg, status)
			continue
		}
}

```

Is it more readable or less readable right now? Less places to make a typo because you don't need to return `true` / `false` for every condition

2024-07-12 11:55 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		inflightSeqNums := getInflightSeqNums(batchCtx.inflight)
You only need to build it once, right? So it should be done outside of the loop not inside

2024-07-12 11:55 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchBuilder := newBatchBuildContainer(1)
Hmm, I wonder if it really makes sense to a have dedicated magic number for zk execution here.
```go
func newBatchBuildContainer(capacity int) *batchBuildContainer {
	return &batchBuildContainer{
		batch:    make([]ccip.ObservedMessage, 0, capacity),
		statuses: make([]messageExecStatus, 0, capacity),
	}
}
```

You still might end up going through the entire list of messages to skip them and execute the last one from the list, so `statuses` would be as long as `seqRequestwithMeta`. Actually, it's inevitable, because you execute in a round only single message so executing last message from the batch would be
```
m1 - skip, m2 - skip, m3 - skip, m4 - execute
```

I wonder if passing `len(seqnRequestsWithMeta)` wouldn't be easier to read even if we allocate a bit more memory than required. It would be the same as for default batching strategy, so easier to understand. Also batch can't be larger than 256 elements

2024-07-12 14:36 UTC, amit-momin requested changes

2024-07-12 14:36 UTC, amit-momin commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +		}
I think this error handling could cause some problems. The error field here is multi-purposed which could be causing some confusion. It could point to an unfound tx but it's also used to return the error that caused a tx's status to be failed or fatal. I'm also worried about using the explicit error message here since this is just in the EVM TXM. Other chains could return a different error message which could become a problem in a ChainWriter world.

2024-07-12 14:36 UTC, amit-momin commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +		}
I think there are 3 different states you would be interested in here when `err != nil`
```
if err != nil {
  if status == Unknown {
    // Tx not found
  } else if status == Failed {
    // Found a status but not a final one so can continue the search
  } else if status == Fatal {
    // Found a final status so can break??
  }
}
```
Side note: To avoid unnecessary calls, should this code also break if a `Finalized` status is found?
[Statuses](https://github.com/smartcontractkit/chainlink-common/blob/552fe1f9c0551ff68f71cb5abe0b85d51ad034aa/pkg/types/chain_writer.go#L35-L41)

2024-07-12 14:36 UTC, amit-momin commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		statuses, _, err := bs.statuschecker.CheckMessageStatus(batchCtx.ctx, hexutil.Encode(msg.MessageID[:]))
These are DB reads on the TXM side so it's not as costly of a query as an RPC call. We currently don't have plans to support a batch endpoint. To add one would be a wider conversation with the ChainWriter devs since this is something we're supporting through that interface too.

2024-07-12 16:00 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		inflightSeqNums := getInflightSeqNums(batchCtx.inflight)
Good catch

2024-07-12 16:00 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	batchBuilder := newBatchBuildContainer(1)
The optimization doesn't weight the readability gains, I'm in favor of using the same number.

2024-07-12 18:21 UTC, 0xnogo commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +		}
Here we are only looking to break the loop when the key is not found. As you mentioned an error could also mean something `Fatal`/`Failed` which is explaining why we do the error message check.

I understood that `Unknown` could also mean that the tx is `in progress` or `unstarted`, that's why I didn't decided to have it as a break condition.

2024-07-12 18:26 UTC, 0xnogo commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +		}
I am basically trying to break when:
```
if err != nil {
   return status, fmt.Errorf("failed to find transaction with IdempotencyKey %s: %w", transactionID, err)
}
// This check is required since a no-rows error returns nil err
if tx == nil {
   return status, fmt.Errorf("failed to find transaction with IdempotencyKey %s", transactionID)
}
```

And collecting all the statuses on the other cases. In `batching.go`, we are looping through the statuses and snoozing the message if we found a `Fatal`.

```
			for _, s := range statuses {
				if s == types.Fatal {
					msgLggr.Infow("Skipping message - TXM status is fatal")
					batchBuilder.skip(msg, TXMFatalStatus)
					haveFatalStatus = true
					break
				}
			}
			}
```

`Finalized` is not implemented so we decided to discard it.
`Failed` is a valid case to retry.
`Unknown` might be a candidate to snooze if it exclusively means that the tx is not found.

2024-07-12 18:38 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	return true, "", messageMaxGas, tokenData, msgValue, nil
> I think this bool item is not needed because information on whether the message is valid or not is already present in the returned data and it's hidden under "" :D

Not exactly as we have a case without any error message string that is unvalid

```
	execCostUsd, err1 := batchCtx.gasPriceEstimator.EstimateMsgCostUSD(batchCtx.gasPrice, dstWrappedNativePrice, msg)
	if err1 != nil {
		msgLggr.Errorw("Failed to estimate message cost USD", "err", err1)
		return false, "", 0, nil, nil, errors.New("failed to estimate message cost USD")
	}
```

It's related to this weird return we are doing instead of returning an err.

2024-07-12 18:51 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +	return true, "", messageMaxGas, tokenData, msgValue, nil
We can still implement the changes we are suggesting as it's making the code more readable.

For the `gasPriceEstimator`, we can continue to return `""`.

2024-07-15 10:42 UTC, mateusz-sekara commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +		statuses, _, err := bs.statuschecker.CheckMessageStatus(batchCtx.ctx, hexutil.Encode(msg.MessageID[:]))
> These are DB reads on the TXM side so it's not as costly of a query as an RPC call.

@amit-momin Do we have some data to back this up? During load tests, we've seen a couple of TXM db queries taking extremely long to finish (longer than RPC calls). Is this a new query or an existing one? Do we actually track the duration of that query?

2024-07-22 20:52 UTC, amit-momin commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +		}
In that case, I think the condition may need to just be `err != nil && status == Unknown`. If the Unknown status is really pointing to Unstarted or Inprogress, err would be nil since we found the transaction.

2024-07-25 11:24 UTC, 0xnogo commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +		}
Valid. Updated the logic

2024-07-29 14:45 UTC, winder reviewed
This PR is pretty difficult to review with the refactoring mixed in with new features. I attempted to make a first pass and left a few questions. Overall the changes mostly make sense, I'm most unsure about the transmitter and message status checking abstraction.

2024-07-29 14:45 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +			msgLggr.Infow("No final status found for message, adding to batch")
Message is not quite right, it's not being added until a couple more checks to do

2024-07-29 14:45 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +			msgLggr.Infow("No status found for message, adding to batch")
Would be good to include messageID in these logs. Also it's not being added until a couple more checks are done.

2024-07-29 14:45 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/batching_test.go
> +			name:                   "message batched when unconfrimed or failed",
```suggestion
			name:                   "message batched when unconfirmed or failed",
```

2024-07-29 14:45 UTC, winder commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +type GetTransactionStatusFunc func(ctx context.Context, transactionID string) (commontypes.TransactionStatus, error)
Why don't you use `TxmStatusChecker` instead of defining a new type?

2024-07-29 14:45 UTC, winder commented on core/services/ocr2/plugins/ccip/transmitter/transmitter.go
> +	}
Call `NewTransmitter` instead of duplicating the error handling

2024-07-29 14:45 UTC, winder commented on core/services/relay/evm/evm.go
> +			statuschecker.NewTxmStatusChecker(configWatcher.chain.TxManager().GetTransactionStatus),
`configWatcher.chain.TxManager()` is the first argument. Could the status checker be created internal to the `NewTransmitter` function?

2024-07-29 14:45 UTC, winder commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +func (tsc *TxmStatusChecker) CheckMessageStatus(ctx context.Context, msgID string) ([]types.TransactionStatus, int, error) {
Why is a counter appended to the message ID? Just a way to cache multiple transactions in a KV map or something else?

2024-07-29 14:54 UTC, 0xnogo commented on core/services/relay/evm/statuschecker/txm_status_checker.go
> +func (tsc *TxmStatusChecker) CheckMessageStatus(ctx context.Context, msgID string) ([]types.TransactionStatus, int, error) {
When creating a tx using the TXM, we are setting an `idempotency key`, which means if we want a message to be retried each key needs to be unique (otherwise txm will noop the tx). `msgId-counter` will allow us to set a unique idempotency key per msg id per retry.

On the other side, this key is used to retrieve the status of the message. We decided to not use a cache to keep the exec plugin as stateless as possible. That's why we are getting all the statuses here.

2024-07-29 15:48 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/ocr2.go
> +type GetTransactionStatusFunc func(ctx context.Context, transactionID string) (commontypes.TransactionStatus, error)
We are right. I think we can even use the `CCIPTransactionStatusChecker` interface direclty.

2024-07-29 16:05 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +			msgLggr.Infow("No status found for message, adding to batch")
Good catch. Fixing

2024-07-30 15:10 UTC, makramkd commented on core/services/ocr2/delegate.go
> +		if err2 != nil {
Does this need to be `err2`? I believe we only need a different var name if there's a nested scope situation which doesn't seem to be the case here. Can we switch to just `err`? cc @patrickhuie19

2024-07-30 15:10 UTC, makramkd commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +			msgLggr.Infow("No final status found for message - proceeding with checks", "message", msgId)
Should this be

```suggestion
			msgLggr.Infow("No fatal status found for message - proceeding with checks", "message", msgId)
```

2024-07-30 15:13 UTC, 0xnogo commented on core/services/ocr2/delegate.go
> +		if err2 != nil {
You are right. We only need different variable names for errors if there is a nested scope situation.

2024-07-30 15:21 UTC, 0xnogo commented on core/services/ocr2/plugins/ccip/ccipexec/batching.go
> +			msgLggr.Infow("No final status found for message - proceeding with checks", "message", msgId)
good catch

2024-07-30 15:32 UTC, winder approved these changes

2024-07-30 16:18 UTC, merged