Feature/ccip 1250
smartcontractkit/ccip pull request #957
Opened 2024-06-03 20:10 UTC by patrickhuie19

## Motivation

## Solution

2024-06-05 20:47 UTC, krehermann commented on .github/workflows/integration-tests.yml
> +  ## Solana Section
what's this all about? seem out of scope. can it be a seperate PR?

2024-06-05 20:47 UTC, krehermann commented on core/capabilities/streams/codec.go
> +package streams
what's going on here? seems independent of the change you need to make? is it a weird dep issue b/c of the forked repo?

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/evm.go
> +	if commitPluginConfig.IsSourceProvider {
add comment about why you can bail out early here in the src case

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/commit_provider.go
> +type SrcCommitProvider struct {
add throughout code comment about the distinction between SrcCommtProvider and Dest, including reasoning for the separation.

on unimplemented methods of each add a code comment tell users they are doing the wrong thing

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/evm.go
> +	ctx := context.Background()
you have some TODOs in the code re:context, do you need that here too?

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	// gasEstimator gas.EvmFeeEstimator,
remove?

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	jobID                                  string
jobId seems wrong. i don't think the provider will know about jobs unless we are violating some boundaries

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	//TODO implement me
add ticket reference

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	panic("NewOffRampReader called on SrcExecProvider. Valid on DstExecProvider.")
return an error instead? not sure what's better

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +		return nil, errors.Wrap(err, "failed to parse USDC attestation API")
prefer fmt.Errorf("%w") that errors pkg is deprecated

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	//TODO implement me
ticket ref

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	//TODO implement me
ticket ref

2024-06-05 20:47 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	//TODO implement me
ticket ref

2024-06-05 20:47 UTC, krehermann commented on core/cmd/solana_chains_commands_test.go
> -	cfg := solana.TOMLConfig{
why change?

2024-06-06 15:52 UTC, patrickhuie19 commented on core/capabilities/streams/codec.go
> +package streams
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in `chainlink-common`, and some extra baggage came along with those commits.

2024-06-06 15:52 UTC, patrickhuie19 commented on .github/workflows/integration-tests.yml
> +  ## Solana Section
(Copied from the comment below)
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in `chainlink-common`, and some extra baggage came along with those commits.

2024-06-06 15:53 UTC, patrickhuie19 commented on core/services/relay/evm/evm.go
> +	ctx := context.Background()
This is from a cherry-pick, so yes, but it should be added to core.

2024-06-06 15:54 UTC, patrickhuie19 commented on core/services/relay/evm/exec_provider.go
> +	// gasEstimator gas.EvmFeeEstimator,
Will do. Left over from when I originally planned to tackle `NewCommitStoreReader` in this scope.

2024-06-06 15:56 UTC, patrickhuie19 commented on core/services/relay/evm/exec_provider.go
> +	jobID                                  string
Yea, I didn't like it as well, but it keeps the scope at least for this PR reduced. I can check how it's consumed by the internal CCIP methods, but if it's just used by a logger that should be easy enough to add to the logger (`lggr = lggr.With("JobID: ", jobID`) up the stack and remove this plumbing.

2024-06-06 15:58 UTC, patrickhuie19 commented on core/services/relay/evm/exec_provider.go
> +	panic("NewOffRampReader called on SrcExecProvider. Valid on DstExecProvider.")
I was 50-50 on this as well. Either works for me. Somewhere in the CreateJob flow there's a leak in error propagation and the stack traces get cut off. IDK why yet. The nice thing with the panic is that they're there. 

^ Even using that reasoning to me seems like a dev feature rather than a prod best practice, so perhaps the error is better.

2024-06-06 15:59 UTC, patrickhuie19 commented on core/services/relay/evm/exec_provider.go
> +		return nil, errors.Wrap(err, "failed to parse USDC attestation API")
Ok, will do. Goland didn't highlight that to me 🤦

2024-06-06 16:00 UTC, patrickhuie19 commented on core/cmd/solana_chains_commands_test.go
> -	cfg := solana.TOMLConfig{
The solana module was changed - TOML config was moved from the top level Solana module to a config module

2024-06-06 16:57 UTC, patrickhuie19 commented on core/capabilities/syncer.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:57 UTC, patrickhuie19 commented on core/cmd/shell_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:57 UTC, patrickhuie19 commented on core/cmd/solana_chains_commands_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:57 UTC, patrickhuie19 commented on core/cmd/solana_node_commands_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:57 UTC, patrickhuie19 commented on core/cmd/solana_transaction_commands_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:57 UTC, patrickhuie19 commented on core/config/docs/docs_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:57 UTC, patrickhuie19 commented on core/services/chainlink/config.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:58 UTC, patrickhuie19 commented on core/services/chainlink/config_general.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:58 UTC, patrickhuie19 commented on core/services/chainlink/config_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:58 UTC, patrickhuie19 commented on core/services/chainlink/mocks/relayer_chain_interoperators.go
> +func (f *FakeRelayerChainInteroperators) GetAll() map[types.RelayID]loop.Relayer {
No longer needed. I'll clean up.

2024-06-06 16:59 UTC, patrickhuie19 commented on core/services/chainlink/relayer_chain_interoperators_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:59 UTC, patrickhuie19 commented on core/services/chainlink/relayer_factory.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 16:59 UTC, patrickhuie19 commented on core/services/chainlink/types.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 17:03 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/exportinternal.go
Many CCIP methods are internal (i.e. behind an `/internal` path that go does not allow to be exported). This approach kicks a two part can down the road. These parts are:

1. Define chain-agnostic versions of these internal functions
2. Properly move over EVM specific CCIP code to the `chainlink-evm` repo

2024-06-06 17:04 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/price_registry.go
Artifact of a merge

2024-06-06 17:05 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/internal/oraclelib/backfilled_oracle.go
`BackfilledOracle` had a direct dependency on Log Poller and called replay. `ChainAgnosticBackFilledOracle` does this indirectly through the provider `Start` method.

2024-06-06 17:05 UTC, patrickhuie19 commented on core/services/ocr2/plugins/generic/relayerset_test.go
because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 17:06 UTC, patrickhuie19 commented on core/services/ocr2/validate/validate.go
I'm guilty of this as well, but we sometimes find it hard to stick to canonical/consistent usage of a term. This particular offense is mixed usage of `Execution` and `Exec`, which I've tried to push all usages toward `Exec`.

2024-06-06 17:08 UTC, patrickhuie19 commented on core/services/relay/evm/chain_reader_test.go
from a merge

2024-06-06 17:08 UTC, patrickhuie19 commented on core/services/relay/evm/commit_provider.go
> +type SrcCommitProvider struct {
Updating panics to errors so that the relayer process does not crash.

2024-06-06 17:09 UTC, patrickhuie19 commented on core/services/relay/evm/exec_provider.go
> +	panic("NewOffRampReader called on SrcExecProvider. Valid on DstExecProvider.")
Update after convo: Updating panics to errors so that the relayer process does not crash.

2024-06-06 17:09 UTC, patrickhuie19 commented on core/services/relay/evm/functions.go
from merge

2024-06-06 17:09 UTC, patrickhuie19 commented on core/services/relay/evm/mercury_provider.go
from merge

2024-06-06 17:10 UTC, patrickhuie19 commented on core/services/relay/evm/ocr2keeper.go
> +func (c *ocr2keeperProvider) ChainReader() commontypes.ContractReader {
from merge

2024-06-06 17:10 UTC, patrickhuie19 commented on core/services/relay/evm/ocr2vrf.go
> +func (c *dkgProvider) ChainReader() commontypes.ContractReader {
from merge

2024-06-06 17:10 UTC, patrickhuie19 commented on core/services/relay/evm/ocr2vrf.go
> +func (c *ocr2vrfProvider) ChainReader() commontypes.ContractReader {
from merge

2024-06-06 17:10 UTC, patrickhuie19 commented on core/services/relay/evm/plugin_provider.go
from merge

2024-06-06 17:10 UTC, patrickhuie19 commented on core/utils/config/validate.go
from merge

2024-06-06 17:10 UTC, patrickhuie19 commented on core/web/solana_chains_controller_test.go
from merge

2024-06-06 17:11 UTC, patrickhuie19 commented on core/web/testutils/mock_relayer.go
from merge

2024-06-06 17:11 UTC, patrickhuie19 commented on plugins/medianpoc/plugin_test.go
from merge, but shouldn't the method name be `ContractReader`? 🤷

2024-06-06 18:00 UTC, patrickhuie19 commented on core/capabilities/streams/codec_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/capabilities/syncer.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/cmd/shell_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/cmd/solana_node_commands_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/cmd/solana_transaction_commands_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/config/docs/docs_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/services/chainlink/config.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/services/chainlink/config_general.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/services/chainlink/config_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:01 UTC, patrickhuie19 commented on core/services/chainlink/relayer_chain_interoperators_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:02 UTC, patrickhuie19 commented on core/services/chainlink/relayer_factory.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:02 UTC, patrickhuie19 commented on core/services/chainlink/types.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:02 UTC, patrickhuie19 commented on core/services/ocr2/plugins/generic/relayerset_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:02 UTC, patrickhuie19 commented on core/services/ocr2/plugins/mercury/plugin_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:03 UTC, krehermann commented on core/services/ocr2/delegate.go
> +	GetAll() map[types.RelayID]loop.Relayer
is this your change or a cherry pick consequence?

if you it's yours then prefer List()

2024-06-06 18:03 UTC, patrickhuie19 commented on core/services/relay/evm/chain_reader.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:03 UTC, patrickhuie19 commented on core/services/relay/evm/functions.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:03 UTC, patrickhuie19 commented on core/services/relay/evm/mercury_provider.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:03 UTC, patrickhuie19 commented on plugins/medianpoc/plugin_test.go
Yea, it's because of the fork. I needed to cherry-pick some commits to satisfy type changes in chainlink-common, and some extra baggage came along with those commits.

2024-06-06 18:11 UTC, krehermann commented on core/services/relay/evm/commit_provider.go
> +	return nil
these will cause nil panics somewhere down the road.

what do you think of implementing an 'error only implementation' for this and other interfaces. you could construct it with a string (in this case "OffchainConfigDigester called on SrcCommitProvider. Valid on DstCommitProvider." and add that string to all the method impl errors

2024-06-06 18:12 UTC, krehermann commented on core/services/relay/evm/commit_provider.go
> +	return nil
return empty map to avoid nil panic downstream

2024-06-06 18:13 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	jobID                                  string
ok, please add a TODO and ticket reference

2024-06-06 18:14 UTC, krehermann commented on core/services/relay/evm/exec_provider.go
> +	return nil
same comment about downstream nil panics

2024-06-07 12:06 UTC, dimkouv requested changes

2024-06-07 12:06 UTC, dimkouv commented on .github/workflows/integration-tests.yml
>          with:
Let's fix failing ci steps

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	GetAll() map[types.RelayID]loop.Relayer
There are two identical methods, one returns an error and one not. What's the diff?
```
GetAll() map[types.RelayID]loop.Relayer
GetIDToRelayerMap() (map[types.RelayID]loop.Relayer, error)
```

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	// Write PluginConfig bytes to send source/dest relayer provider + info outside of top level rargs/pargs over the wire
`newServicesCCIPCommit()` became big.
Maybe better to split in functions?

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	// Write PluginConfig bytes to send source/dest relayer provider + info outside of top level rargs/pargs over the wire
Maybe
```
srcProvider = getSourceProvider(...)
dstProvider = getDestProvider(...)
```

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +			ContractID:   spec.ContractID,
So this is commit store address, which exists on destination.
But we initialize the source chain provider. So essentially this contract id (address) does not exist on source.

Is this a `hack` to bypass the way providers are designed? From my understanding relayers/providers were designed with plugin running on a single chain.

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	return ccipcommit.NewCommitServices2(ctx, srcProvider, dstProvider, srcChain, dstChain, d.legacyChains, jb, lggr, d.pipelineRunner, oracleArgsNoPlugin, d.isNewlyCreatedJob, int64(srcChainID), dstCha
should we rename
`func NewCommitServices2`
to
`func NewCommitServices`
?

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	return ccipcommit.NewCommitServices2(ctx, srcProvider, dstProvider, srcChain, dstChain, d.legacyChains, jb, lggr, d.pipelineRunner, oracleArgsNoPlugin, d.isNewlyCreatedJob, int64(srcChainID), dstCha
old `NewCommitServices` is not used

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	return ccipcommit.NewCommitServices2(ctx, srcProvider, dstProvider, srcChain, dstChain, d.legacyChains, jb, lggr, d.pipelineRunner, oracleArgsNoPlugin, d.isNewlyCreatedJob, int64(srcChainID), dstCha
or is this PR still draft?

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +func ccipCommitProviderTypeToPluginConfig(isSourceProvider bool, sourceStartBlock uint64, destStartBlock uint64) ([]byte, error) {
maybe rename this function?
it's a simple constructor that returns json bytes.

maybe refactor to be used like this:
```
cfg, err := newCommitPluginConfig(true, 123, 321).Encode()
```

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	if err != nil {
this is always false

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	offRampConfig, err := offRampReader.GetStaticConfig(context.Background())
Forgot to use `ctx` ?

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +		return nil, errors.Wrap(err, "open source chain")
💯 'open source chain' #fosdem

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	staticConfig2, err := ccipdata.FetchCommitStoreStaticConfig(commitStoreAddress, dstChain.Client())
Why do we do this? We already have the static config now

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	sourceNative, err := srcProvider.SourceNativeToken(ctx, onRampRouterAddr)
no errcheck

2024-06-07 12:06 UTC, dimkouv commented on core/services/ocr2/plugins/ccip/ccipexec/initializers.go
> +	offRampAddress2, err := offRampReader.Address(ctx)
yes

2024-06-07 13:21 UTC, krehermann commented on core/services/ocr2/delegate.go
> +	GetAll() map[types.RelayID]loop.Relayer
good catch, yes, this this should be removed. i misread the return val and thought it was a slice. use the existing method

2024-06-07 13:24 UTC, krehermann commented on core/services/ocr2/delegate.go
> +	if err != nil {
let's hope so :) but if unchecked and given a bad config, this will panic which is much worse than an explicit check

2024-06-07 13:27 UTC, krehermann commented on core/services/ocr2/delegate.go
> +		return nil, errors.Wrap(err, "create offRampReader")
stop using errors.Wrap in new code. it's deprecated.

use fmt.Errorf("%w") here and elsewhere

2024-06-07 15:08 UTC, patrickhuie19 commented on core/services/ocr2/delegate.go
> +			ContractID:   spec.ContractID,
Yea, that's right - we need the dest provider to instantiate the src provider. I can however pass an empty string to `ContractID`. I think that's what you suggested offline.

2024-06-07 15:11 UTC, patrickhuie19 commented on core/services/ocr2/delegate.go
> +	return ccipcommit.NewCommitServices2(ctx, srcProvider, dstProvider, srcChain, dstChain, d.legacyChains, jb, lggr, d.pipelineRunner, oracleArgsNoPlugin, d.isNewlyCreatedJob, int64(srcChainID), dstCha
I'll remove the dead code 😅

2024-06-07 15:11 UTC, patrickhuie19 commented on core/services/ocr2/delegate.go
> +func ccipCommitProviderTypeToPluginConfig(isSourceProvider bool, sourceStartBlock uint64, destStartBlock uint64) ([]byte, error) {
Nice, I like this better. I did not like the name as well.

2024-06-07 15:17 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/ccipcommit/initializers.go
> +	staticConfig2, err := ccipdata.FetchCommitStoreStaticConfig(commitStoreAddress, dstChain.Client())
Dead code left over from testing. Removed

2024-06-07 15:18 UTC, patrickhuie19 commented on core/services/ocr2/delegate.go
> +		return nil, errors.Wrap(err, "open source chain")
🥞

2024-06-07 15:18 UTC, patrickhuie19 commented on core/services/ocr2/delegate.go
> +	offRampConfig, err := offRampReader.GetStaticConfig(context.Background())
Good catch, thank you

2024-06-07 15:22 UTC, patrickhuie19 commented on core/services/ocr2/delegate.go
> +	GetAll() map[types.RelayID]loop.Relayer
Yup, sorry. `List` I don't think allows you to get all the relayers without knowing the relayer IDs ahead of time, and at one point I thought I could get the src chain ID from the CCIP job spec and thus filter the relayers. Not needed now and the right call is probably to allow a `nil` or empty input arg to `List` that will give you everything.

2024-06-07 18:24 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/ccipexec/initializers.go
> +	offRampAddress2, err := offRampReader.Address(ctx)
Removed all this code

2024-06-11 07:10 UTC, makramkd requested changes, later dismissed
in order to avoid getting the same cherry picked commits twice in the git history lets merge core first and then hopefully this PR diff will be significantly cleaner. haven't reviewed the full set of changes yet.

lots of goimports required on many files as well

2024-06-11 07:10 UTC, makramkd commented on core/services/ocr2/delegate.go
> +	"strconv"
gotta run `goimports` here

2024-06-11 07:10 UTC, makramkd commented on core/services/ocr2/plugins/ccip/exportinternal.go
Wasn't this code in chainlink-common?

2024-06-11 07:10 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/ccipdata/batchreader/token_pool_batch_reader.go
> +	"github.com/smartcontractkit/chainlink/v2/core/services/ocr2/plugins/ccip/internal/rpclib"
goimports

2024-06-11 07:10 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/price_registry.go
> +	panic("implement me")
Don't think this should ever panic but return an unimplemented error

2024-06-11 07:10 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/oraclelib/backfilled_oracle.go
> +		srcReplayErr := r.srcProvider.Start(ctx)
This opaque interface doesn't tell me anything about this actually doing a replay. Is there a way to avoid this or are we doomed to use opaque interfaces that we expect to do specific things?

2024-06-11 07:10 UTC, makramkd commented on core/services/ocr2/plugins/ccip/internal/oraclelib/backfilled_oracle.go
> +func NewChainAgnosticBackFilledOracle(lggr logger.Logger, srcProvider services.ServiceCtx, dstProvider services.ServiceCtx, oracle job.ServiceCtx) *ChainAgnosticBackFilledOracle {
This code is copy/pasted from above - any way to reduce duplication?

2024-06-11 07:10 UTC, makramkd commented on core/services/relay/evm/evm.go
> +func (r *Relayer) NewCCIPCommitProvider(rargs commontypes.RelayArgs, pargs commontypes.PluginArgs) (commontypes.CCIPCommitProvider, error) {
Can we put this in a new file so its easily searchable / findable, core/services/relay/evm/ccip.go maybe?

2024-06-11 12:09 UTC, patrickhuie19 commented on core/services/ocr2/delegate.go
> +	"strconv"
wdym/what are you looking for? I did run `gofmt -w $(git diff origin/HEAD HEAD --name-only) && goimports -local github.com/smartcontractkit/chainlink -w $(git diff origin/HEAD HEAD --name-only)` on this commit, which I figure would catch everything.

2024-06-11 12:11 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/exportinternal.go
Not that I'm aware of (maybe @dimkouv) - I'm not sure how it could live in chainlink-common. This is an unblock before CCIP merges evm specific code to `chainlink-evm`.

2024-06-11 12:11 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/internal/ccipdata/v1_0_0/price_registry.go
> +	panic("implement me")
Now redundant after a merge; removed

2024-06-11 12:16 UTC, patrickhuie19 commented on core/services/ocr2/plugins/ccip/internal/oraclelib/backfilled_oracle.go
> +		srcReplayErr := r.srcProvider.Start(ctx)
Hmm - we could add another provider method to do the replay. One data point to me that suggests we keep this approach is that we'll have to handle https://github.com/smartcontractkit/ccip/blob/ccip-develop/core/services/ocr2/plugins/ccip/ccipcommit/initializers.go#L91, which I was expecting to implement in the `Close` method of the provider.

2024-06-11 12:39 UTC, makramkd commented on core/services/ocr2/delegate.go
> +	"strconv"
You have standard library imports mixed with third party lib imports

2024-06-11 12:40 UTC, patrickhuie19 commented on core/services/relay/evm/evm.go
> +func (r *Relayer) NewCCIPCommitProvider(rargs commontypes.RelayArgs, pargs commontypes.PluginArgs) (commontypes.CCIPCommitProvider, error) {
My preference is to keep everything defined on a struct in the same file as the struct definition. The bulk of creating the impl's lives in separate searchable files: `commit_provider.go` and `exec_provider.go`

2024-06-13 14:42 UTC, patrickhuie19 commented on core/services/relay/evm/evm.go
> +func chainToUUID(chainID *big.Int) uuid.UUID {
Moved out evm/ccip.go - deleted this file since 80% is now dead code

2024-06-20 13:00 UTC, dimkouv commented on core/services/ocr2/delegate.go
> +	if err != nil {
it was something like this:
```
if err != nil {
   return err
}

doSomething()

if err != nil { // <--- duplicate check
   return err
}

but now looks fixed

2024-06-25 14:32 UTC, krehermann approved these changes

2024-06-26 08:11 UTC, dimkouv approved these changes

2024-06-26 10:16 UTC, ilija42 commented on core/services/relay/evm/evm.go
> +func (r *Relayer) NewCCIPCommitProvider(rargs commontypes.RelayArgs, pargs commontypes.PluginArgs) (commontypes.CCIPCommitProvider, error) {
don't these changes also need to be added to core?

2024-06-26 14:25 UTC, ilija42 commented on core/services/relay/evm/evm.go
> +func (r *Relayer) NewCCIPCommitProvider(rargs commontypes.RelayArgs, pargs commontypes.PluginArgs) (commontypes.CCIPCommitProvider, error) {
https://github.com/smartcontractkit/chainlink/pull/13635/commits/eafb6428e3de98f806686dd5d2451857a11b0c8a

2024-06-26 14:27 UTC, patrickhuie19 commented on core/services/relay/evm/evm.go
> +func (r *Relayer) NewCCIPCommitProvider(rargs commontypes.RelayArgs, pargs commontypes.PluginArgs) (commontypes.CCIPCommitProvider, error) {
Ah yea; thanks. We do merge CCIP into core on a regular cadence, but perhaps not fast enough in this case.

2024-06-27 17:55 UTC, merged