Feat/ccip 2466 HomeChain config syncer
smartcontractkit/ccip pull request #978
Opened 2024-06-07 10:02 UTC by asoliman92

## Motivation

Plugins need to refresh HomeChain config regularly to know which oracles support which chains and the latest F for each chain.

## Solution

2024-06-07 14:55 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/common_types.go
> +package cciptypes
Copied from Chainlink-common, ignore.

2024-06-07 14:56 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/common_types_test.go
> +package cciptypes
Copied from Chainlink-common, ignore

2024-06-07 14:56 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/config.go
> +package cciptypes
Important changes next..

2024-06-07 14:56 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/config.go
> +	// TODO: delete
Removing these..

2024-06-07 14:57 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/config.go
> +	PricedTokens []types.Account `json:"pricedTokens"`
I think this should be part of `ObservationConsensus` struct not the plugin config. It seems that it will be changing and we need to reach consensus on it between observers in DON.
CC @dimkouv @makramkd

2024-06-07 14:58 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/config.go
> +// TODO: Add all following
All the following till the end of file is new.

2024-06-07 14:58 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/config.go
> +type OnChainCapabilityConfig struct {
@makramkd Can you double check that I'm doing this correctly?

2024-06-07 14:59 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/generic_types.go
> +package cciptypes
Copied from Chainlink-common, ignore.

2024-06-07 15:00 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/generic_types_test.go
> +package cciptypes
Copied from Chainlink-common, ignore.

2024-06-07 15:00 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/interfaces.go
> +package cciptypes
Some changes coming here.

2024-06-07 15:00 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/plugin_commit_types.go
> +package cciptypes
Important changes here.

2024-06-07 15:01 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/plugin_commit_types.go
> +	ConsensusObservation ConsensusObservation `json:"consensusObservation"`
Removed PluginConfig and using `ConsensusObservation` instead that has only fields relevant for observations that we need to reach consensus on.

2024-06-07 15:03 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/plugin_commit_types_test.go
> +package cciptypes
Copied from Chainlink-common, ignore.

2024-06-07 15:03 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/ccipocr3-dont-merge/plugin_execute_types.go
> +package cciptypes
Copied from Chainlink-common, ignore.

2024-06-07 15:05 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	go homeChainPoller.StartPolling(ctx, 360*time.Second)
I think generally we shouldn't be able to create the plugin without having `homeChainConfig` ready, it's a field inside `homeChainPoller`. These checks should happen in the factory before even starting the plugin IMO. Or if we're moving the Poller to be on JobSpec level that will be something else as well.

2024-06-07 15:06 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	if err := validateObserverReadingEligibility(ao.Observer, obs.NewMsgs, homeChainConfig.NodeSupportedChains); err != nil {
CC @dimkouv

2024-06-10 10:36 UTC, dimkouv requested changes

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/mocks/home_chain_poller.go
> +	*mock.Mock
`Mock` is not used.
Is the intention to use `Mock` or the statically defined config and `Close` to always return `nil`? IMO we should use `Mock`

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/mocks/home_chain_reader.go
> +	*mock.Mock
Same here (comment on `Mock`)

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	log.Println("Start Polling HomeChainConfig")
We should use `logger` similar to plugins.

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	log.Println("Start Polling HomeChainConfig")
And use proper log levels e.g. info or debug here.

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +			r.homeChainConfig = homeConfig
There is a race condition on this variable.

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +func (r *HomeChainConfigPoller) GetSupportedChains(oracleID commontypes.OracleID) mapset.Set[cciptypes.ChainSelector] {
This method is not used.

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +				log.Println("Error polling DB:", err)
If you get an error you overwrite with an empty config.

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return cciptypes.HomeChainConfig{}, err
wrap the errors using `fmt.Errorf("some msg: %w", err)`

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +func (r *HomeChainConfigPoller) fetchLatestConfig(ctx context.Context) (cciptypes.HomeChainConfig, error) {
This function has two responsibilities.
Get config and set config in the state of the poller.
Either rename it or make it have one.

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	return nil
I think we should stop the work that `startPolling` is doing when `Close` is called.

2024-06-10 10:36 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	var fChain = make(map[cciptypes.ChainSelector]int)
Initialize with
```
fChain := make(...

// instead of

var fChain = make(...
```

2024-06-10 13:33 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +func (r *HomeChainConfigPoller) GetSupportedChains(oracleID commontypes.OracleID) mapset.Set[cciptypes.ChainSelector] {
It's used in `Observation` step

2024-06-10 13:47 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/mocks/home_chain_poller.go
> +	*mock.Mock
Agreed 👍

2024-06-12 17:05 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/factory.go
> +	var oracleIDToP2pID map[commontypes.OracleID]cciptypes.P2PID // TODO: Get this from ocr config, it's the mapping of the oracleId index in the DON https://docs.google.com/document/d/1nyGUeterqc9P4ztG
Make sure to use injected ocr3Config into the plugin factory and use it to construct the `oracleIDToP2pID`

2024-06-19 09:39 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/ccip.go
> +
```suggestion

```

2024-06-20 11:00 UTC, makramkd requested changes
Only read the PR briefly, will be back to look at it some more

2024-06-20 11:00 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin.go
>  	}
Don't start the poller here, it will be started outside of the plugin. Can inject it as a dependency though

2024-06-20 11:00 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +
Unnecessary newline

2024-06-20 11:00 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
You can use `StartStopOnce` to handle all possible start <-> stop state transitions

2024-06-20 11:00 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
Means you can get rid of your mutex

2024-06-20 11:00 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}()
Put this `func` in a method

2024-06-20 11:00 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +				return
The `ctx` given to `Start` should not be used like this, there's no guarantee it'll be long lived

2024-06-20 11:04 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +}
We want to store the full chain config of all chains in this struct, seems like it only has the FChain and the NodeSupportedChains from homeChainConfig

2024-06-20 11:04 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	return nil
If you use `StartStopOnce` you can call `StopOnce` here instead

2024-06-20 18:23 UTC, dimkouv submitted a review, later dismissed

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	consensusObservation := cciptypes.ConsensusObservation{
why `consensusObservation` isn't it just some observed config? There is not consensus logic applied to this data.

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	consensusObservation := cciptypes.ConsensusObservation{
the observed items now are:
```
(msgs, gasprices, tokenprices, seqnums, consensusObservation)
```

which seems weird

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	if !homeChainConfig.IsSupported(p.oracleIDToP2pID[p.nodeID], p.cfg.DestChain) {
should become: `p.supportsChain(p.cfg.destChain)`

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +// If a sequence number is pending (is not on-chain yet), it will be included in the results.
That's not true.

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +// This will be used to reach consensus on the observed seqNums and if plugin can read dest chain it should be able to contribute to the observation.
This comment should not be here. Probably some copy/pasting error.

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +		//TODO: Make sure that the observer can read the chain
This is not required, we checked that in the validation phase

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
>  func pluginConfigConsensus(
The returned value has `NodeSupportedChains` field empty.

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +	if len(seqNums) > 0 && !supportedChains.IsSupported(destChain) {
maybe rename `IsSupported` to `Contains`

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		ticker := time.NewTicker(12 * time.Second)
let's not use hardcoded values

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		lggr:            lggr,
initialize all fields and make mutex a pointer

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		// We don't want to return an actual error here as it's already working as expected
You can return an error, client should handle it

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		// We don't want to return an actual error here as it's already working as expected
You never unlock, this will lead to big issues

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +			case <-ctx.Done():
no need to check `ctx`, `bgCtx` includes it

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +				return
if that's the case probably need to do:
```
bgCtx, cancelFunc := context.WithCancel(context.background())
```

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +				_ = r.fetchAndSetConfig(ctx)
we'll miss all this errors?

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +func (r *HomeChainConfigPoller) GetSupportedChains(p2pID cciptypes.P2PID) mapset.Set[cciptypes.ChainSelector] {
this method is not called by anyone

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return errors.New("Cancel function not set")
Error string should not be capitalized or end with punctuation mark

2024-06-20 18:23 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return errors.New("Cancel function not set")
non necessary newline

2024-06-20 18:41 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +}
It's a byte array, I left it out for now until we understand what we need to map it into exactly.

2024-06-20 18:42 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		// We don't want to return an actual error here as it's already working as expected
good catch!

2024-06-20 18:45 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +func (r *HomeChainConfigPoller) GetSupportedChains(p2pID cciptypes.P2PID) mapset.Set[cciptypes.ChainSelector] {
Called here: https://github.com/smartcontractkit/ccip/blob/8afb0844b3ac49f34f703ed73d4b9f5f4ca0017f/core/services/ocr3/plugins/ccip/commit/plugin.go#L103-L103

2024-06-20 18:50 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +				_ = r.fetchAndSetConfig(ctx)
I'm logging inside the `fetchAndSetConfig`, would logging here be better in this case?

2024-06-20 18:54 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +				return
What's the need of the given context in this case then? The way I see it, that the Start function will be called at launch which means that the context should outlive any other plugin contexts. WDYT?

2024-06-20 22:23 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	consensusObservation := cciptypes.ConsensusObservation{
I wanted to group them so that it's easier to access them and group them in later stages. I'll check how we use it later again, maybe just flattening it is really better.

2024-06-20 23:07 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
>  	}
It's already injected as a dependency. This is like a safeguard if it wasn't called earlier to be called here as it won't actually start a new one if it was already started. Do you think it's better to check for the Health and if it wasn't healthy to stop running the plugin completely?

2024-06-20 23:36 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +}
For the OCR3 config, It's better to add in another PR IMO. This PR is already full of changes. Any objections to that?

2024-06-21 00:34 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		lggr:            lggr,
Why a pointer?

2024-06-21 05:28 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin_e2e_test.go
> +		//TODO: I think this test is not correct, it should error because no readers are set up for it.
@dimkouv ?

2024-06-21 05:30 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> +// If a sequence number is pending (is not on-chain yet), it will be included in the results.
Yes. I wrote it early on when I was still a bit confused about readers/writers..etc

2024-06-21 05:48 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
I checked how the `StateMachine` (the newer name for `StartStopOnce` is being used. We still need to have a stop channel and then stop it in `Close` for it to work. I can do it for consistency but it's not less code or clearer than this.

2024-06-21 12:11 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/factory.go
> +		nil,
Can we add comments to these `nil` fields so we know what they are (until they get fully specified):

```suggestion
		nil, /* blah item 1 */
		onChainTokenPricesReader,
		nil, /* blah item 2 */
		nil,
		nil,
		nil,
```

2024-06-21 12:11 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +		return mapset.NewSet[cciptypes.ChainSelector](), nil
If the error is not nil don't return nil for it, return `nil, fmt.Errorf("...: %w", err)`

2024-06-21 12:23 UTC, makramkd reviewed
Need to think about the health check a bit, lack of chain configs is not necessarily an error state

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> -	// Come to consensus on what the feeTokens are.
@dimkouv is it ok that we removed this?

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	services.StateMachine
Style nit: put embedded objects at the beginning of the struct decl

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
I don't think we should fail to start if we couldn't fetch it the first time. We should just go into the `poll` loop and keep retrying on failure

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +			if err != nil {
Style nit: saves one line

```suggestion
			if err := r.fetchAndSetConfigs(ctx); err != nil {
```

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return fmt.Errorf("no on chain configs found")
This is not necessarily an error, there can legitimately be no chain configs onchain yet (i.e for a fresh deployment)

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	r.mutex.Unlock()
Cleaner to put this in a func that does the state updates and do a `r.mutex.Lock()` and `defer r.mutex.Unlock()`, these lines kinda blend together atm.

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return nil, errors.New("no chain configs found")
This is not an error

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return nil, fmt.Errorf("no known chain configs")
Not an error

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return nil, fmt.Errorf("no FChain values found")
Don't think this is an error

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
I don't think this is an error state

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	//iterate over configs
Unnecessary comment

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +type OnChainConfig struct {
I dislike this name, onchainConfig already means something in the OCR context and it could get confusing

2024-06-21 12:23 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		return fmt.Errorf("no on chain configs found")
You can log a warning though

2024-06-21 12:33 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +		return mapset.NewSet[cciptypes.ChainSelector](), nil
Do we want to fail though in case no supportedChains or just return empty set? returning empty set will make the flow smoother during the plugin run.

2024-06-21 12:53 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
good point

2024-06-21 13:14 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +		// TODO: Should we completely fail?
yes

2024-06-21 13:14 UTC, dimkouv commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +func (p *Plugin) getChainConfig() (cciptypes.ChainConfig, error) {
i believe this method is not needed you can call poller.getchainconfig() it's the same thing

2024-06-21 13:20 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +type OnChainConfig struct {
What are your suggestions? Maybe `HomeChainConfigMapper`?

2024-06-21 13:28 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +func (p *Plugin) getChainConfig() (cciptypes.ChainConfig, error) {
It's just a shortcut, calling it from a plugin means get the chain config for the destination chain that this plugin is working with. I might change the name to `getDestChainConfig` to be clearer.

2024-06-24 06:20 UTC, makramkd requested changes

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	libocrtypes "github.com/smartcontractkit/libocr/ragep2p/types"
Can we group the imports correctly? All ccipocr3 imports should be next to each other at the bottom of the import statement since its a local import.

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	destSupportedChains, err := p.supportedChains()
This is just supported chains right? Why is the var called `destSupportedChains`?

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_e2e_test.go
> +
Ditto here re: imports.

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_e2e_test.go
> +
This should be failing the golangci-lint check

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> -	// Come to consensus on what the feeTokens are.
Will this be added back at some point in the future?

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	// How frequent will the poller fetch the chain configs
```suggestion
	// How frequently the poller fetches the chain configs
```

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
What's the point of doing this here if you're going to do it in `poll` anyway?

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	ticker := time.NewTicker(r.pollingInterval * time.Second)
`pollingInterval` is already a `time.Duration`. Multiplying it again by a `time.Second` will not get you the results you seek; `time.Duration` is denominated in nanoseconds, so `time.Second` is actually `1e9` in raw integer terms, so if you specified `pollingInteval` as the logical 12 seconds (block time on ethereum mainnet) this ends up being `1e9 * 12e9 == 12e18` which is actually larger than the largest `int64`.

This is unless you are setting `pollingInterval` to be something like `1`, essentially a multiplier of the `time.Second` value, but this is not the correct usage of the `time.Duration` API. It'll just lead to confusion and bugs.

So this should just be 
```suggestion
	ticker := time.NewTicker(r.pollingInterval)
```

And the `pollingInterval` should be a meaningful `time.Duration` value (e.g `12 * time.Second`, maybe better as a constant instead of a struct field tbh)

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		r.lggr.Warnw("no on chain configs found")
Maybe return early here to avoid the misleading `Setting ChainConfig` log below

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	fChain map[cciptypes.ChainSelector]int
Suggestion: it feels to me that it'd be clearer what the state being tracked by this object is if we collect them all into one object and have that in this struct. For example:

```golang
type state struct {
    // gets updated by the polling loop
	chainConfigs map[cciptypes.ChainSelector]ChainConfig
	// mapping between each node's peerID and the chains it supports. derived from chainConfigs
	nodeSupportedChains map[libocrtypes.PeerID]mapset.Set[cciptypes.ChainSelector]
	// set of chains that are known to CCIP, derived from chainConfigs
	knownSourceChains mapset.Set[cciptypes.ChainSelector]
	// map of chain to FChain value, derived from chainConfigs
	fChain map[cciptypes.ChainSelector]int
}

type HomeChainConfigPoller struct {
    services.StateMachine

    stopCh services.StopChan

	homeChainReader types.ContractReader
    state state
// ...
}
```

This makes it clearer that state updates need to be atomic (i.e on each poll the whole state will be updated, not just part of it).

This might mean you're even able to move the `mutex` to this state object (though not required).

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +
Unnecessary newline

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
Don't think this is right. Here's a suggestion for health report: if the last 10 polls failed, then we are unhealthy.

2024-06-24 06:20 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +			1,
This is not the right usage of the time.Duration API, `1` here is in nanoseconds. You should pass something meaningful to time.Duration in the form usually of existing constants and a multiplier. e.g if you want 12 seconds, you pass in `12 * time.Second`.

2024-06-24 06:24 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin_functions.go
> -	// Come to consensus on what the feeTokens are.
I don't see a reason for adding it back so far. If we need to it should be easy to do it once it's needed.

2024-06-24 06:31 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	destSupportedChains, err := p.supportedChains()
that's a typo, it's supportedChains not destSupportedChains. Thanks for noticing.

2024-06-24 06:40 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	fChain map[cciptypes.ChainSelector]int
Agreed.

2024-06-24 06:41 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	}
To not wait for the ticker and start with a correct state if possible. It also makes testing easier.

2024-06-24 06:55 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	ticker := time.NewTicker(r.pollingInterval * time.Second)
I started initially with `12 * time.Second`. @dimkouv had a comment to make it a variable. You don't see this as a changing parameter or something to experiment with in the future?

2024-06-24 07:04 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +			1,
My bad. I got them mixed.

2024-06-24 10:01 UTC, makramkd approved these changes

2024-06-24 10:01 UTC, makramkd commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	s.fChain = createFChain(chainConfigs)
You can just update `r.state` directly like `r.state.chainConfigs = ...` etc. `r` is already a pointer receiver so any member updates happen on object memory

2024-06-24 15:05 UTC, winder commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> +	homeChainPoller reader.HomeChainPoller
nit: consider renaming this to `reader.HomeChain`. The fact that it's polling for changes is not really important from the caller perspective. In fact, for testing we would likely substitute a static implementation of the `reader.HomeChain` interface.

2024-06-24 15:25 UTC, winder commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> -	}
This should still be validated, it looks like some of the values are not part of the home chain. (i.e. ScanBatchSize)

2024-06-24 15:28 UTC, winder commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> -	}
Although, I wonder why it's done during observation rather than initialization...

2024-06-24 15:39 UTC, winder commented on core/services/ocr3/plugins/ccip/commit/plugin_e2e_test.go
> +	chainConfigInfos := []reader.ChainConfigInfo{
A general comment on these tests: there is a lot of mocking and magic numbers which makes it hard to see whats actually being tested...

2024-06-24 15:41 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +type HomeChainConfigPoller struct {
Can this be private?

2024-06-24 15:41 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +) *HomeChainConfigPoller {
Return the interface type

2024-06-24 15:46 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +	return s.chainConfigs[chainSelector], nil
nit: you can do this with a single lookup
```suggestion
	if chainConfig, ok := s.chainConfigs[chainSelector]; ok {
		return chainConfig, nil
	}
	return ChainConfig{}, fmt.Errorf("chain config not found for chain %v", chainSelector)
```

2024-06-24 15:52 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +}
Do these need to be public?

2024-06-24 15:52 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +	var tests = []struct {
nit: no need for table driven tests if there's just one test

2024-06-24 15:53 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +	for _, tc := range tests {
```suggestion
	for _, tc := range tests {
		tc := tc
```

2024-06-24 15:55 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +}
```suggestion
}

```

2024-06-24 15:58 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +	_ = configPoller.Start(context.Background())
Even if it cannot return an error now, it should check. (also, this function can return an error)
```suggestion
	err := configPoller.Start(context.Background())
	require.NoError(t, err)
```

2024-06-24 16:01 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +func (r *HomeChainConfigPoller) convertOnChainConfigToHomeChainConfig(capabilityConfigs []ChainConfigInfo) (map[cciptypes.ChainSelector]ChainConfig, error) {
This appears to be a pure function
```suggestion
func convertOnChainConfigToHomeChainConfig(capabilityConfigs []ChainConfigInfo) (map[cciptypes.ChainSelector]ChainConfig, error) {
```

2024-06-24 16:03 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +func (r *HomeChainConfigPoller) fetchOnChainConfig(ctx context.Context) ([]ChainConfigInfo, error) {
This function doesn't reduce the number of error checks required by the caller, I'd probably just keep it in fetchAndSetConfigs rather than making it a separate function

2024-06-24 16:04 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +		)
You can skip this setup by making convertOnChainConfigToHomeChainConfig a pure function

2024-06-24 16:06 UTC, winder commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain_test.go
> +	time.Sleep(100 * time.Millisecond)
This is smaller than the polling interval. This is testing that values are fetched during `Start`, not because of the polling.

2024-06-24 16:06 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin.go
> -	}
I think it was an accidental delete. Thanks for noticing 👍

2024-06-24 16:14 UTC, winder approved these changes
Mostly nits and style suggestions, I don't think any of the feedback is strictly blocking. So approved pending your consideration of feedback.

2024-06-24 16:14 UTC, merged

2024-06-24 16:22 UTC, 0xnogo approved these changes

2024-06-24 16:22 UTC, 0xnogo commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +		lggr:            lggr,
The mutex would be passed by value in different places and can potentially break the synchronization logic.

2024-06-24 16:22 UTC, 0xnogo approved these changes

2024-06-24 17:23 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/internal/reader/home_chain.go
> +}
I use them in the e2e tests to simulate the polling fully in the commit plugin

2024-06-24 17:23 UTC, asoliman92 commented on core/services/ocr3/plugins/ccip/commit/plugin_e2e_test.go
> +	chainConfigInfos := []reader.ChainConfigInfo{
I agree with that. I'll address these in another PR 👍